project:
  name: good_microchip_at24c02c_i2c_eeprom_power
  version: 0.1.0

libraries:
  - ../../libs/vendor

board:
  components:
    UEEPROM:
      model: vendor.microchip.at24c02c
      part_number: AT24C02C-SSHM-T
      power_domains:
        VCC: rail_3v3
      pins:
        VCC: rail_3v3
        GND: gnd
        A0: eeprom_a0
        A1: eeprom_a1
        A2: eeprom_a2
        SDA: i2c_sda
        SCL: i2c_scl
        WP: eeprom_wp
  nets:
    rail_3v3:
      kind: power
      nominal_voltage: 3.3
      powered: true
    gnd:
      kind: ground
    eeprom_a0:
      kind: digital_or_analog
      nominal_voltage: 0.0
    eeprom_a1:
      kind: digital_or_analog
      nominal_voltage: 0.0
    eeprom_a2:
      kind: digital_or_analog
      nominal_voltage: 0.0
    i2c_sda:
      kind: digital_or_analog
      nominal_voltage: 3.3
    i2c_scl:
      kind: digital_or_analog
      nominal_voltage: 3.3
    eeprom_wp:
      kind: digital_or_analog
      nominal_voltage: 0.0

scenarios:
  - name: at24c02c_power_tree
    type: power_tree
    checks:
      - POWER_TREE_VALID
