use super::project::{GuiProjectExample, gui_project_examples};

fn gui_project_example_by_id(id: &str) -> GuiProjectExample {
    gui_project_examples()
        .iter()
        .copied()
        .find(|example| example.id == id)
        .unwrap()
}

struct ExpectedProjectExample {
    id: &'static str,
    category: &'static str,
    open_label: &'static str,
    run_label: &'static str,
    summary: &'static str,
    project_path: &'static str,
    project_name: &'static str,
    expected_traces: &'static [&'static str],
    expected_frequency: &'static str,
    observation_preset_component: Option<&'static str>,
}

#[test]
fn gui_project_example_registry_lists_scope_and_observation_fixtures() {
    const EXPECTED: &[ExpectedProjectExample] = &[
        ExpectedProjectExample {
            id: "ne555_astable_scope",
            category: "Timer",
            open_label: "Open NE555 Scope Example",
            run_label: "Open NE555 + Run Scopes",
            summary: "Astable-style timer output with timing-node and source-current traces.",
            project_path: "examples/ne555_astable_scope_smoke/project.yaml",
            project_name: "ne555_astable_scope",
            expected_traces: &["v(out)", "v(timing)", "v(vcc)", "i(VCC)", "i(VOUT)"],
            expected_frequency: "about 1.46 kHz",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "rc_lowpass_scope",
            category: "Filter",
            open_label: "Open RC Low-Pass Scope Example",
            run_label: "Open RC Low-Pass + Run Scopes",
            summary: "1 kHz sine into a first-order low-pass for input/output comparison.",
            project_path: "examples/rc_lowpass_scope/project.yaml",
            project_name: "rc_lowpass_scope",
            expected_traces: &["v(input)", "v(filtered)", "i(VSIN)"],
            expected_frequency: "1.00 kHz sine, fc about 1.59 kHz",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "rc_monte_carlo_bode",
            category: "Yield",
            open_label: "Open RC Monte Carlo Example",
            run_label: "Open RC Monte Carlo + Run Observations",
            summary: "Generated RC low-pass Bode run with sampled R/C tolerances and yield checks.",
            project_path: "examples/good_generated_rc_lowpass_monte_carlo_observation/project.yaml",
            project_name: "good_generated_rc_lowpass_monte_carlo_observation",
            expected_traces: &[
                "input_gain_db",
                "filtered_gain_db",
                "filtered_phase_deg",
                "filtered_mag",
            ],
            expected_frequency: "5 sampled R/C tolerance Bode runs with yield and P5 margin criteria",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "comparator_threshold_scope",
            category: "Comparator",
            open_label: "Open Comparator Threshold Example",
            run_label: "Open Comparator + Run Scopes",
            summary: "Pulse input against a DC reference for output-state threshold checks.",
            project_path: "examples/comparator_threshold_scope/project.yaml",
            project_name: "comparator_threshold_scope",
            expected_traces: &["v(input)", "v(reference)", "v(output)", "v(vcc)"],
            expected_frequency: "80 us input pulse crossing a 1.2 V reference",
            observation_preset_component: Some("XU1"),
        },
        ExpectedProjectExample {
            id: "opamp_buffer_scope",
            category: "Op-Amp",
            open_label: "Open Op-Amp Buffer Example",
            run_label: "Open Op-Amp Buffer + Run Scopes",
            summary: "Unity-gain buffer tracking a pulse input with output settling checks.",
            project_path: "examples/good_ideal_opamp_buffer/project.yaml",
            project_name: "good_ideal_opamp_buffer",
            expected_traces: &["v(input)", "v(output)", "v(vcc)"],
            expected_frequency: "80 us input pulse through unity feedback",
            observation_preset_component: Some("XU1"),
        },
        ExpectedProjectExample {
            id: "ch340c_usb_uart_scope",
            category: "USB-UART",
            open_label: "Open CH340C USB-UART Example",
            run_label: "Open CH340C + Run Scopes",
            summary: "Source-backed CH340C bridge output-state observation for boot/control lines.",
            project_path: "examples/good_wch_ch340c_usb_uart_observation/project.yaml",
            project_name: "good_wch_ch340c_usb_uart_observation",
            expected_traces: &["v_vcc", "v_txd", "v_dtr_n", "v_rts_n"],
            expected_frequency: "3.3 V CH340C observation with TXD high, DTR# low, and RTS# high",
            observation_preset_component: Some("UUSB"),
        },
        ExpectedProjectExample {
            id: "cp2102n_usb_uart_scope",
            category: "USB-UART",
            open_label: "Open CP2102N USB-UART Example",
            run_label: "Open CP2102N + Run Scopes",
            summary: "Source-backed CP2102N regulator and UART output-state observation.",
            project_path: "examples/good_silabs_cp2102n_usb_uart_observation/project.yaml",
            project_name: "good_silabs_cp2102n_usb_uart_observation",
            expected_traces: &["v_vregin", "v_vdd", "v_txd", "v_rts", "v_dtr"],
            expected_frequency: "5 V VREGIN, regulated VDD/VIO, TXD high, RTS high, and DTR low",
            observation_preset_component: Some("UUSB"),
        },
        ExpectedProjectExample {
            id: "ft232r_usb_uart_scope",
            category: "USB-UART",
            open_label: "Open FT232R USB-UART Example",
            run_label: "Open FT232R + Run Scopes",
            summary: "Source-backed FT232R bridge 3V3OUT and UART output-state observation.",
            project_path: "examples/good_ftdi_ft232r_usb_uart_observation/project.yaml",
            project_name: "good_ftdi_ft232r_usb_uart_observation",
            expected_traces: &["v_vcc", "v_3v3out", "v_txd", "v_rts_n", "v_dtr_n"],
            expected_frequency: "5 V VCC, generated 3V3OUT/VCCIO, TXD high, RTS# high, and DTR# low",
            observation_preset_component: Some("UUSB"),
        },
        ExpectedProjectExample {
            id: "ch347_usb_jtag_scope",
            category: "Debug",
            open_label: "Open CH347 USB-JTAG Example",
            run_label: "Open CH347 + Run Scopes",
            summary: "Source-backed CH347 USB-JTAG bridge line-state observation.",
            project_path: "examples/good_wch_ch347_usb_jtag_observation/project.yaml",
            project_name: "good_wch_ch347_usb_jtag_observation",
            expected_traces: &[
                "v_vcc", "v_txd1", "v_tms", "v_tck", "v_tdi", "v_tdo", "v_trst",
            ],
            expected_frequency: "3.3 V CH347 debug bridge with TXD1/TMS/TDI/TRST high and TCK low",
            observation_preset_component: Some("UDBG"),
        },
        ExpectedProjectExample {
            id: "cmsis_dap_swd_scope",
            category: "Debug",
            open_label: "Open CMSIS-DAP SWD Example",
            run_label: "Open CMSIS-DAP + Run Scopes",
            summary: "Source-backed generic CMSIS-DAP SWD probe line-state observation.",
            project_path: "examples/good_cmsis_dap_swd_probe_observation/project.yaml",
            project_name: "good_cmsis_dap_swd_probe_observation",
            expected_traces: &["v_vtref", "v_swclk", "v_swdio", "v_nreset", "v_swo"],
            expected_frequency: "3.3 V target reference with CMSIS-DAP SWD idle high lines and released reset",
            observation_preset_component: Some("UPROBE"),
        },
        ExpectedProjectExample {
            id: "stm32l431_boot_uart_swd_scope",
            category: "MCU",
            open_label: "Open STM32L431 Boot/UART/SWD Example",
            run_label: "Open STM32L431 + Run Scopes",
            summary: "Source-backed STM32L431 rail, reset, BOOT0, USART1, and SWD line-state observation.",
            project_path: "examples/good_stm32l431_boot_uart_swd_observation/project.yaml",
            project_name: "good_stm32l431_boot_uart_swd_observation",
            expected_traces: &[
                "v_vdd",
                "v_nrst",
                "v_boot0",
                "v_pa9_usart1_tx",
                "v_pa10_usart1_rx",
                "v_pa13_swdio",
                "v_pa14_swclk",
            ],
            expected_frequency: "3.3 V STM32L431 with NRST released, BOOT0 low, USART1 idle high, and SWD idle lines",
            observation_preset_component: Some("UMCU"),
        },
        ExpectedProjectExample {
            id: "esp32_s3_wroom_boot_usb_scope",
            category: "MCU",
            open_label: "Open ESP32-S3 Boot/USB Example",
            run_label: "Open ESP32-S3 + Run Scopes",
            summary: "Source-backed ESP32-S3 module supply, EN, boot-strap, and USB line-state observation.",
            project_path: "examples/good_esp32_s3_wroom_boot_usb_observation/project.yaml",
            project_name: "good_esp32_s3_wroom_boot_usb_observation",
            expected_traces: &[
                "v_3v3", "v_en", "v_io0", "v_io46", "v_usb_dm", "v_usb_dp", "v_txd0",
            ],
            expected_frequency: "3.3 V ESP32-S3 module with EN high, GPIO0 high, GPIO46 low, USB D+ high, and D- low",
            observation_preset_component: Some("UMCU"),
        },
        ExpectedProjectExample {
            id: "esp32_wroom_32e_boot_uart_scope",
            category: "MCU",
            open_label: "Open ESP32-WROOM-32E Boot/UART Example",
            run_label: "Open ESP32-WROOM-32E + Run Scopes",
            summary: "Source-backed ESP32-WROOM-32E module supply, EN, boot-strap, and UART line-state observation.",
            project_path: "examples/good_esp32_wroom_32e_boot_uart_observation/project.yaml",
            project_name: "good_esp32_wroom_32e_boot_uart_observation",
            expected_traces: &["v_3v3", "v_en", "v_io0", "v_io2", "v_txd0"],
            expected_frequency: "3.3 V ESP32-WROOM-32E module with EN high, GPIO0 high, GPIO2 low, and TXD0 idle high",
            observation_preset_component: Some("UESP"),
        },
        ExpectedProjectExample {
            id: "licheerv_nano_w_scope",
            category: "Module",
            open_label: "Open LicheeRV-Nano-W Example",
            run_label: "Open LicheeRV-Nano-W + Run Scopes",
            summary: "Source-backed LicheeRV-Nano-W module power, UART, motion-enable, and fault-IRQ observation.",
            project_path: "examples/good_sipeed_licheerv_nano_w_observation/project.yaml",
            project_name: "good_sipeed_licheerv_nano_w_observation",
            expected_traces: &[
                "v_5v",
                "v_uart0_tx",
                "v_uart0_rx",
                "v_motion_en",
                "v_fault_irq",
            ],
            expected_frequency: "5 V LicheeRV-Nano-W module with UART0 TX/RX high, motion enable high, and fault IRQ low",
            observation_preset_component: Some("USOM"),
        },
        ExpectedProjectExample {
            id: "at32f435_motion_core_scope",
            category: "MCU",
            open_label: "Open AT32F435 Motion-Core Example",
            run_label: "Open AT32F435 + Run Scopes",
            summary: "Source-backed AT32F435 motion-core rail, UART, CAN, RS-485, and control-line observation.",
            project_path: "examples/good_artery_at32f435_motion_core_observation/project.yaml",
            project_name: "good_artery_at32f435_motion_core_observation",
            expected_traces: &[
                "v_vdd",
                "v_lrv_uart_rx",
                "v_lrv_uart_tx",
                "v_lrv_motion_en",
                "v_motion_fault_irq",
                "v_can_tx",
                "v_can_rx",
                "v_rs485_tx",
                "v_rs485_rx",
                "v_rs485_de",
                "v_servo_pwm_oe",
            ],
            expected_frequency: "3.3 V AT32F435 motion core with Linux UART and field-bus control lines in idle/ready states",
            observation_preset_component: Some("UMCU"),
        },
        ExpectedProjectExample {
            id: "at32m416_motor_control_scope",
            category: "MCU",
            open_label: "Open AT32M416 Motor-Control Example",
            run_label: "Open AT32M416 + Run Scopes",
            summary: "Source-backed AT32M416 motor-control rail, CAN, PWM, driver, encoder, and fault-line observation.",
            project_path: "examples/good_artery_at32m416_motor_control_observation/project.yaml",
            project_name: "good_artery_at32m416_motor_control_observation",
            expected_traces: &[
                "v_vdd",
                "v_can_tx",
                "v_can_rx",
                "v_pwm_uh",
                "v_pwm_ul",
                "v_pwm_vl",
                "v_drv_en",
                "v_drv_nfault",
                "v_drv_spi_cs",
                "v_cur_u",
                "v_enc_a",
                "v_fault_out",
            ],
            expected_frequency: "3.3 V AT32M416 motor-control MCU with driver, CAN, encoder, and control lines in idle/ready states",
            observation_preset_component: Some("UMCU"),
        },
        ExpectedProjectExample {
            id: "txs0108e_level_scope",
            category: "Level Shifter",
            open_label: "Open TXS0108E Level-Shifter Example",
            run_label: "Open TXS0108E + Run Scopes",
            summary: "Source-backed TXS0108E enabled A-to-B mixed-voltage observation.",
            project_path: "examples/good_ti_txs0108e_level_shifter_observation/project.yaml",
            project_name: "good_ti_txs0108e_level_shifter_observation",
            expected_traces: &["v_vcca", "v_vccb", "v_oe", "v_a1", "v_b1", "i_b1_load"],
            expected_frequency: "1.8 V A-side input translated to a 3.3 V B-side high level",
            observation_preset_component: Some("ULS"),
        },
        ExpectedProjectExample {
            id: "nl27wz17_logic_buffer_scope",
            category: "Logic",
            open_label: "Open NL27WZ17 Logic Buffer Example",
            run_label: "Open NL27WZ17 + Run Scopes",
            summary: "Source-backed dual Schmitt-buffer input/output line-state observation.",
            project_path: "examples/good_onsemi_nl27wz17_logic_buffer_observation/project.yaml",
            project_name: "good_onsemi_nl27wz17_logic_buffer_observation",
            expected_traces: &["v_vcc", "v_1a", "v_1y", "v_2a", "v_2y"],
            expected_frequency: "3.3 V NL27WZ17 buffer with 1A high mirrored to 1Y and 2A low mirrored to 2Y",
            observation_preset_component: Some("UBUF"),
        },
        ExpectedProjectExample {
            id: "jst_xh_servo_connector_scope",
            category: "Connector",
            open_label: "Open JST XH Connector Example",
            run_label: "Open JST XH + Run Scopes",
            summary: "Source-backed JST XH mated-contact voltage-drop observation.",
            project_path: "examples/good_jst_xh_servo_connector_observation/project.yaml",
            project_name: "good_jst_xh_servo_connector_observation",
            expected_traces: &["v_vcc_board", "v_vcc_load", "v_sig_load", "v_gnd_load"],
            expected_frequency: "JST XH 3-pin servo connector contact-drop observation at 1 A equivalent load",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "jst_vh_actuator_connector_scope",
            category: "Connector",
            open_label: "Open JST VH Connector Example",
            run_label: "Open JST VH + Run Scopes",
            summary: "Source-backed JST VH actuator-bus mated-contact voltage-drop observation.",
            project_path: "examples/good_jst_vh_actuator_bus_connector_observation/project.yaml",
            project_name: "good_jst_vh_actuator_bus_connector_observation",
            expected_traces: &[
                "v_vbat_load",
                "v_aux5_load",
                "v_canh_load",
                "v_canl_load",
                "v_enable_load",
                "v_fault_load",
                "v_sync_load",
                "v_gnd_load",
            ],
            expected_frequency: "JST VH 8-pin actuator-bus connector contact-drop observation at 5 A equivalent load",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "tpd2eusb30_esd_scope",
            category: "Protection",
            open_label: "Open TPD2EUSB30 ESD Example",
            run_label: "Open TPD2EUSB30 + Run Scopes",
            summary: "Source-backed USB ESD standoff and line-capacitance observation.",
            project_path: "examples/good_tpd2eusb30_usb_esd_observation/project.yaml",
            project_name: "good_tpd2eusb30_usb_esd_observation",
            expected_traces: &["v_dp", "v_dm", "i_dp_source", "i_dm_source"],
            expected_frequency: "normal USB data-line voltages below the 5.5 V TPD2EUSB30 standoff limit",
            observation_preset_component: Some("UESD"),
        },
        ExpectedProjectExample {
            id: "prtr5v0u2x_esd_scope",
            category: "Protection",
            open_label: "Open PRTR5V0U2X ESD Example",
            run_label: "Open PRTR5V0U2X + Run Scopes",
            summary: "Source-backed rail-to-rail USB ESD standoff and capacitance observation.",
            project_path: "examples/good_nexperia_prtr5v0u2x_usb_esd_observation/project.yaml",
            project_name: "good_nexperia_prtr5v0u2x_usb_esd_observation",
            expected_traces: &[
                "v_vbus",
                "v_dp",
                "v_dm",
                "i_vbus_source",
                "i_dp_source",
                "i_dm_source",
            ],
            expected_frequency: "normal USB VBUS and data-line voltages below the 5.5 V PRTR5V0U2X standoff limit",
            observation_preset_component: Some("UESD"),
        },
        ExpectedProjectExample {
            id: "esd2can24_q1_scope",
            category: "Protection",
            open_label: "Open ESD2CAN24-Q1 Example",
            run_label: "Open ESD2CAN24-Q1 + Run Scopes",
            summary: "Source-backed CAN ESD standoff and line-capacitance observation.",
            project_path: "examples/good_ti_esd2can24_q1_can_esd_observation/project.yaml",
            project_name: "good_ti_esd2can24_q1_can_esd_observation",
            expected_traces: &["v_canh", "v_canl", "i_canh_source", "i_canl_source"],
            expected_frequency: "normal CANH/CANL voltages below the 24 V ESD2CAN24-Q1 standoff limit",
            observation_preset_component: Some("UESD"),
        },
        ExpectedProjectExample {
            id: "tcan3413_can_scope",
            category: "Interface",
            open_label: "Open TCAN3413 CAN Example",
            run_label: "Open TCAN3413 + Run Scopes",
            summary: "Source-backed CAN transceiver dominant line-state observation.",
            project_path: "examples/good_ti_tcan3413_can_transceiver_observation/project.yaml",
            project_name: "good_ti_tcan3413_can_transceiver_observation",
            expected_traces: &[
                "v_vcc", "v_vio", "v_txd", "v_stb", "v_rxd", "v_canh", "v_canl",
            ],
            expected_frequency: "3.3 V normal-mode TCAN3413 CAN dominant line-state observation",
            observation_preset_component: Some("UCAN"),
        },
        ExpectedProjectExample {
            id: "drv8323_gate_driver_scope",
            category: "Motor Driver",
            open_label: "Open DRV8323 Gate-Driver Example",
            run_label: "Open DRV8323 + Run Scopes",
            summary: "Source-backed DRV8323 supply, fault, SPI-output, and current-sense observation.",
            project_path: "examples/good_drv8323_gate_driver_observation/project.yaml",
            project_name: "good_drv8323_gate_driver_observation",
            expected_traces: &[
                "v_vm", "v_dvdd", "v_enable", "v_nfault", "v_sdo", "v_soa", "v_sob", "v_soc",
            ],
            expected_frequency: "24 V VM and 3.3 V DVDD/ENABLE DRV8323 gate-driver observation",
            observation_preset_component: Some("UDRV"),
        },
        ExpectedProjectExample {
            id: "pca9685_pwm_scope",
            category: "PWM Driver",
            open_label: "Open PCA9685 PWM Example",
            run_label: "Open PCA9685 + Run Scopes",
            summary: "Source-backed PCA9685 VDD, OE, I2C idle, and low-load PWM output observation.",
            project_path: "examples/good_pca9685_pwm_driver_observation/project.yaml",
            project_name: "good_pca9685_pwm_driver_observation",
            expected_traces: &[
                "v_vdd", "v_oe", "v_scl", "v_sda", "v_pwm0", "v_pwm1", "v_pwm2", "v_pwm3",
            ],
            expected_frequency: "3.3 V enabled PCA9685 with 50 Hz low-load PWM output observation",
            observation_preset_component: Some("UPWM"),
        },
        ExpectedProjectExample {
            id: "icm42688p_imu_scope",
            category: "Sensor",
            open_label: "Open ICM-42688-P IMU Example",
            run_label: "Open ICM-42688-P + Run Scopes",
            summary: "Source-backed ICM-42688-P rail, SPI line-state, and interrupt observation.",
            project_path: "examples/good_tdk_icm42688p_imu_observation/project.yaml",
            project_name: "good_tdk_icm42688p_imu_observation",
            expected_traces: &[
                "v_vdd", "v_vddio", "v_sclk", "v_sdi", "v_cs", "v_sdo", "v_int1",
            ],
            expected_frequency: "3.3 V ICM-42688-P IMU rails, SPI idle line states, SDO low, and INT1 high",
            observation_preset_component: Some("UIMU"),
        },
        ExpectedProjectExample {
            id: "esds552_scope",
            category: "Protection",
            open_label: "Open ESDS552 Example",
            run_label: "Open ESDS552 + Run Scopes",
            summary: "Source-backed RS-485/RS-422 ESD standoff and line-capacitance observation.",
            project_path: "examples/good_ti_esds552_rs485_esd_observation/project.yaml",
            project_name: "good_ti_esds552_rs485_esd_observation",
            expected_traces: &["v_rs485_a", "v_rs485_b", "i_a_source", "i_b_source"],
            expected_frequency: "normal RS-485 A/B voltages below the 12 V ESDS552 standoff limit",
            observation_preset_component: Some("UESD"),
        },
        ExpectedProjectExample {
            id: "thvd1450_rs485_scope",
            category: "Interface",
            open_label: "Open THVD1450 RS-485 Example",
            run_label: "Open THVD1450 + Run Scopes",
            summary: "Source-backed RS-485 transceiver line-state observation.",
            project_path: "examples/good_ti_thvd1450_rs485_transceiver_observation/project.yaml",
            project_name: "good_ti_thvd1450_rs485_transceiver_observation",
            expected_traces: &[
                "v_vcc",
                "v_di",
                "v_de",
                "v_re_n",
                "v_ro",
                "v_rs485_a",
                "v_rs485_b",
            ],
            expected_frequency: "3.3 V enabled THVD1450 RS-485 driver/receiver line-state observation",
            observation_preset_component: Some("UTRX"),
        },
        ExpectedProjectExample {
            id: "ap2112k_ldo_scope",
            category: "Regulator",
            open_label: "Open AP2112K LDO Example",
            run_label: "Open AP2112K + Run Scopes",
            summary: "Enabled 3.3 V LDO rail with load-current and output-window checks.",
            project_path: "examples/good_ap2112k_3v3_ldo_observation/project.yaml",
            project_name: "good_ap2112k_3v3_ldo_observation",
            expected_traces: &["v_usb", "v_en", "v_rail3v3", "i_load"],
            expected_frequency: "5 V enabled input, 3.3 V regulated load rail",
            observation_preset_component: Some("UREG"),
        },
        ExpectedProjectExample {
            id: "ams1117_ldo_scope",
            category: "Regulator",
            open_label: "Open AMS1117 LDO Example",
            run_label: "Open AMS1117 + Run Scopes",
            summary: "Fixed 3.3 V AMS1117 rail with output capacitor and minimum-load checks.",
            project_path: "examples/good_ams1117_3v3_ldo_observation/project.yaml",
            project_name: "good_ams1117_3v3_ldo_observation",
            expected_traces: &["v_usb", "v_rail3v3", "i_load"],
            expected_frequency: "5 V input, 3.3 V AMS1117 rail, 22 uF output capacitor, and 10 mA load",
            observation_preset_component: Some("UREG"),
        },
        ExpectedProjectExample {
            id: "tps54331_buck_scope",
            category: "Regulator",
            open_label: "Open TPS54331 Buck Example",
            run_label: "Open TPS54331 + Run Scopes",
            summary: "Enabled 12 V to 5 V buck-regulator rail observation with load-current checks.",
            project_path: "examples/good_tps54331_5v_buck_observation/project.yaml",
            project_name: "good_tps54331_5v_buck_observation",
            expected_traces: &["v_input", "v_enable", "v_rail5v", "i_load"],
            expected_frequency: "12 V input, 3.3 V enable, and 5 V buck-regulator rail observation",
            observation_preset_component: Some("UBUCK"),
        },
        ExpectedProjectExample {
            id: "tps62162_buck_scope",
            category: "Regulator",
            open_label: "Open TPS62162 Buck Example",
            run_label: "Open TPS62162 + Run Scopes",
            summary: "Enabled 12 V to 3.3 V buck-regulator rail observation with load-current checks.",
            project_path: "examples/good_tps62162_3v3_buck_observation/project.yaml",
            project_name: "good_tps62162_3v3_buck_observation",
            expected_traces: &["v_input", "v_enable", "v_rail3v3", "i_load"],
            expected_frequency: "12 V input, 3.3 V enable, and 3.3 V buck-regulator rail observation",
            observation_preset_component: Some("UBUCK"),
        },
        ExpectedProjectExample {
            id: "tps63802_buck_boost_scope",
            category: "Regulator",
            open_label: "Open TPS63802 Buck-Boost Example",
            run_label: "Open TPS63802 + Run Scopes",
            summary: "Enabled Li-Ion input to 3.3 V buck-boost rail observation with load-current checks.",
            project_path: "examples/good_tps63802_3v3_buck_boost_observation/project.yaml",
            project_name: "good_tps63802_3v3_buck_boost_observation",
            expected_traces: &["v_battery", "v_enable", "v_rail3v3", "i_load"],
            expected_frequency: "3.7 V input, 3.3 V enable, and 3.3 V buck-boost rail observation",
            observation_preset_component: Some("UREG"),
        },
        ExpectedProjectExample {
            id: "tps61023_boost_scope",
            category: "Regulator",
            open_label: "Open TPS61023 Boost Example",
            run_label: "Open TPS61023 + Run Scopes",
            summary: "Enabled Li-Ion input to 5 V boost-regulator rail observation with load-current checks.",
            project_path: "examples/good_tps61023_5v_boost_observation/project.yaml",
            project_name: "good_tps61023_5v_boost_observation",
            expected_traces: &["v_battery", "v_enable", "v_rail5v", "i_load"],
            expected_frequency: "3.7 V input, 3.3 V enable, and 5 V boost-regulator rail observation",
            observation_preset_component: Some("UBOOST"),
        },
        ExpectedProjectExample {
            id: "tps22918_load_switch_scope",
            category: "Load Switch",
            open_label: "Open TPS22918 Load Switch Example",
            run_label: "Open TPS22918 + Run Scopes",
            summary: "Enabled 5 V load switch path with switched-rail and load-current checks.",
            project_path: "examples/good_tps22918_load_switch_observation/project.yaml",
            project_name: "good_tps22918_load_switch_observation",
            expected_traces: &["v_usb", "v_on", "v_switched5v", "i_load"],
            expected_frequency: "5 V enabled load switch into a 1 kOhm load",
            observation_preset_component: Some("USW"),
        },
        ExpectedProjectExample {
            id: "tps25948_efuse_scope",
            category: "eFuse",
            open_label: "Open TPS25948 eFuse Example",
            run_label: "Open TPS25948 + Run Scopes",
            summary: "Enabled 12 V eFuse/load-switch path with protected-rail and load-current checks.",
            project_path: "examples/good_tps25948_efuse_observation/project.yaml",
            project_name: "good_tps25948_efuse_observation",
            expected_traces: &["v_input", "v_enable", "v_protected12v", "i_load"],
            expected_frequency: "12 V enabled eFuse/load-switch path into a 120 ohm load",
            observation_preset_component: Some("UEFUSE"),
        },
        ExpectedProjectExample {
            id: "tps24751_hot_swap_scope",
            category: "eFuse",
            open_label: "Open TPS24751 Hot-Swap Example",
            run_label: "Open TPS24751 + Run Scopes",
            summary: "Enabled 12 V hot-swap/reverse-blocking path with protected-rail and load-current checks.",
            project_path: "examples/good_tps24751_hot_swap_observation/project.yaml",
            project_name: "good_tps24751_hot_swap_observation",
            expected_traces: &["v_input", "v_enable", "v_protected12v", "i_load"],
            expected_frequency: "12 V enabled hot-swap/reverse-blocking path into a 120 ohm load",
            observation_preset_component: Some("UHOTSWAP"),
        },
        ExpectedProjectExample {
            id: "tps2121_power_mux_scope",
            category: "Power Mux",
            open_label: "Open TPS2121 Power Mux Example",
            run_label: "Open TPS2121 + Run Scopes",
            summary: "USB-selected 5 V power-mux path with output rail and load-current checks.",
            project_path: "examples/good_tps2121_power_mux_observation/project.yaml",
            project_name: "good_tps2121_power_mux_observation",
            expected_traces: &["v_usb", "v_backup", "v_sys5v", "i_load"],
            expected_frequency: "5 V USB-selected input through a TPS2121 power-mux rail observation",
            observation_preset_component: Some("UMUX"),
        },
        ExpectedProjectExample {
            id: "tps2115a_power_mux_scope",
            category: "Power Mux",
            open_label: "Open TPS2115A Power Mux Example",
            run_label: "Open TPS2115A + Run Scopes",
            summary: "USB-selected 5 V autoswitching power-mux path with output rail and load-current checks.",
            project_path: "examples/good_tps2115a_power_mux_observation/project.yaml",
            project_name: "good_tps2115a_power_mux_observation",
            expected_traces: &["v_usb", "v_backup", "v_mode", "v_sys5v", "i_load"],
            expected_frequency: "5 V USB-selected input through a TPS2115A power-mux rail observation",
            observation_preset_component: Some("UMUX"),
        },
        ExpectedProjectExample {
            id: "mcp73831_charger_scope",
            category: "Charger",
            open_label: "Open MCP73831 Charger Example",
            run_label: "Open MCP73831 + Run Scopes",
            summary: "USB-powered Li-Ion charger with PROG-current and VBAT checks.",
            project_path: "examples/good_mcp73831_charger_observation/project.yaml",
            project_name: "good_mcp73831_charger_observation",
            expected_traces: &["v_usb", "v_bat", "i_charge"],
            expected_frequency: "5 V USB input, 10 kOhm PROG resistor, and 100 mA charge observation",
            observation_preset_component: Some("UCHG"),
        },
        ExpectedProjectExample {
            id: "bq24075_power_path_scope",
            category: "Power Path",
            open_label: "Open BQ24075 Power Path Example",
            run_label: "Open BQ24075 + Run Scopes",
            summary: "Adapter-powered charger with OUT rail and BAT charge-current checks.",
            project_path: "examples/good_bq24075_power_path_observation/project.yaml",
            project_name: "good_bq24075_power_path_observation",
            expected_traces: &["v_adapter", "v_sysout", "v_bat", "i_charge", "i_sys_load"],
            expected_frequency: "6 V adapter input, 5.5 V OUT path, and 450 mA ISET charge observation",
            observation_preset_component: Some("UCHG"),
        },
        ExpectedProjectExample {
            id: "bq25798_nvdc_scope",
            category: "Power Path",
            open_label: "Open BQ25798 NVDC Example",
            run_label: "Open BQ25798 + Run Scopes",
            summary: "20 V adapter buck-boost/NVDC charger observation with SYS and BAT checks.",
            project_path: "examples/good_bq25798_nvdc_observation/project.yaml",
            project_name: "good_bq25798_nvdc_observation",
            expected_traces: &["v_adapter", "v_sysout", "v_bat", "i_charge", "i_sys_load"],
            expected_frequency: "20 V adapter input, 12 V SYS rail, and 2 A programmed charge observation",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "tlv803_reset_scope",
            category: "Reset",
            open_label: "Open TLV803 Reset Example",
            run_label: "Open TLV803 + Run Scopes",
            summary: "Reset-supervisor threshold release from a pulsed 3.3 V rail.",
            project_path: "examples/good_tlv803ea29_reset_observation/project.yaml",
            project_name: "good_tlv803ea29_reset_observation",
            expected_traces: &["v_rail", "reset_n"],
            expected_frequency: "3.3 V rail ramp with reset release",
            observation_preset_component: Some("URESET"),
        },
        ExpectedProjectExample {
            id: "loop_stability_bode_scope",
            category: "Stability",
            open_label: "Open Loop Stability Bode Example",
            run_label: "Open Loop Stability + Run Scopes",
            summary: "Open-loop Bode response with executable phase and gain margin checks.",
            project_path: "examples/loop_stability_bode_scope/project.yaml",
            project_name: "loop_stability_bode_scope",
            expected_traces: &["loop_mag_db", "loop_phase_deg", "loop_mag"],
            expected_frequency: "Bode loop gain with phase margin >45 deg and gain margin >6 dB",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "dc_bias_observation",
            category: "Bias",
            open_label: "Open DC Bias Example",
            run_label: "Open DC Bias + Run Observations",
            summary: "Generated operating-point divider bias with resistor-tolerance margin checks.",
            project_path: "examples/good_dc_bias_observation/project.yaml",
            project_name: "good_dc_bias_observation",
            expected_traces: &["vin", "midpoint"],
            expected_frequency: "DC operating point with 9 divider-tolerance corners",
            observation_preset_component: None,
        },
        ExpectedProjectExample {
            id: "noise_observation",
            category: "Noise",
            open_label: "Open Noise Observation Example",
            run_label: "Open Noise + Run Observations",
            summary: "Generated divider noise density and integrated RMS noise checks.",
            project_path: "examples/good_noise_observation/project.yaml",
            project_name: "good_noise_observation",
            expected_traces: &[
                "onoise_density",
                "inoise_density",
                "onoise_total",
                "inoise_total",
            ],
            expected_frequency: "10 Hz to 100 kHz divider output and input-referred RMS noise",
            observation_preset_component: None,
        },
    ];

    let examples = gui_project_examples();
    assert_eq!(examples.len(), EXPECTED.len());

    for expected in EXPECTED {
        let example = gui_project_example_by_id(expected.id);
        assert_eq!(example.id, expected.id);
        assert_eq!(example.category, expected.category);
        assert_eq!(example.open_label, expected.open_label);
        assert_eq!(example.run_label, expected.run_label);
        assert_eq!(example.summary, expected.summary);
        assert_eq!(example.project_path, expected.project_path);
        assert_eq!(example.project_name, expected.project_name);
        assert_eq!(example.expected_traces, expected.expected_traces);
        assert_eq!(example.expected_frequency, expected.expected_frequency);
        assert_eq!(
            example.observation_preset_component,
            expected.observation_preset_component
        );
    }
}
