use anyhow::{Context, Result, bail};
use serde::Serialize;
use serde_yaml_ng::{Mapping, Value};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct ExcellonDrillImportOptions {
    pub drill: PathBuf,
    pub project: PathBuf,
    pub output: PathBuf,
}

#[derive(Debug, Clone, Default)]
pub struct ExcellonDrillImportSummary {
    pub drill_hits: usize,
    pub tools: usize,
    pub plated_hits: usize,
    pub non_plated_hits: usize,
    pub unknown_plating_hits: usize,
}

#[derive(Debug, Clone, Copy, Serialize)]
struct DrillPoint {
    x_mm: f64,
    y_mm: f64,
}

#[derive(Debug, Clone)]
struct ParsedDrillFile {
    layer: String,
    plating: DrillPlating,
    tools: BTreeMap<String, f64>,
    hits: Vec<DrillHit>,
}

#[derive(Debug, Clone)]
struct DrillHit {
    at: DrillPoint,
    drill_mm: f64,
    tool: String,
    source_hit_index: usize,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
enum DrillPlating {
    Plated,
    NonPlated,
    Unknown,
}

#[derive(Debug, Serialize)]
struct DrillYaml {
    at: DrillPoint,
    drill_mm: f64,
    plating: DrillPlating,
    layer: String,
    tool: String,
    source_hit_index: usize,
}

#[derive(Debug, Clone, Copy)]
struct DrillState {
    metric: bool,
    absolute: bool,
    decimals: Option<u32>,
}

impl Default for DrillState {
    fn default() -> Self {
        Self {
            metric: false,
            absolute: true,
            decimals: None,
        }
    }
}

pub fn import_excellon_drill(
    options: &ExcellonDrillImportOptions,
) -> Result<ExcellonDrillImportSummary> {
    let text = fs::read_to_string(&options.drill)
        .with_context(|| format!("Failed to read drill file {}", options.drill.display()))?;
    let parsed = parse_excellon_drill(&text, &options.drill)?;
    let project_text = fs::read_to_string(&options.project).with_context(|| {
        format!(
            "Failed to read Board IR project {}",
            options.project.display()
        )
    })?;
    let mut project_yaml: Value = serde_yaml_ng::from_str(&project_text).with_context(|| {
        format!(
            "Failed to parse Board IR project YAML {}",
            options.project.display()
        )
    })?;
    merge_drills_into_project(&mut project_yaml, &parsed)?;
    absolutize_relative_libraries(
        &mut project_yaml,
        options.project.parent().unwrap_or_else(|| Path::new(".")),
    )?;
    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create import output directory {}",
                parent.display()
            )
        })?;
    }
    let mut yaml = serde_yaml_ng::to_string(&project_yaml)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI by adding Excellon/NC drill evidence to Board IR.\n",
    );
    fs::write(&options.output, yaml)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    Ok(summary_for_drill_file(&parsed))
}

fn parse_excellon_drill(text: &str, path: &Path) -> Result<ParsedDrillFile> {
    let mut state = DrillState::default();
    let mut layer = "drill".to_string();
    let mut plating = DrillPlating::Unknown;
    let mut tools = BTreeMap::new();
    let mut current_tool: Option<String> = None;
    let mut hits = Vec::new();
    for (line_index, raw_line) in text.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() {
            continue;
        }
        if let Some(comment) = line.strip_prefix(';') {
            if let Some(value) = comment.trim().strip_prefix("TYPE=") {
                plating = match value.trim() {
                    "PLATED" => DrillPlating::Plated,
                    "NON_PLATED" => DrillPlating::NonPlated,
                    _ => DrillPlating::Unknown,
                };
            } else if let Some(value) = comment.trim().strip_prefix("Layer:") {
                let value = value.trim();
                if !value.is_empty() {
                    layer = value.to_string();
                }
            }
            continue;
        }
        if line == "M48" || line == "%" || line == "G05" {
            continue;
        }
        if line == "M30" {
            break;
        }
        if line == "G90" {
            state.absolute = true;
            continue;
        }
        if line == "G91" {
            bail!(
                "Drill file {} uses incremental coordinates; only absolute coordinates are supported.",
                path.display()
            );
        }
        if line.starts_with("INCH") || line.starts_with("MOIN") {
            bail!(
                "Drill file {} uses inches; only metric drill imports are currently supported.",
                path.display()
            );
        }
        if line.starts_with("METRIC") {
            state.metric = true;
            state.decimals = decimal_count_from_metric_record(line);
            continue;
        }
        if let Some((tool, diameter_mm)) = parse_tool_definition(line, path)? {
            if tools.insert(tool.clone(), diameter_mm).is_some() {
                bail!(
                    "Drill file {} defines tool {} more than once.",
                    path.display(),
                    tool
                );
            }
            continue;
        }
        if is_tool_selection(line) {
            if !tools.contains_key(line) {
                bail!(
                    "Drill file {} selects undefined tool {}.",
                    path.display(),
                    line
                );
            }
            current_tool = Some(line.to_string());
            continue;
        }
        if line.starts_with('X') || line.starts_with('Y') {
            if !state.metric {
                bail!(
                    "Drill file {} has coordinates before METRIC units.",
                    path.display()
                );
            }
            if !state.absolute {
                bail!("Drill file {} is not in absolute mode.", path.display());
            }
            let tool = current_tool.clone().with_context(|| {
                format!(
                    "Drill file {} has coordinate hit before tool selection at line {}.",
                    path.display(),
                    line_index + 1
                )
            })?;
            let drill_mm = *tools.get(&tool).with_context(|| {
                format!(
                    "Drill file {} selected undefined tool {}.",
                    path.display(),
                    tool
                )
            })?;
            let at = parse_hit_point(line, state.decimals, path)?;
            hits.push(DrillHit {
                at,
                drill_mm,
                tool,
                source_hit_index: hits.len(),
            });
            continue;
        }
        bail!(
            "Drill file {} has unsupported command at line {}: {}.",
            path.display(),
            line_index + 1,
            line
        );
    }
    if tools.is_empty() {
        bail!("Drill file {} defines no drill tools.", path.display());
    }
    if hits.is_empty() {
        bail!("Drill file {} contains no drill hits.", path.display());
    }
    Ok(ParsedDrillFile {
        layer,
        plating,
        tools,
        hits,
    })
}

fn decimal_count_from_metric_record(line: &str) -> Option<u32> {
    line.rsplit(',')
        .next()
        .and_then(|format| format.split_once('.'))
        .map(|(_, fractional)| fractional.chars().filter(char::is_ascii_digit).count() as u32)
        .filter(|count| *count > 0)
}

fn parse_tool_definition(line: &str, path: &Path) -> Result<Option<(String, f64)>> {
    if !line.starts_with('T') || !line.contains('C') {
        return Ok(None);
    }
    let Some((tool, diameter)) = line.split_once('C') else {
        return Ok(None);
    };
    if tool.len() <= 1
        || !tool[1..]
            .chars()
            .all(|character| character.is_ascii_digit())
    {
        return Ok(None);
    }
    let diameter_text = diameter
        .chars()
        .take_while(|character| character.is_ascii_digit() || *character == '.')
        .collect::<String>();
    let diameter_mm = diameter_text.parse::<f64>().with_context(|| {
        format!(
            "Drill file {} has invalid tool diameter in {}.",
            path.display(),
            line
        )
    })?;
    if !diameter_mm.is_finite() || diameter_mm <= 0.0 {
        bail!(
            "Drill file {} tool {} has non-positive diameter.",
            path.display(),
            tool
        );
    }
    Ok(Some((tool.to_string(), diameter_mm)))
}

fn is_tool_selection(line: &str) -> bool {
    line.len() > 1 && line.starts_with('T') && line[1..].chars().all(|c| c.is_ascii_digit())
}

fn parse_hit_point(line: &str, decimals: Option<u32>, path: &Path) -> Result<DrillPoint> {
    let x_text = coordinate_field(line, 'X').with_context(|| {
        format!(
            "Drill file {} hit is missing X coordinate: {}.",
            path.display(),
            line
        )
    })?;
    let y_text = coordinate_field(line, 'Y').with_context(|| {
        format!(
            "Drill file {} hit is missing Y coordinate: {}.",
            path.display(),
            line
        )
    })?;
    let x_mm = parse_coordinate_mm(x_text, decimals, path)?;
    let y_mm = parse_coordinate_mm(y_text, decimals, path)?;
    if !(x_mm.is_finite() && y_mm.is_finite()) {
        bail!(
            "Drill file {} produced non-finite coordinates.",
            path.display()
        );
    }
    Ok(DrillPoint { x_mm, y_mm })
}

fn coordinate_field(line: &str, axis: char) -> Option<&str> {
    let start = line.find(axis)? + axis.len_utf8();
    let bytes = line.as_bytes();
    let mut end = start;
    if matches!(bytes.get(end), Some(b'-' | b'+')) {
        end += 1;
    }
    while matches!(bytes.get(end), Some(byte) if byte.is_ascii_digit() || *byte == b'.') {
        end += 1;
    }
    (end > start).then_some(&line[start..end])
}

fn parse_coordinate_mm(value: &str, decimals: Option<u32>, path: &Path) -> Result<f64> {
    if value.contains('.') {
        return value.parse::<f64>().with_context(|| {
            format!(
                "Drill file {} has invalid decimal coordinate {}.",
                path.display(),
                value
            )
        });
    }
    let decimals = decimals.with_context(|| {
        format!(
            "Drill file {} uses integer coordinates without a decimal format declaration.",
            path.display()
        )
    })?;
    let raw = value.parse::<i64>().with_context(|| {
        format!(
            "Drill file {} has invalid integer coordinate {}.",
            path.display(),
            value
        )
    })?;
    Ok(raw as f64 / 10_i64.pow(decimals) as f64)
}

fn merge_drills_into_project(project_yaml: &mut Value, parsed: &ParsedDrillFile) -> Result<()> {
    let board = mapping_field_mut(project_yaml, "board")?;
    let layout = mapping_field_in_mapping_mut(board, "layout")?;
    let drills_key = Value::String("drills".to_string());
    if !layout.contains_key(&drills_key) {
        layout.insert(drills_key.clone(), Value::Sequence(Vec::new()));
    }
    let drills = layout
        .get_mut(&drills_key)
        .expect("drills field was inserted when absent")
        .as_sequence_mut()
        .context("Board IR field board.layout.drills must be a list.")?;
    for hit in &parsed.hits {
        drills.push(
            serde_yaml_ng::to_value(DrillYaml {
                at: hit.at,
                drill_mm: hit.drill_mm,
                plating: parsed.plating,
                layer: parsed.layer.clone(),
                tool: hit.tool.clone(),
                source_hit_index: hit.source_hit_index,
            })
            .context("Failed to serialize drill evidence into Board IR YAML.")?,
        );
    }
    Ok(())
}

fn mapping_field_mut<'a>(value: &'a mut Value, key: &str) -> Result<&'a mut Mapping> {
    let mapping = value
        .as_mapping_mut()
        .with_context(|| format!("Expected YAML object while reading {key}."))?;
    mapping
        .get_mut(Value::String(key.to_string()))
        .with_context(|| format!("Board IR project is missing {key}."))?
        .as_mapping_mut()
        .with_context(|| format!("Board IR field {key} must be an object."))
}

fn mapping_field_in_mapping_mut<'a>(
    mapping: &'a mut Mapping,
    key: &str,
) -> Result<&'a mut Mapping> {
    mapping
        .get_mut(Value::String(key.to_string()))
        .with_context(|| format!("Board IR project is missing board.{key}."))?
        .as_mapping_mut()
        .with_context(|| format!("Board IR field board.{key} must be an object."))
}

fn summary_for_drill_file(parsed: &ParsedDrillFile) -> ExcellonDrillImportSummary {
    ExcellonDrillImportSummary {
        drill_hits: parsed.hits.len(),
        tools: parsed.tools.len(),
        plated_hits: usize::from(parsed.plating == DrillPlating::Plated) * parsed.hits.len(),
        non_plated_hits: usize::from(parsed.plating == DrillPlating::NonPlated) * parsed.hits.len(),
        unknown_plating_hits: usize::from(parsed.plating == DrillPlating::Unknown)
            * parsed.hits.len(),
    }
}

fn absolutize_relative_libraries(project_yaml: &mut Value, project_dir: &Path) -> Result<()> {
    let mapping = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    let Some(libraries) = mapping.get_mut(Value::String("libraries".to_string())) else {
        return Ok(());
    };
    let libraries = libraries
        .as_sequence_mut()
        .context("Board IR field libraries must be a list.")?;
    for library in libraries {
        let Some(path_text) = library.as_str() else {
            bail!("Board IR libraries entries must be strings.");
        };
        let path = Path::new(path_text);
        if path.is_absolute() {
            continue;
        }
        let resolved = normalize_path(&project_dir.join(path));
        let absolute = fs::canonicalize(&resolved).unwrap_or(resolved);
        *library = Value::String(absolute.to_string_lossy().to_string());
    }
    Ok(())
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    normalized
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_metric_plated_drill_hits() {
        let text = r#"
;TYPE=PLATED
;Layer: PTH_Through
M48
METRIC,LZ,0000.00000
T01C0.30500
T02C1.00000
%
G05
G90
T01
X29.3Y-8.64001
T02
X1000000Y-2000000
M30
"#;
        let parsed = parse_excellon_drill(text, Path::new("fixture.drl")).unwrap();
        assert_eq!(parsed.plating, DrillPlating::Plated);
        assert_eq!(parsed.layer, "PTH_Through");
        assert_eq!(parsed.tools.len(), 2);
        assert_eq!(parsed.hits.len(), 2);
        assert_eq!(parsed.hits[0].at.x_mm, 29.3);
        assert_eq!(parsed.hits[0].drill_mm, 0.305);
        assert_eq!(parsed.hits[1].at.x_mm, 10.0);
        assert_eq!(parsed.hits[1].at.y_mm, -20.0);
    }

    #[test]
    fn rejects_undefined_tool_selection() {
        let text = "M48\nMETRIC,LZ,0000.00000\n%\nT01\nX1.0Y2.0\nM30\n";
        let error = parse_excellon_drill(text, Path::new("bad.drl")).unwrap_err();
        assert!(error.to_string().contains("selects undefined tool"));
    }
}
