use anyhow::{Context, Result, bail};
use serde::Serialize;
use serde_json::Value as JsonValue;
use serde_yaml_ng::{Mapping, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const POINT_EPSILON_MM: f64 = 1.0e-9;

#[derive(Debug, Clone)]
pub struct EasyedaFlyingProbeImportOptions {
    pub input: PathBuf,
    pub project: PathBuf,
    pub output: PathBuf,
    pub default_model: String,
}

#[derive(Debug, Clone, Default)]
pub struct EasyedaFlyingProbeImportSummary {
    pub pin_rows: usize,
    pub connected_pin_rows: usize,
    pub pads_imported: usize,
    pub duplicate_pin_rows: usize,
    pub multipart_pin_rows: usize,
    pub skipped_unconnected_pins: usize,
    pub components_created: usize,
    pub nets_imported: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PlacementSide {
    Top,
    Bottom,
}

#[derive(Debug, Clone, PartialEq)]
struct ImportedPad {
    component: String,
    pin: String,
    net: String,
    at: LayoutPointYaml,
    layers: Vec<String>,
    kind: String,
    shape: String,
    size: LayoutSizeYaml,
    rotation_deg: f64,
    drill_mm: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
struct LayoutPointYaml {
    x_mm: f64,
    y_mm: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
struct LayoutSizeYaml {
    x_mm: f64,
    y_mm: f64,
}

#[derive(Debug, Serialize)]
struct LayoutPadYaml {
    at: LayoutPointYaml,
    net: String,
    layers: Vec<String>,
    kind: String,
    shape: String,
    size: LayoutSizeYaml,
    rotation_deg: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    drill_mm: Option<f64>,
}

#[derive(Debug, Serialize)]
struct ImportedComponentYaml {
    model: String,
    pins: BTreeMap<String, String>,
    source: ImportedComponentSourceYaml,
}

#[derive(Debug, Serialize)]
struct ImportedComponentSourceYaml {
    format: String,
    note: String,
}

#[derive(Debug, Serialize)]
struct NetYaml {
    kind: String,
}

pub fn import_easyeda_flying_probe(
    options: &EasyedaFlyingProbeImportOptions,
) -> Result<EasyedaFlyingProbeImportSummary> {
    let input_text = fs::read_to_string(&options.input)
        .with_context(|| format!("Failed to read {}", options.input.display()))?;
    let parsed = parse_easyeda_flying_probe(&input_text, &options.input)?;

    let project_text = fs::read_to_string(&options.project)
        .with_context(|| format!("Failed to read {}", options.project.display()))?;
    let mut project_yaml: Value = serde_yaml_ng::from_str(&project_text)
        .with_context(|| format!("Failed to parse {}", options.project.display()))?;
    let summary = merge_pads_into_project(&mut project_yaml, &parsed, &options.default_model)?;
    absolutize_relative_libraries(
        &mut project_yaml,
        options.project.parent().unwrap_or_else(|| Path::new(".")),
    )?;

    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create EasyEDA flying-probe import output directory {}",
                parent.display()
            )
        })?;
    }
    let mut output = serde_yaml_ng::to_string(&project_yaml)?;
    output.insert_str(
        0,
        "# Generated by CircuitCI from EasyEDA/JLC flying-probe pad and net evidence.\n",
    );
    fs::write(&options.output, output)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    Ok(summary)
}

fn parse_easyeda_flying_probe(text: &str, input: &Path) -> Result<ParsedFlyingProbe> {
    let root: JsonValue = serde_json::from_str(text)
        .with_context(|| format!("Failed to parse {}", input.display()))?;
    let unit = required_str_field(&root, "lengthUnit")?;
    let unit_scale = match unit {
        "mil" => 0.0254,
        "mm" => 1.0,
        other => bail!(
            "EasyEDA flying-probe file {} uses unsupported lengthUnit {other:?}; expected mil or mm.",
            input.display()
        ),
    };
    let pins = root
        .get("pins")
        .context("EasyEDA flying-probe file is missing pins object.")?;
    let fields = pins
        .get("fields")
        .and_then(JsonValue::as_array)
        .context("EasyEDA flying-probe pins.fields must be an array.")?
        .iter()
        .map(|field| {
            field
                .as_str()
                .map(str::to_string)
                .context("EasyEDA flying-probe pins.fields entries must be strings.")
        })
        .collect::<Result<Vec<_>>>()?;
    let field_indices = fields
        .iter()
        .enumerate()
        .map(|(index, field)| (field.as_str(), index))
        .collect::<BTreeMap<_, _>>();
    for required in [
        "PIN_NAME",
        "PIN_X",
        "PIN_Y",
        "LAYER",
        "PIN_TYPE",
        "NET_NAME",
        "PAD_SHAPE",
        "PAD_SIZEX",
        "PAD_SIZEY",
        "HOLE_SIZE",
        "PAD_ANGLE",
    ] {
        if !field_indices.contains_key(required) {
            bail!("EasyEDA flying-probe pins.fields is missing required column {required}.");
        }
    }

    let rows = pins
        .get("rows")
        .and_then(JsonValue::as_array)
        .context("EasyEDA flying-probe pins.rows must be an array.")?;
    let mut imported: BTreeMap<(String, String), Vec<ImportedPad>> = BTreeMap::new();
    let mut summary = EasyedaFlyingProbeImportSummary {
        pin_rows: rows.len(),
        ..EasyedaFlyingProbeImportSummary::default()
    };
    for (row_index, row) in rows.iter().enumerate() {
        let row = row.as_array().with_context(|| {
            format!("EasyEDA flying-probe pin row {row_index} is not an array.")
        })?;
        let net = cell_string(row, &field_indices, "NET_NAME", row_index)?;
        if net.trim().is_empty() {
            summary.skipped_unconnected_pins += 1;
            continue;
        }
        let pin_name = cell_string(row, &field_indices, "PIN_NAME", row_index)?;
        let (component, pin) = pin_name.rsplit_once('_').with_context(|| {
            format!(
                "EasyEDA flying-probe PIN_NAME {pin_name:?} in row {row_index} must end with _<pin>."
            )
        })?;
        if component.is_empty() || pin.is_empty() {
            bail!(
                "EasyEDA flying-probe PIN_NAME {pin_name:?} in row {row_index} has empty component or pin."
            );
        }
        let layer = map_layer(
            cell_string(row, &field_indices, "LAYER", row_index)?,
            row_index,
        )?;
        let kind = map_pin_kind(
            cell_string(row, &field_indices, "PIN_TYPE", row_index)?,
            row_index,
        )?;
        let shape = map_pad_shape(
            cell_string(row, &field_indices, "PAD_SHAPE", row_index)?,
            row_index,
        )?;
        let x_mm = cell_number(row, &field_indices, "PIN_X", row_index)? * unit_scale;
        let y_mm = cell_number(row, &field_indices, "PIN_Y", row_index)? * unit_scale;
        let size_x_mm = cell_number(row, &field_indices, "PAD_SIZEX", row_index)? * unit_scale;
        let size_y_mm = cell_number(row, &field_indices, "PAD_SIZEY", row_index)? * unit_scale;
        if size_x_mm <= 0.0 || size_y_mm <= 0.0 {
            bail!(
                "EasyEDA flying-probe pin row {row_index} has non-positive pad size ({size_x_mm}, {size_y_mm}) mm."
            );
        }
        let rotation_deg = cell_number(row, &field_indices, "PAD_ANGLE", row_index)?;
        let drill_mm = positive_optional_number(row, &field_indices, "HOLE_SIZE", row_index)?
            .map(|drill| drill * unit_scale);
        let pad = ImportedPad {
            component: component.to_string(),
            pin: pin.to_string(),
            net: net.to_string(),
            at: LayoutPointYaml { x_mm, y_mm },
            layers: vec![layer],
            kind,
            shape,
            size: LayoutSizeYaml {
                x_mm: size_x_mm,
                y_mm: size_y_mm,
            },
            rotation_deg,
            drill_mm,
        };
        let key = (pad.component.clone(), pad.pin.clone());
        if let Some(existing_pads) = imported.get_mut(&key) {
            if existing_pads
                .iter()
                .any(|existing| pads_equivalent(existing, &pad))
            {
                summary.duplicate_pin_rows += 1;
                continue;
            }
            if existing_pads
                .iter()
                .all(|existing| pads_are_compatible_multipart(existing, &pad))
            {
                summary.multipart_pin_rows += 1;
                existing_pads.push(pad);
                summary.connected_pin_rows += 1;
                continue;
            }
            bail!(
                "EasyEDA flying-probe pin row {row_index} conflicts with an earlier row for {}.{}.",
                pad.component,
                pad.pin
            );
        }
        imported.insert(key, vec![pad]);
        summary.connected_pin_rows += 1;
    }
    if imported.is_empty() {
        bail!(
            "EasyEDA flying-probe import found no connected pads in {}.",
            input.display()
        );
    }
    let pads = imported
        .into_values()
        .flat_map(|pads| {
            pads.into_iter().enumerate().map(|(index, mut pad)| {
                if index > 0 {
                    pad.pin = format!("{}#{}", pad.pin, index + 1);
                }
                pad
            })
        })
        .collect();
    Ok(ParsedFlyingProbe { pads, summary })
}

#[derive(Debug, Clone)]
struct ParsedFlyingProbe {
    pads: Vec<ImportedPad>,
    summary: EasyedaFlyingProbeImportSummary,
}

fn merge_pads_into_project(
    project_yaml: &mut Value,
    parsed: &ParsedFlyingProbe,
    default_model: &str,
) -> Result<EasyedaFlyingProbeImportSummary> {
    let root = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    {
        let board = mapping_field_mut(root, "board")?;
        ensure_mapping_field_mut(board, "components")?;
        ensure_mapping_field_mut(board, "nets")?;
        let layout = ensure_mapping_field_mut(board, "layout")?;
        ensure_mapping_field_mut(layout, "pads")?;
    }

    let existing_nets = {
        let board = mapping_field_mut(root, "board")?;
        let nets = ensure_mapping_field_mut(board, "nets")?;
        nets.keys()
            .filter_map(Value::as_str)
            .map(str::to_string)
            .collect::<BTreeSet<_>>()
    };
    let mut summary = parsed.summary.clone();
    for pad in &parsed.pads {
        let component_key = Value::String(pad.component.clone());
        {
            let board = mapping_field_mut(root, "board")?;
            let components = ensure_mapping_field_mut(board, "components")?;
            if !components.contains_key(&component_key) {
                let component = ImportedComponentYaml {
                    model: default_model.to_string(),
                    pins: BTreeMap::new(),
                    source: ImportedComponentSourceYaml {
                        format: "easyeda_flying_probe".to_string(),
                        note: "Pad-only placeholder created from flying-probe ownership evidence."
                            .to_string(),
                    },
                };
                components.insert(component_key.clone(), serde_yaml_ng::to_value(component)?);
                summary.components_created += 1;
            }
        }

        let net_key = Value::String(pad.net.clone());
        {
            let board = mapping_field_mut(root, "board")?;
            let nets = ensure_mapping_field_mut(board, "nets")?;
            if !nets.contains_key(&net_key) {
                nets.insert(
                    net_key.clone(),
                    serde_yaml_ng::to_value(NetYaml {
                        kind: classify_net_kind(&pad.net).to_string(),
                    })?,
                );
                if !existing_nets.contains(&pad.net) {
                    summary.nets_imported += 1;
                }
            }
        }

        let layers = resolved_pad_layers(root, pad)?;
        let board = mapping_field_mut(root, "board")?;
        let layout = ensure_mapping_field_mut(board, "layout")?;
        let pads_root = ensure_mapping_field_mut(layout, "pads")?;
        let component_pads = if let Some(component_pads) = pads_root.get_mut(&component_key) {
            component_pads.as_mapping_mut().with_context(|| {
                format!(
                    "Board IR board.layout.pads.{} must be a YAML object.",
                    pad.component
                )
            })?
        } else {
            pads_root.insert(component_key.clone(), Value::Mapping(Mapping::new()));
            pads_root
                .get_mut(&component_key)
                .and_then(Value::as_mapping_mut)
                .expect("inserted mapping")
        };
        component_pads.insert(
            Value::String(pad.pin.clone()),
            serde_yaml_ng::to_value(LayoutPadYaml {
                at: pad.at.clone(),
                net: pad.net.clone(),
                layers,
                kind: pad.kind.clone(),
                shape: pad.shape.clone(),
                size: pad.size.clone(),
                rotation_deg: pad.rotation_deg,
                drill_mm: pad.drill_mm,
            })?,
        );
        summary.pads_imported += 1;
    }
    Ok(summary)
}

fn resolved_pad_layers(root: &mut Mapping, pad: &ImportedPad) -> Result<Vec<String>> {
    if pad.kind == "through_hole" || pad.drill_mm.is_some() {
        return Ok(vec!["F.Cu".to_string(), "B.Cu".to_string()]);
    }
    let Some(side) = placement_side_for_component(root, &pad.component)? else {
        return Ok(pad.layers.clone());
    };
    if pad.layers == ["F.Cu"] && side == PlacementSide::Bottom {
        return Ok(vec!["B.Cu".to_string()]);
    }
    Ok(pad.layers.clone())
}

fn placement_side_for_component(
    root: &mut Mapping,
    component: &str,
) -> Result<Option<PlacementSide>> {
    let board = mapping_field_mut(root, "board")?;
    let Some(layout) = board.get_mut(Value::String("layout".to_string())) else {
        return Ok(None);
    };
    let layout = layout
        .as_mapping_mut()
        .context("Board IR field board.layout must be a YAML object.")?;
    let Some(placements) = layout.get_mut(Value::String("placements".to_string())) else {
        return Ok(None);
    };
    let placements = placements
        .as_mapping_mut()
        .context("Board IR field board.layout.placements must be a YAML object.")?;
    let Some(placement) = placements.get_mut(Value::String(component.to_string())) else {
        return Ok(None);
    };
    let placement = placement.as_mapping_mut().with_context(|| {
        format!("Board IR field board.layout.placements.{component} must be a YAML object.")
    })?;
    let Some(side) = placement.get(Value::String("side".to_string())) else {
        return Ok(None);
    };
    let side = side.as_str().with_context(|| {
        format!("Board IR field board.layout.placements.{component}.side must be a string.")
    })?;
    match side {
        "top" => Ok(Some(PlacementSide::Top)),
        "bottom" => Ok(Some(PlacementSide::Bottom)),
        other => bail!(
            "Board IR field board.layout.placements.{component}.side uses unsupported value {other:?}."
        ),
    }
}

fn mapping_field_mut<'a>(mapping: &'a mut Mapping, field: &str) -> Result<&'a mut Mapping> {
    mapping
        .get_mut(Value::String(field.to_string()))
        .with_context(|| format!("Board IR project is missing required field {field}."))?
        .as_mapping_mut()
        .with_context(|| format!("Board IR field {field} must be a YAML object."))
}

fn ensure_mapping_field_mut<'a>(mapping: &'a mut Mapping, field: &str) -> Result<&'a mut Mapping> {
    let key = Value::String(field.to_string());
    if !mapping.contains_key(&key) {
        mapping.insert(key.clone(), Value::Mapping(Mapping::new()));
    }
    mapping
        .get_mut(&key)
        .and_then(Value::as_mapping_mut)
        .with_context(|| format!("Board IR field {field} must be a YAML object."))
}

fn required_str_field<'a>(root: &'a JsonValue, field: &str) -> Result<&'a str> {
    root.get(field)
        .and_then(JsonValue::as_str)
        .with_context(|| format!("EasyEDA flying-probe field {field} must be a string."))
}

fn cell_string<'a>(
    row: &'a [JsonValue],
    fields: &BTreeMap<&str, usize>,
    field: &str,
    row_index: usize,
) -> Result<&'a str> {
    row.get(fields[field])
        .and_then(JsonValue::as_str)
        .with_context(|| {
            format!("EasyEDA flying-probe pin row {row_index} field {field} must be a string.")
        })
        .map(str::trim)
}

fn cell_number(
    row: &[JsonValue],
    fields: &BTreeMap<&str, usize>,
    field: &str,
    row_index: usize,
) -> Result<f64> {
    let value = row.get(fields[field]).with_context(|| {
        format!("EasyEDA flying-probe pin row {row_index} is missing field {field}.")
    })?;
    let number = match value {
        JsonValue::Number(number) => number.as_f64(),
        JsonValue::String(text) => text.trim().parse::<f64>().ok(),
        _ => None,
    }
    .with_context(|| {
        format!("EasyEDA flying-probe pin row {row_index} field {field} must be numeric.")
    })?;
    if !number.is_finite() {
        bail!("EasyEDA flying-probe pin row {row_index} field {field} is not finite.");
    }
    Ok(number)
}

fn positive_optional_number(
    row: &[JsonValue],
    fields: &BTreeMap<&str, usize>,
    field: &str,
    row_index: usize,
) -> Result<Option<f64>> {
    let number = cell_number(row, fields, field, row_index)?;
    if number < 0.0 {
        bail!("EasyEDA flying-probe pin row {row_index} field {field} is negative.");
    }
    Ok((number > 0.0).then_some(number))
}

fn map_layer(layer: &str, row_index: usize) -> Result<String> {
    match layer {
        "T" | "Top" | "F.Cu" => Ok("F.Cu".to_string()),
        "B" | "Bottom" | "B.Cu" => Ok("B.Cu".to_string()),
        other => {
            bail!("EasyEDA flying-probe pin row {row_index} uses unsupported layer {other:?}.")
        }
    }
}

fn map_pin_kind(kind: &str, row_index: usize) -> Result<String> {
    match kind {
        "SMD" => Ok("smd".to_string()),
        "DIP" => Ok("through_hole".to_string()),
        other => {
            bail!("EasyEDA flying-probe pin row {row_index} uses unsupported PIN_TYPE {other:?}.")
        }
    }
}

fn map_pad_shape(shape: &str, row_index: usize) -> Result<String> {
    match shape {
        "R" => Ok("rect".to_string()),
        "C" => Ok("circle".to_string()),
        "O" => Ok("oval".to_string()),
        "P" => Ok("polygon".to_string()),
        other => {
            bail!("EasyEDA flying-probe pin row {row_index} uses unsupported PAD_SHAPE {other:?}.")
        }
    }
}

fn classify_net_kind(net: &str) -> &'static str {
    let normalized = net.trim().to_ascii_uppercase();
    if normalized == "GND" || normalized.ends_with("_GND") || normalized.ends_with("-GND") {
        "ground"
    } else {
        "digital_or_analog"
    }
}

fn pads_equivalent(first: &ImportedPad, second: &ImportedPad) -> bool {
    first.component == second.component
        && first.pin == second.pin
        && first.net == second.net
        && first.layers == second.layers
        && first.kind == second.kind
        && first.shape == second.shape
        && close(first.at.x_mm, second.at.x_mm)
        && close(first.at.y_mm, second.at.y_mm)
        && close(first.size.x_mm, second.size.x_mm)
        && close(first.size.y_mm, second.size.y_mm)
        && close(first.rotation_deg, second.rotation_deg)
        && match (first.drill_mm, second.drill_mm) {
            (Some(first), Some(second)) => close(first, second),
            (None, None) => true,
            _ => false,
        }
}

fn pads_are_compatible_multipart(first: &ImportedPad, second: &ImportedPad) -> bool {
    first.component == second.component
        && first.pin == second.pin
        && first.net == second.net
        && first.layers == second.layers
        && first.kind == second.kind
        && match (first.drill_mm, second.drill_mm) {
            (Some(first), Some(second)) => close(first, second),
            (None, None) => true,
            _ => false,
        }
}

fn close(first: f64, second: f64) -> bool {
    (first - second).abs() <= POINT_EPSILON_MM
}

fn absolutize_relative_libraries(project_yaml: &mut Value, project_dir: &Path) -> Result<()> {
    let mapping = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    let Some(libraries) = mapping.get_mut(Value::String("libraries".to_string())) else {
        return Ok(());
    };
    let libraries = libraries
        .as_sequence_mut()
        .context("Board IR field libraries must be a list.")?;
    for library in libraries {
        let Some(path_text) = library.as_str() else {
            bail!("Board IR libraries entries must be strings.");
        };
        let path = Path::new(path_text);
        if path.is_absolute() {
            continue;
        }
        let resolved = normalize_path(&project_dir.join(path));
        let absolute = fs::canonicalize(&resolved).unwrap_or(resolved);
        *library = Value::String(absolute.to_string_lossy().to_string());
    }
    Ok(())
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    normalized
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_connected_pads_and_deduplicates_identical_rows() {
        let text = r#"{
  "lengthUnit": "mil",
  "pins": {
    "fields": ["PIN_NO", "PIN_NAME", "PIN_X", "PIN_Y", "LAYER", "PIN_TYPE", "NET_NAME", "NET_TYPE", "PAD_SHAPE", "PAD_SIZEX", "PAD_SIZEY", "HOLE_SIZE", "HOLE_LEN", "PAD_ANGLE"],
    "rows": [
      [1, "J1_1", "1000", "-500", "T", "SMD", "GND", "", "R", "40", "20", "0", "0", "90"],
      [2, "J1_1", "1000", "-500", "T", "SMD", "GND", "", "R", "40", "20", "0", "0", "90"],
      [3, "J1_2", "1100", "-500", "T", "DIP", "VBUS", "", "C", "50", "50", "20", "0", "0"],
      [4, "J1_3", "1200", "-500", "T", "SMD", "", "", "R", "40", "20", "0", "0", "0"]
    ]
  }
}"#;
        let parsed = parse_easyeda_flying_probe(text, Path::new("fixture.json")).unwrap();
        assert_eq!(parsed.summary.pin_rows, 4);
        assert_eq!(parsed.summary.connected_pin_rows, 2);
        assert_eq!(parsed.summary.duplicate_pin_rows, 1);
        assert_eq!(parsed.summary.skipped_unconnected_pins, 1);
        assert_eq!(parsed.pads.len(), 2);
        assert_eq!(parsed.pads[0].component, "J1");
        assert_eq!(parsed.pads[0].pin, "1");
        assert_eq!(parsed.pads[0].layers, ["F.Cu"]);
        assert_eq!(parsed.pads[0].kind, "smd");
        assert!((parsed.pads[0].at.x_mm - 25.4).abs() < 1.0e-12);
        assert!((parsed.pads[1].drill_mm.unwrap() - 0.508).abs() < 1.0e-12);
    }

    #[test]
    fn rejects_conflicting_duplicate_pin_rows() {
        let text = r#"{
  "lengthUnit": "mil",
  "pins": {
    "fields": ["PIN_NAME", "PIN_X", "PIN_Y", "LAYER", "PIN_TYPE", "NET_NAME", "PAD_SHAPE", "PAD_SIZEX", "PAD_SIZEY", "HOLE_SIZE", "PAD_ANGLE"],
    "rows": [
      ["J1_1", "1000", "-500", "T", "SMD", "GND", "R", "40", "20", "0", "0"],
      ["J1_1", "1000", "-500", "T", "SMD", "VBUS", "R", "40", "20", "0", "0"]
    ]
  }
}"#;
        let error = parse_easyeda_flying_probe(text, Path::new("fixture.json")).unwrap_err();
        assert!(error.to_string().contains("conflicts"));
    }
}
