use anyhow::{Context, Result, bail};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct JlcAssemblyImportOptions {
    pub bom: PathBuf,
    pub placement: PathBuf,
    pub output: PathBuf,
    pub name: String,
    pub default_model: String,
}

#[derive(Debug, Clone, Default)]
pub struct JlcAssemblyImportSummary {
    pub components: usize,
    pub bom_rows: usize,
    pub placements: usize,
    pub components_with_bom: usize,
    pub components_with_placement: usize,
}

#[derive(Debug, Clone)]
struct BomEntry {
    row_number: usize,
    designator_group: String,
    quantity: usize,
    comment: Option<String>,
    footprint: Option<String>,
    value: Option<String>,
    manufacturer_part: Option<String>,
    manufacturer: Option<String>,
    supplier_part: Option<String>,
    supplier: Option<String>,
}

#[derive(Debug, Clone)]
struct PlacementEntry {
    designator: String,
    device: Option<String>,
    footprint: Option<String>,
    x_mm: f64,
    y_mm: f64,
    layer: Option<String>,
    rotation_deg: Option<f64>,
    smd: Option<bool>,
    comment: Option<String>,
    name: Option<String>,
    pins: Option<usize>,
}

#[derive(Debug, Serialize)]
struct ProjectYaml {
    project: ProjectMetaYaml,
    libraries: Vec<String>,
    board: BoardYaml,
    scenarios: Vec<ScenarioYaml>,
}

#[derive(Debug, Serialize)]
struct ProjectMetaYaml {
    name: String,
    version: String,
    import_source: String,
}

#[derive(Debug, Serialize)]
struct BoardYaml {
    components: BTreeMap<String, ComponentYaml>,
    nets: BTreeMap<String, NetYaml>,
    layout: LayoutYaml,
}

#[derive(Debug, Serialize)]
struct ComponentYaml {
    model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    part_number: Option<String>,
    pins: BTreeMap<String, String>,
    source: SourceYaml,
}

#[derive(Debug, Serialize)]
struct SourceYaml {
    format: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    bom_row: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    bom_designator_group: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    bom_quantity: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    bom_comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    footprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    manufacturer_part: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    manufacturer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    supplier_part: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    supplier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_device: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_footprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_pins: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    placement_smd: Option<bool>,
}

#[derive(Debug, Serialize)]
struct NetYaml {}

#[derive(Debug, Serialize)]
struct LayoutYaml {
    placements: BTreeMap<String, PlacementYaml>,
}

#[derive(Debug, Serialize)]
struct PlacementYaml {
    x_mm: f64,
    y_mm: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    side: Option<PlacementSideYaml>,
    #[serde(skip_serializing_if = "Option::is_none")]
    rotation_deg: Option<f64>,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
enum PlacementSideYaml {
    Top,
    Bottom,
}

#[derive(Debug, Serialize)]
struct ScenarioYaml {}

pub fn import_jlc_assembly(options: &JlcAssemblyImportOptions) -> Result<JlcAssemblyImportSummary> {
    let bom_rows = parse_bom(&options.bom)?;
    let placements = parse_placements(&options.placement)?;
    let project = build_project(options, &bom_rows, &placements)?;
    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create import output directory {}",
                parent.display()
            )
        })?;
    }
    let mut yaml = serde_yaml_ng::to_string(&project)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI from JLC/EasyEDA BOM and placement assembly evidence. Add schematic connectivity before electrical sign-off.\n",
    );
    fs::write(&options.output, yaml)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    let components_with_bom = bom_rows
        .values()
        .flat_map(|designators| designators.keys())
        .collect::<BTreeSet<_>>()
        .len();
    Ok(JlcAssemblyImportSummary {
        components: project.board.components.len(),
        bom_rows: bom_rows.len(),
        placements: project.board.layout.placements.len(),
        components_with_bom,
        components_with_placement: placements.len(),
    })
}

fn build_project(
    options: &JlcAssemblyImportOptions,
    bom_rows: &BTreeMap<usize, BTreeMap<String, BomEntry>>,
    placements: &BTreeMap<String, PlacementEntry>,
) -> Result<ProjectYaml> {
    let mut designators = BTreeSet::new();
    for entries in bom_rows.values() {
        designators.extend(entries.keys().cloned());
    }
    designators.extend(placements.keys().cloned());
    if designators.is_empty() {
        bail!(
            "JLC/EasyEDA assembly import found no designators in {} or {}.",
            options.bom.display(),
            options.placement.display()
        );
    }

    let bom_by_designator = bom_rows
        .values()
        .flat_map(|entries| entries.iter())
        .map(|(designator, entry)| (designator.as_str(), entry))
        .collect::<BTreeMap<_, _>>();

    let mut components = BTreeMap::new();
    let mut layout_placements = BTreeMap::new();
    for designator in designators {
        let bom = bom_by_designator.get(designator.as_str()).copied();
        let placement = placements.get(&designator);
        components.insert(
            designator.clone(),
            ComponentYaml {
                model: options.default_model.clone(),
                part_number: component_part_number(bom, placement),
                pins: BTreeMap::new(),
                source: source_yaml(bom, placement),
            },
        );
        if let Some(placement) = placement {
            layout_placements.insert(
                designator,
                PlacementYaml {
                    x_mm: placement.x_mm,
                    y_mm: placement.y_mm,
                    side: placement_side(placement.layer.as_deref()),
                    rotation_deg: placement.rotation_deg,
                },
            );
        }
    }

    Ok(ProjectYaml {
        project: ProjectMetaYaml {
            name: options.name.clone(),
            version: "0.1.0".to_string(),
            import_source: "jlc_assembly".to_string(),
        },
        libraries: vec![generic_library_path()],
        board: BoardYaml {
            components,
            nets: BTreeMap::new(),
            layout: LayoutYaml {
                placements: layout_placements,
            },
        },
        scenarios: Vec::new(),
    })
}

fn component_part_number(
    bom: Option<&BomEntry>,
    placement: Option<&PlacementEntry>,
) -> Option<String> {
    bom.and_then(|entry| entry.manufacturer_part.clone())
        .or_else(|| placement.and_then(|entry| entry.device.clone()))
        .or_else(|| bom.and_then(|entry| entry.supplier_part.clone()))
}

fn source_yaml(bom: Option<&BomEntry>, placement: Option<&PlacementEntry>) -> SourceYaml {
    SourceYaml {
        format: "jlc_assembly".to_string(),
        bom_row: bom.map(|entry| entry.row_number),
        bom_designator_group: bom.map(|entry| entry.designator_group.clone()),
        bom_quantity: bom.map(|entry| entry.quantity),
        bom_comment: bom.and_then(|entry| entry.comment.clone()),
        value: bom
            .and_then(|entry| entry.value.clone())
            .or_else(|| placement.and_then(|entry| entry.comment.clone())),
        footprint: bom
            .and_then(|entry| entry.footprint.clone())
            .or_else(|| placement.and_then(|entry| entry.footprint.clone())),
        manufacturer_part: bom.and_then(|entry| entry.manufacturer_part.clone()),
        manufacturer: bom.and_then(|entry| entry.manufacturer.clone()),
        supplier_part: bom.and_then(|entry| entry.supplier_part.clone()),
        supplier: bom.and_then(|entry| entry.supplier.clone()),
        placement_device: placement.and_then(|entry| entry.device.clone()),
        placement_footprint: placement.and_then(|entry| entry.footprint.clone()),
        placement_comment: placement.and_then(|entry| entry.comment.clone()),
        placement_name: placement.and_then(|entry| entry.name.clone()),
        placement_pins: placement.and_then(|entry| entry.pins),
        placement_smd: placement.and_then(|entry| entry.smd),
    }
}

fn parse_bom(path: &Path) -> Result<BTreeMap<usize, BTreeMap<String, BomEntry>>> {
    let table = read_csv_table(path)?;
    let (headers, rows) = table
        .split_first()
        .with_context(|| format!("JLC/EasyEDA BOM {} is empty.", path.display()))?;
    let columns = HeaderMap::new(headers);
    let designator_column = columns.required("Designator", path)?;
    let mut parsed = BTreeMap::new();
    for (row_index, row) in rows.iter().enumerate() {
        if row.iter().all(|cell| cell.trim().is_empty()) {
            continue;
        }
        let row_number = row_index + 2;
        let designator_group = cell(row, designator_column).to_string();
        let designators = parse_designator_list(&designator_group);
        if designators.is_empty() {
            bail!(
                "JLC/EasyEDA BOM {} row {} has no designators.",
                path.display(),
                row_number
            );
        }
        let quantity = optional_usize(row, columns.optional("Quantity"), path, row_number)?
            .unwrap_or(designators.len());
        if quantity != designators.len() {
            bail!(
                "JLC/EasyEDA BOM {} row {} quantity {} does not match {} designators.",
                path.display(),
                row_number,
                quantity,
                designators.len()
            );
        }
        let entry = BomEntry {
            row_number,
            designator_group: designator_group.clone(),
            quantity,
            comment: optional_string(row, columns.optional("Comment")),
            footprint: optional_string(row, columns.optional("Footprint")),
            value: optional_string(row, columns.optional("Value")),
            manufacturer_part: optional_string(row, columns.optional("Manufacturer Part")),
            manufacturer: optional_string(row, columns.optional("Manufacturer")),
            supplier_part: optional_string(row, columns.optional("Supplier Part")),
            supplier: optional_string(row, columns.optional("Supplier")),
        };
        let entries = parsed.entry(row_number).or_insert_with(BTreeMap::new);
        for designator in designators {
            if entries.insert(designator.clone(), entry.clone()).is_some() {
                bail!(
                    "JLC/EasyEDA BOM {} row {} repeats designator {}.",
                    path.display(),
                    row_number,
                    designator
                );
            }
        }
    }
    let mut seen = BTreeSet::new();
    for entries in parsed.values() {
        for designator in entries.keys() {
            if !seen.insert(designator.clone()) {
                bail!(
                    "JLC/EasyEDA BOM {} contains duplicate designator {} across rows.",
                    path.display(),
                    designator
                );
            }
        }
    }
    Ok(parsed)
}

fn parse_placements(path: &Path) -> Result<BTreeMap<String, PlacementEntry>> {
    let table = read_csv_table(path)?;
    let (headers, rows) = table
        .split_first()
        .with_context(|| format!("JLC/EasyEDA placement CSV {} is empty.", path.display()))?;
    let columns = HeaderMap::new(headers);
    let designator_column = columns.required("Designator", path)?;
    let x_column = columns.required("Mid X", path)?;
    let y_column = columns.required("Mid Y", path)?;
    let mut placements = BTreeMap::new();
    for (row_index, row) in rows.iter().enumerate() {
        if row.iter().all(|cell| cell.trim().is_empty()) {
            continue;
        }
        let row_number = row_index + 2;
        let designator = cell(row, designator_column).trim();
        if designator.is_empty() {
            bail!(
                "JLC/EasyEDA placement CSV {} row {} has empty designator.",
                path.display(),
                row_number
            );
        }
        let entry = PlacementEntry {
            designator: designator.to_string(),
            device: optional_string(row, columns.optional("Device")),
            footprint: optional_string(row, columns.optional("Footprint")),
            x_mm: required_mm(row, x_column, path, row_number, "Mid X")?,
            y_mm: required_mm(row, y_column, path, row_number, "Mid Y")?,
            layer: optional_string(row, columns.optional("Layer")),
            rotation_deg: optional_f64(row, columns.optional("Rotation"), path, row_number)?,
            smd: optional_bool(row, columns.optional("SMD"), path, row_number)?,
            comment: optional_string(row, columns.optional("Comment")),
            name: optional_string(row, columns.optional("Name")),
            pins: optional_usize(row, columns.optional("Pins"), path, row_number)?,
        };
        if placements.insert(entry.designator.clone(), entry).is_some() {
            bail!(
                "JLC/EasyEDA placement CSV {} contains duplicate designator {}.",
                path.display(),
                designator
            );
        }
    }
    Ok(placements)
}

fn read_csv_table(path: &Path) -> Result<Vec<Vec<String>>> {
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read JLC/EasyEDA CSV {}", path.display()))?;
    parse_csv(&text).with_context(|| format!("Failed to parse CSV {}", path.display()))
}

fn parse_csv(input: &str) -> Result<Vec<Vec<String>>> {
    let mut rows = Vec::new();
    let mut row = Vec::new();
    let mut cell = String::new();
    let mut chars = input.chars().peekable();
    let mut in_quotes = false;
    while let Some(character) = chars.next() {
        match character {
            '"' if in_quotes && chars.peek() == Some(&'"') => {
                cell.push('"');
                chars.next();
            }
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => {
                row.push(std::mem::take(&mut cell));
            }
            '\n' if !in_quotes => {
                row.push(trim_cr(std::mem::take(&mut cell)));
                rows.push(std::mem::take(&mut row));
            }
            character => cell.push(character),
        }
    }
    if in_quotes {
        bail!("CSV has an unterminated quoted field.");
    }
    if !cell.is_empty() || !row.is_empty() {
        row.push(trim_cr(cell));
        rows.push(row);
    }
    Ok(rows)
}

fn trim_cr(mut value: String) -> String {
    if value.ends_with('\r') {
        value.pop();
    }
    value
}

struct HeaderMap {
    columns: BTreeMap<String, usize>,
}

impl HeaderMap {
    fn new(headers: &[String]) -> Self {
        let columns = headers
            .iter()
            .enumerate()
            .map(|(index, header)| (normalize_header(header), index))
            .collect();
        Self { columns }
    }

    fn required(&self, name: &str, path: &Path) -> Result<usize> {
        self.optional(name).with_context(|| {
            format!(
                "JLC/EasyEDA CSV {} is missing required column {name}.",
                path.display()
            )
        })
    }

    fn optional(&self, name: &str) -> Option<usize> {
        self.columns.get(&normalize_header(name)).copied()
    }
}

fn normalize_header(value: &str) -> String {
    value
        .chars()
        .filter(|character| character.is_ascii_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

fn cell(row: &[String], index: usize) -> &str {
    row.get(index).map(String::as_str).unwrap_or("").trim()
}

fn optional_string(row: &[String], index: Option<usize>) -> Option<String> {
    index
        .map(|index| cell(row, index))
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

fn optional_bool(
    row: &[String],
    index: Option<usize>,
    path: &Path,
    row_number: usize,
) -> Result<Option<bool>> {
    let Some(index) = index else {
        return Ok(None);
    };
    let value = cell(row, index);
    if value.is_empty() {
        return Ok(None);
    }
    match value.to_ascii_lowercase().as_str() {
        "yes" | "true" | "1" => Ok(Some(true)),
        "no" | "false" | "0" => Ok(Some(false)),
        _ => bail!(
            "JLC/EasyEDA CSV {} row {} has invalid boolean value {}.",
            path.display(),
            row_number,
            value
        ),
    }
}

fn optional_usize(
    row: &[String],
    index: Option<usize>,
    path: &Path,
    row_number: usize,
) -> Result<Option<usize>> {
    let Some(index) = index else {
        return Ok(None);
    };
    let value = cell(row, index);
    if value.is_empty() {
        return Ok(None);
    }
    let parsed = value.parse::<usize>().with_context(|| {
        format!(
            "JLC/EasyEDA CSV {} row {} has invalid integer {}.",
            path.display(),
            row_number,
            value
        )
    })?;
    Ok(Some(parsed))
}

fn optional_f64(
    row: &[String],
    index: Option<usize>,
    path: &Path,
    row_number: usize,
) -> Result<Option<f64>> {
    let Some(index) = index else {
        return Ok(None);
    };
    let value = cell(row, index);
    if value.is_empty() {
        return Ok(None);
    }
    let parsed = value.parse::<f64>().with_context(|| {
        format!(
            "JLC/EasyEDA CSV {} row {} has invalid number {}.",
            path.display(),
            row_number,
            value
        )
    })?;
    if !parsed.is_finite() {
        bail!(
            "JLC/EasyEDA CSV {} row {} has non-finite number {}.",
            path.display(),
            row_number,
            value
        );
    }
    Ok(Some(parsed))
}

fn required_mm(
    row: &[String],
    index: usize,
    path: &Path,
    row_number: usize,
    column: &str,
) -> Result<f64> {
    let raw = cell(row, index);
    if raw.is_empty() {
        bail!(
            "JLC/EasyEDA placement CSV {} row {} has empty {}.",
            path.display(),
            row_number,
            column
        );
    }
    let value = raw.strip_suffix("mm").unwrap_or(raw).trim();
    let parsed = value.parse::<f64>().with_context(|| {
        format!(
            "JLC/EasyEDA placement CSV {} row {} has invalid {} value {}.",
            path.display(),
            row_number,
            column,
            raw
        )
    })?;
    if !parsed.is_finite() {
        bail!(
            "JLC/EasyEDA placement CSV {} row {} has non-finite {} value {}.",
            path.display(),
            row_number,
            column,
            raw
        );
    }
    Ok(parsed)
}

fn parse_designator_list(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(str::to_string)
        .collect()
}

fn placement_side(layer: Option<&str>) -> Option<PlacementSideYaml> {
    match layer.map(str::trim).map(str::to_ascii_lowercase).as_deref() {
        Some("t" | "top" | "f" | "front") => Some(PlacementSideYaml::Top),
        Some("b" | "bottom" | "back") => Some(PlacementSideYaml::Bottom),
        _ => None,
    }
}

fn generic_library_path() -> String {
    fs::canonicalize("libs/generic")
        .unwrap_or_else(|_| PathBuf::from("libs/generic"))
        .to_string_lossy()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::{parse_csv, parse_designator_list};

    #[test]
    fn csv_parser_handles_quoted_designator_lists() {
        let rows = parse_csv("A,\"B,C\",D\n1,\"R1,R2\",3\n").unwrap();
        assert_eq!(rows[1][1], "R1,R2");
    }

    #[test]
    fn designator_list_trims_empty_entries() {
        assert_eq!(parse_designator_list("R1, R2,,C1"), ["R1", "R2", "C1"]);
    }
}
