use super::kicad_sch::sexp::{
    as_list, child_list, list_children, numeric_at, parse_sexp_document, string_at, tag,
};
use anyhow::{Context, Result, bail};
use serde::Serialize;
use serde_yaml_ng::{Mapping, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, Path, PathBuf};

#[derive(Debug)]
pub struct KicadPcbPlacementImportOptions {
    pub input: PathBuf,
    pub project: PathBuf,
    pub output: PathBuf,
}

#[derive(Debug, Clone)]
struct PcbPlacement {
    x_mm: f64,
    y_mm: f64,
    side: Option<PcbPlacementSide>,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
enum PcbPlacementSide {
    Top,
    Bottom,
}

#[derive(Debug, Serialize)]
struct PlacementYaml {
    x_mm: f64,
    y_mm: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    side: Option<PcbPlacementSide>,
}

pub fn import_kicad_pcb_placements(options: &KicadPcbPlacementImportOptions) -> Result<usize> {
    let placements = parse_kicad_pcb_placements(&options.input)?;
    let text = fs::read_to_string(&options.project).with_context(|| {
        format!(
            "Failed to read Board IR project {}",
            options.project.display()
        )
    })?;
    let mut project_yaml: Value = serde_yaml_ng::from_str(&text).with_context(|| {
        format!(
            "Failed to parse Board IR project YAML {}",
            options.project.display()
        )
    })?;
    let imported_count = merge_placements_into_project(&mut project_yaml, &placements)?;
    if imported_count == 0 {
        bail!(
            "KiCad PCB {} has no footprint references matching Board IR project components in {}.",
            options.input.display(),
            options.project.display()
        );
    }
    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create import output directory {}",
                parent.display()
            )
        })?;
    }
    absolutize_relative_libraries(
        &mut project_yaml,
        options.project.parent().unwrap_or_else(|| Path::new(".")),
    )?;
    let mut yaml = serde_yaml_ng::to_string(&project_yaml)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI by adding KiCad PCB component placements to Board IR.\n",
    );
    fs::write(&options.output, yaml)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    Ok(imported_count)
}

fn parse_kicad_pcb_placements(path: &PathBuf) -> Result<BTreeMap<String, PcbPlacement>> {
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read KiCad PCB {}", path.display()))?;
    let root = parse_sexp_document(&text)?;
    let root_list = as_list(&root).context("KiCad PCB must be an S-expression list.")?;
    if tag(root_list) != Some("kicad_pcb") {
        bail!("KiCad PCB {} root token is not kicad_pcb.", path.display());
    }
    let mut placements = BTreeMap::new();
    for footprint in list_children(root_list, "footprint") {
        let reference = footprint_reference(footprint)
            .with_context(|| "KiCad PCB footprint is missing Reference property or fp_text.")?;
        if placements.contains_key(&reference) {
            bail!("KiCad PCB contains duplicate footprint reference {reference}.");
        }
        let at = child_list(footprint, "at")
            .with_context(|| format!("KiCad PCB footprint {reference} is missing (at x y)."))?;
        let x_mm = numeric_at(at, 1)
            .with_context(|| format!("KiCad PCB footprint {reference} has invalid x placement."))?;
        let y_mm = numeric_at(at, 2)
            .with_context(|| format!("KiCad PCB footprint {reference} has invalid y placement."))?;
        let side = footprint_side(footprint);
        placements.insert(reference, PcbPlacement { x_mm, y_mm, side });
    }
    if placements.is_empty() {
        bail!("KiCad PCB {} contains no footprints.", path.display());
    }
    Ok(placements)
}

fn footprint_reference(footprint: &[super::kicad_sch::sexp::Sexp]) -> Option<String> {
    for property in list_children(footprint, "property") {
        if string_at(property, 1) == Some("Reference") {
            let reference = string_at(property, 2)?.trim();
            if !reference.is_empty() {
                return Some(reference.to_string());
            }
        }
    }
    for fp_text in list_children(footprint, "fp_text") {
        if string_at(fp_text, 1) == Some("reference") {
            let reference = string_at(fp_text, 2)?.trim();
            if !reference.is_empty() {
                return Some(reference.to_string());
            }
        }
    }
    None
}

fn footprint_side(footprint: &[super::kicad_sch::sexp::Sexp]) -> Option<PcbPlacementSide> {
    let layer = child_list(footprint, "layer").and_then(|layer| string_at(layer, 1))?;
    if layer.starts_with("F.") {
        Some(PcbPlacementSide::Top)
    } else if layer.starts_with("B.") {
        Some(PcbPlacementSide::Bottom)
    } else {
        None
    }
}

fn merge_placements_into_project(
    project_yaml: &mut Value,
    placements: &BTreeMap<String, PcbPlacement>,
) -> Result<usize> {
    let board = mapping_field_mut(project_yaml, "board")?;
    let component_refs = mapping_field(board, "components")?
        .keys()
        .filter_map(Value::as_str)
        .map(str::to_string)
        .collect::<BTreeSet<_>>();
    if component_refs.is_empty() {
        bail!("Board IR project has no board.components entries.");
    }
    let layout = ensure_mapping_field_mut(board, "layout")?;
    let placement_yaml = ensure_mapping_field_mut(layout, "placements")?;
    let mut imported_count = 0;
    for (reference, placement) in placements {
        if !component_refs.contains(reference) {
            continue;
        }
        placement_yaml.insert(
            Value::String(reference.clone()),
            serde_yaml_ng::to_value(PlacementYaml {
                x_mm: placement.x_mm,
                y_mm: placement.y_mm,
                side: placement.side,
            })?,
        );
        imported_count += 1;
    }
    Ok(imported_count)
}

fn absolutize_relative_libraries(project_yaml: &mut Value, project_dir: &Path) -> Result<()> {
    let mapping = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    let Some(libraries) = mapping.get_mut(Value::String("libraries".to_string())) else {
        return Ok(());
    };
    let libraries = libraries
        .as_sequence_mut()
        .context("Board IR field libraries must be a list.")?;
    for library in libraries {
        let Some(path_text) = library.as_str() else {
            bail!("Board IR libraries entries must be strings.");
        };
        let path = Path::new(path_text);
        if path.is_absolute() {
            continue;
        }
        let resolved = normalize_path(&project_dir.join(path));
        let absolute = fs::canonicalize(&resolved).unwrap_or(resolved);
        *library = Value::String(absolute.to_string_lossy().to_string());
    }
    Ok(())
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    normalized
}

fn mapping_field_mut<'a>(value: &'a mut Value, key: &str) -> Result<&'a mut Mapping> {
    let mapping = value
        .as_mapping_mut()
        .with_context(|| format!("Expected YAML object while reading {key}."))?;
    mapping
        .get_mut(Value::String(key.to_string()))
        .with_context(|| format!("Board IR project is missing {key}."))?
        .as_mapping_mut()
        .with_context(|| format!("Board IR field {key} must be an object."))
}

fn mapping_field<'a>(mapping: &'a Mapping, key: &str) -> Result<&'a Mapping> {
    mapping
        .get(Value::String(key.to_string()))
        .with_context(|| format!("Board IR project is missing board.{key}."))?
        .as_mapping()
        .with_context(|| format!("Board IR field board.{key} must be an object."))
}

fn ensure_mapping_field_mut<'a>(mapping: &'a mut Mapping, key: &str) -> Result<&'a mut Mapping> {
    let key_value = Value::String(key.to_string());
    if !mapping.contains_key(&key_value) {
        mapping.insert(key_value.clone(), Value::Mapping(Mapping::new()));
    }
    mapping
        .get_mut(&key_value)
        .expect("field was inserted when absent")
        .as_mapping_mut()
        .with_context(|| format!("Board IR field {key} must be an object."))
}
