use super::kicad::{
    KicadImportOptions, ParsedComponent, ParsedKicadNetlist, ParsedNet, ParsedNode,
    import_parsed_kicad,
};
use anyhow::{Context, Result, bail};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone)]
enum Sexp {
    Atom(String),
    Str(String),
    List(Vec<Sexp>),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    x: i64,
    y: i64,
}

#[derive(Debug)]
struct PinGeometry {
    at: Point,
}

#[derive(Debug)]
struct SymbolInstance {
    refdes: String,
    value: Option<String>,
    lib: Option<String>,
    part: Option<String>,
    fields: BTreeMap<String, String>,
    at: Point,
    lib_id: String,
    pins: BTreeMap<String, Point>,
    is_power_symbol: bool,
}

#[derive(Debug, Clone)]
struct Segment {
    a: Point,
    b: Point,
}

#[derive(Debug)]
struct UnionFind {
    parent: Vec<usize>,
}

pub fn import_kicad_schematic(options: &KicadImportOptions) -> Result<()> {
    let parsed = parse_kicad_schematic(&options.input)?;
    import_parsed_kicad(
        options,
        &parsed,
        "kicad_schematic",
        "# Generated by CircuitCI from a native KiCad schematic. Add scenarios before sign-off.\n",
    )
}

pub(super) fn parse_kicad_schematic(path: &Path) -> Result<ParsedKicadNetlist> {
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read KiCad schematic {}", path.display()))?;
    let root = parse_sexp_document(&text)?;
    let root_list = as_list(&root).context("KiCad schematic must be an S-expression list.")?;
    if tag(root_list) != Some("kicad_sch") {
        bail!(
            "KiCad schematic {} root token is not kicad_sch.",
            path.display()
        );
    }
    reject_unsupported_constructs(root_list)?;
    let lib_pins = parse_lib_symbol_pins(root_list)?;
    let (symbols, power_labels) = parse_symbol_instances(root_list, &lib_pins)?;
    if symbols.is_empty() {
        bail!(
            "KiCad schematic {} contains no importable symbols.",
            path.display()
        );
    }
    let (segments, junctions) = parse_wires_and_junctions(root_list)?;
    let mut labels = parse_labels(root_list);
    labels.extend(power_labels);
    let nets = build_nets(&symbols, &segments, &junctions, &labels)?;

    let mut components = BTreeMap::new();
    for symbol in symbols {
        if components.contains_key(&symbol.refdes) {
            bail!(
                "Duplicate KiCad schematic component reference {}.",
                symbol.refdes
            );
        }
        components.insert(
            symbol.refdes.clone(),
            ParsedComponent {
                refdes: symbol.refdes,
                value: symbol.value,
                lib: symbol.lib,
                part: symbol.part,
                fields: symbol.fields,
            },
        );
    }
    Ok(ParsedKicadNetlist { components, nets })
}

fn reject_unsupported_constructs(root: &[Sexp]) -> Result<()> {
    for item in root.iter().skip(1) {
        let Some(list) = maybe_list(item) else {
            continue;
        };
        match tag(list) {
            Some("sheet") => bail!("Native KiCad schematic import does not support sheets yet."),
            Some("hierarchical_label") => {
                bail!("Native KiCad schematic import does not support hierarchical labels yet.")
            }
            Some("bus") | Some("bus_entry") => {
                bail!("Native KiCad schematic import does not support buses yet.")
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_lib_symbol_pins(root: &[Sexp]) -> Result<BTreeMap<String, BTreeMap<String, PinGeometry>>> {
    let mut pins_by_lib = BTreeMap::new();
    let Some(lib_symbols) = child_list(root, "lib_symbols") else {
        bail!("Native KiCad schematic import requires root lib_symbols pin geometry.");
    };
    for child in list_children(lib_symbols, "symbol") {
        let Some(lib_id) = string_at(child, 1) else {
            continue;
        };
        let mut pins = BTreeMap::new();
        collect_pin_geometry(child, &mut pins)?;
        pins_by_lib.insert(lib_id.to_string(), pins);
    }
    Ok(pins_by_lib)
}

fn collect_pin_geometry(list: &[Sexp], pins: &mut BTreeMap<String, PinGeometry>) -> Result<()> {
    for child in list.iter().skip(1).filter_map(maybe_list) {
        match tag(child) {
            Some("pin") => {
                let number = child_list(child, "number")
                    .and_then(|number| string_at(number, 1))
                    .with_context(|| "KiCad library pin is missing a number.")?
                    .to_string();
                let at = child_list(child, "at")
                    .and_then(parse_at_point)
                    .with_context(|| {
                        format!("KiCad library pin {number} is missing coordinates.")
                    })?;
                pins.insert(number, PinGeometry { at });
            }
            Some("symbol") => collect_pin_geometry(child, pins)?,
            _ => {}
        }
    }
    Ok(())
}

fn parse_symbol_instances(
    root: &[Sexp],
    lib_pins: &BTreeMap<String, BTreeMap<String, PinGeometry>>,
) -> Result<(Vec<SymbolInstance>, BTreeMap<Point, String>)> {
    let mut symbols = Vec::new();
    let mut power_labels = BTreeMap::new();
    for symbol in list_children(root, "symbol") {
        let lib_id = child_list(symbol, "lib_id")
            .and_then(|list| string_at(list, 1))
            .with_context(|| "KiCad schematic symbol is missing lib_id.")?
            .to_string();
        let at_list = child_list(symbol, "at")
            .with_context(|| format!("KiCad schematic symbol {lib_id} is missing at."))?;
        let at = parse_at_point(at_list)
            .with_context(|| format!("KiCad schematic symbol {lib_id} has invalid at."))?;
        let rotation = numeric_at(at_list, 3).unwrap_or(0.0);
        if !approx_zero(rotation) {
            bail!("Native KiCad schematic import does not support rotated symbol {lib_id}.");
        }
        let properties = parse_properties(symbol);
        let refdes = properties
            .get("Reference")
            .filter(|value| !value.trim().is_empty())
            .with_context(|| format!("KiCad schematic symbol {lib_id} is missing Reference."))?
            .to_string();
        let value = properties.get("Value").cloned();
        let Some(pin_geometry) = lib_pins.get(&lib_id) else {
            bail!(
                "KiCad schematic symbol {refdes} uses {lib_id}, but lib_symbols has no pin geometry for it."
            );
        };
        let mut pins = BTreeMap::new();
        for pin in list_children(symbol, "pin") {
            let number = string_at(pin, 1)
                .with_context(|| {
                    format!("KiCad schematic symbol {refdes} has a pin without a number.")
                })?
                .to_string();
            let Some(geometry) = pin_geometry.get(&number) else {
                bail!(
                    "KiCad schematic symbol {refdes}.{number} has no matching lib_symbols pin geometry."
                );
            };
            pins.insert(
                number,
                Point {
                    x: at.x + geometry.at.x,
                    y: at.y + geometry.at.y,
                },
            );
        }
        if pins.is_empty() {
            bail!("KiCad schematic symbol {refdes} has no instance pins.");
        }
        let (lib, part) = split_lib_id(&lib_id);
        let is_power_symbol = refdes.starts_with("#PWR") || lib.as_deref() == Some("power");
        if is_power_symbol {
            if pins.len() != 1 {
                bail!("KiCad power symbol {refdes} must expose exactly one pin.");
            }
            let label = value.clone().unwrap_or_else(|| refdes.clone());
            power_labels.insert(*pins.values().next().unwrap(), label);
            continue;
        }
        let fields = properties
            .into_iter()
            .filter(|(name, _)| name != "Reference" && name != "Value")
            .collect();
        symbols.push(SymbolInstance {
            refdes,
            value,
            lib,
            part,
            fields,
            at,
            lib_id,
            pins,
            is_power_symbol,
        });
    }
    Ok((symbols, power_labels))
}

fn parse_properties(symbol: &[Sexp]) -> BTreeMap<String, String> {
    let mut properties = BTreeMap::new();
    for property in list_children(symbol, "property") {
        if let (Some(name), Some(value)) = (string_at(property, 1), string_at(property, 2)) {
            properties.insert(name.to_string(), value.to_string());
        }
    }
    properties
}

fn parse_wires_and_junctions(root: &[Sexp]) -> Result<(Vec<Segment>, BTreeSet<Point>)> {
    let mut segments = Vec::new();
    for wire in list_children(root, "wire") {
        let points = child_list(wire, "pts")
            .map(parse_points)
            .transpose()?
            .with_context(|| "KiCad wire is missing pts.")?;
        if points.len() < 2 {
            bail!("KiCad wire must contain at least two points.");
        }
        for pair in points.windows(2) {
            let segment = Segment {
                a: pair[0],
                b: pair[1],
            };
            if !segment.is_axis_aligned() {
                bail!("Native KiCad schematic import supports only horizontal or vertical wires.");
            }
            segments.push(segment);
        }
    }
    let junctions = list_children(root, "junction")
        .filter_map(|junction| child_list(junction, "at"))
        .filter_map(parse_at_point)
        .collect();
    reject_unjunctioned_crossings(&segments, &junctions)?;
    Ok((segments, junctions))
}

fn parse_labels(root: &[Sexp]) -> BTreeMap<Point, String> {
    let mut labels = BTreeMap::new();
    for label_tag in ["label", "global_label"] {
        for label in list_children(root, label_tag) {
            if let (Some(name), Some(at)) = (
                string_at(label, 1),
                child_list(label, "at").and_then(parse_at_point),
            ) {
                labels.insert(at, name.to_string());
            }
        }
    }
    labels
}

fn build_nets(
    symbols: &[SymbolInstance],
    segments: &[Segment],
    junctions: &BTreeSet<Point>,
    labels: &BTreeMap<Point, String>,
) -> Result<Vec<ParsedNet>> {
    let mut points = BTreeSet::new();
    for segment in segments {
        points.insert(segment.a);
        points.insert(segment.b);
    }
    points.extend(junctions.iter().copied());
    points.extend(labels.keys().copied());
    for symbol in symbols {
        points.extend(symbol.pins.values().copied());
    }

    let mut index = BTreeMap::new();
    for point in &points {
        let next = index.len();
        index.insert(*point, next);
    }
    let mut uf = UnionFind::new(index.len());
    for segment in segments {
        let segment_points = points
            .iter()
            .filter(|point| segment.contains(**point))
            .copied()
            .collect::<Vec<_>>();
        for pair in segment_points.windows(2) {
            uf.union(index[&pair[0]], index[&pair[1]]);
        }
    }

    for (point, label) in labels {
        if !segments.iter().any(|segment| segment.contains(*point))
            && !symbols
                .iter()
                .any(|symbol| symbol.pins.values().any(|pin| pin == point))
        {
            bail!("KiCad schematic label {label} is not attached to a wire or pin.");
        }
    }

    let mut labels_by_root: BTreeMap<usize, BTreeSet<String>> = BTreeMap::new();
    for (point, label) in labels {
        let root = uf.find(index[point]);
        labels_by_root
            .entry(root)
            .or_default()
            .insert(label.clone());
    }
    for labels in labels_by_root.values() {
        if labels.len() > 1 {
            bail!("KiCad schematic net has conflicting labels {labels:?}.");
        }
    }

    let mut nodes_by_key: BTreeMap<String, Vec<ParsedNode>> = BTreeMap::new();
    let mut label_by_key = BTreeMap::new();
    for symbol in symbols {
        let _ = (&symbol.at, &symbol.lib_id, symbol.is_power_symbol);
        for (pin, point) in &symbol.pins {
            let root = uf.find(index[point]);
            let label = labels_by_root
                .get(&root)
                .and_then(|labels| labels.iter().next().cloned());
            let key = label.clone().unwrap_or_else(|| format!("__root_{root}"));
            if let Some(label) = label {
                label_by_key.insert(key.clone(), label);
            }
            nodes_by_key.entry(key).or_default().push(ParsedNode {
                refdes: symbol.refdes.clone(),
                pin: pin.clone(),
            });
        }
    }

    let mut nets = Vec::new();
    for (index, (key, nodes)) in nodes_by_key.into_iter().enumerate() {
        if nodes.is_empty() {
            continue;
        }
        let name = label_by_key
            .get(&key)
            .cloned()
            .unwrap_or_else(|| format!("net_{}", index + 1));
        nets.push(ParsedNet {
            code: (index + 1).to_string(),
            name,
            nodes,
        });
    }
    if nets.is_empty() {
        bail!("KiCad schematic has no connected component pins.");
    }
    Ok(nets)
}

fn reject_unjunctioned_crossings(segments: &[Segment], junctions: &BTreeSet<Point>) -> Result<()> {
    for (left_index, left) in segments.iter().enumerate() {
        for right in segments.iter().skip(left_index + 1) {
            let Some(point) = left.intersection(right) else {
                continue;
            };
            let endpoint_touch = left.is_endpoint(point) || right.is_endpoint(point);
            if !endpoint_touch && !junctions.contains(&point) {
                bail!("KiCad schematic has crossing wires without an explicit junction.");
            }
        }
    }
    Ok(())
}

impl Segment {
    fn is_axis_aligned(&self) -> bool {
        self.a.x == self.b.x || self.a.y == self.b.y
    }

    fn contains(&self, point: Point) -> bool {
        if self.a.x == self.b.x {
            point.x == self.a.x && between(point.y, self.a.y, self.b.y)
        } else if self.a.y == self.b.y {
            point.y == self.a.y && between(point.x, self.a.x, self.b.x)
        } else {
            false
        }
    }

    fn is_endpoint(&self, point: Point) -> bool {
        self.a == point || self.b == point
    }

    fn intersection(&self, other: &Segment) -> Option<Point> {
        if self.a.x == self.b.x && other.a.y == other.b.y {
            let point = Point {
                x: self.a.x,
                y: other.a.y,
            };
            (self.contains(point) && other.contains(point)).then_some(point)
        } else if self.a.y == self.b.y && other.a.x == other.b.x {
            let point = Point {
                x: other.a.x,
                y: self.a.y,
            };
            (self.contains(point) && other.contains(point)).then_some(point)
        } else {
            None
        }
    }
}

impl UnionFind {
    fn new(size: usize) -> Self {
        Self {
            parent: (0..size).collect(),
        }
    }

    fn find(&mut self, item: usize) -> usize {
        if self.parent[item] != item {
            self.parent[item] = self.find(self.parent[item]);
        }
        self.parent[item]
    }

    fn union(&mut self, a: usize, b: usize) {
        let root_a = self.find(a);
        let root_b = self.find(b);
        if root_a != root_b {
            self.parent[root_b] = root_a;
        }
    }
}

fn parse_points(list: &[Sexp]) -> Result<Vec<Point>> {
    list_children(list, "xy")
        .map(|xy| {
            let x = numeric_at(xy, 1).with_context(|| "KiCad xy point is missing x.")?;
            let y = numeric_at(xy, 2).with_context(|| "KiCad xy point is missing y.")?;
            Ok(Point {
                x: quantize_coord(x),
                y: quantize_coord(y),
            })
        })
        .collect()
}

fn parse_at_point(list: &[Sexp]) -> Option<Point> {
    Some(Point {
        x: quantize_coord(numeric_at(list, 1)?),
        y: quantize_coord(numeric_at(list, 2)?),
    })
}

fn parse_sexp_document(text: &str) -> Result<Sexp> {
    let mut parser = Parser { text, offset: 0 };
    parser.skip_ws_and_comments();
    let sexp = parser.parse_one()?;
    parser.skip_ws_and_comments();
    if parser.offset != parser.text.len() {
        bail!("Unexpected trailing data in KiCad S-expression.");
    }
    Ok(sexp)
}

struct Parser<'a> {
    text: &'a str,
    offset: usize,
}

impl Parser<'_> {
    fn parse_one(&mut self) -> Result<Sexp> {
        self.skip_ws_and_comments();
        match self.peek_char() {
            Some('(') => self.parse_list(),
            Some('"') => self.parse_string().map(Sexp::Str),
            Some(_) => self.parse_atom().map(Sexp::Atom),
            None => bail!("Unexpected end of KiCad S-expression."),
        }
    }

    fn parse_list(&mut self) -> Result<Sexp> {
        self.expect_char('(')?;
        let mut items = Vec::new();
        loop {
            self.skip_ws_and_comments();
            match self.peek_char() {
                Some(')') => {
                    self.expect_char(')')?;
                    break;
                }
                Some(_) => items.push(self.parse_one()?),
                None => bail!("Unclosed KiCad S-expression list."),
            }
        }
        Ok(Sexp::List(items))
    }

    fn parse_string(&mut self) -> Result<String> {
        self.expect_char('"')?;
        let mut output = String::new();
        loop {
            let Some(character) = self.next_char() else {
                bail!("Unclosed KiCad S-expression string.");
            };
            match character {
                '"' => break,
                '\\' => {
                    let Some(escaped) = self.next_char() else {
                        bail!("Unclosed KiCad S-expression escape.");
                    };
                    output.push(escaped);
                }
                _ => output.push(character),
            }
        }
        Ok(output)
    }

    fn parse_atom(&mut self) -> Result<String> {
        let start = self.offset;
        while let Some(character) = self.peek_char() {
            if character.is_whitespace() || character == '(' || character == ')' {
                break;
            }
            self.next_char();
        }
        if self.offset == start {
            bail!("Expected KiCad S-expression atom.");
        }
        Ok(self.text[start..self.offset].to_string())
    }

    fn skip_ws_and_comments(&mut self) {
        loop {
            while self.peek_char().is_some_and(char::is_whitespace) {
                self.next_char();
            }
            if self.peek_char() == Some(';') {
                while let Some(character) = self.next_char() {
                    if character == '\n' {
                        break;
                    }
                }
            } else {
                break;
            }
        }
    }

    fn expect_char(&mut self, expected: char) -> Result<()> {
        match self.next_char() {
            Some(actual) if actual == expected => Ok(()),
            Some(actual) => bail!("Expected {expected:?}, got {actual:?}."),
            None => bail!("Expected {expected:?}, got end of input."),
        }
    }

    fn peek_char(&self) -> Option<char> {
        self.text[self.offset..].chars().next()
    }

    fn next_char(&mut self) -> Option<char> {
        let character = self.peek_char()?;
        self.offset += character.len_utf8();
        Some(character)
    }
}

fn as_list(sexp: &Sexp) -> Option<&[Sexp]> {
    maybe_list(sexp)
}

fn maybe_list(sexp: &Sexp) -> Option<&[Sexp]> {
    match sexp {
        Sexp::List(items) => Some(items),
        _ => None,
    }
}

fn tag(list: &[Sexp]) -> Option<&str> {
    string_at(list, 0)
}

fn string_at(list: &[Sexp], index: usize) -> Option<&str> {
    match list.get(index)? {
        Sexp::Atom(value) | Sexp::Str(value) => Some(value),
        Sexp::List(_) => None,
    }
}

fn numeric_at(list: &[Sexp], index: usize) -> Option<f64> {
    string_at(list, index)?.parse().ok()
}

fn child_list<'a>(list: &'a [Sexp], name: &'a str) -> Option<&'a [Sexp]> {
    list_children(list, name).next()
}

fn list_children<'a>(list: &'a [Sexp], name: &'a str) -> impl Iterator<Item = &'a [Sexp]> {
    list.iter().skip(1).filter_map(move |item| {
        let child = maybe_list(item)?;
        (tag(child) == Some(name)).then_some(child)
    })
}

fn split_lib_id(lib_id: &str) -> (Option<String>, Option<String>) {
    lib_id
        .split_once(':')
        .map(|(lib, part)| (Some(lib.to_string()), Some(part.to_string())))
        .unwrap_or((None, Some(lib_id.to_string())))
}

fn quantize_coord(value: f64) -> i64 {
    (value * 1_000_000.0).round() as i64
}

fn between(value: i64, a: i64, b: i64) -> bool {
    value >= a.min(b) && value <= a.max(b)
}

fn approx_zero(value: f64) -> bool {
    value.abs() < 1e-9
}

#[cfg(test)]
mod tests {
    use super::parse_kicad_schematic;

    #[test]
    fn parses_single_sheet_schematic_connectivity() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("basic.kicad_sch");
        std::fs::write(
            &path,
            r#"
(kicad_sch
  (lib_symbols
    (symbol "Device:R"
      (pin passive line (at -2.54 0 0) (length 2.54) (number "1"))
      (pin passive line (at 2.54 0 180) (length 2.54) (number "2"))))
  (symbol (lib_id "Device:R") (at 10 10 0)
    (property "Reference" "R1") (property "Value" "10k")
    (pin "1") (pin "2"))
  (wire (pts (xy 7.46 10) (xy 7.46 12)))
  (label "NET_A" (at 7.46 12 0)))
"#,
        )
        .unwrap();
        let parsed = parse_kicad_schematic(&path).unwrap();
        assert_eq!(parsed.components.len(), 1);
        assert_eq!(parsed.nets.len(), 2);
        assert!(parsed.nets.iter().any(|net| net.name == "NET_A"));
    }
}
