use anyhow::{Context, Result, bail};
use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct KicadImportOptions {
    pub input: PathBuf,
    pub output: PathBuf,
    pub name: String,
    pub default_model: String,
}

#[derive(Debug)]
struct ParsedKicadNetlist {
    components: BTreeMap<String, ParsedComponent>,
    nets: Vec<ParsedNet>,
}

#[derive(Debug)]
struct ParsedComponent {
    refdes: String,
    value: Option<String>,
    lib: Option<String>,
    part: Option<String>,
    fields: BTreeMap<String, String>,
}

#[derive(Debug)]
struct ParsedNet {
    code: String,
    name: String,
    nodes: Vec<ParsedNode>,
}

#[derive(Debug)]
struct ParsedNode {
    refdes: String,
    pin: String,
}

#[derive(Debug)]
enum TextTarget {
    Value,
    Field(String),
}

#[derive(Debug, Serialize)]
struct ProjectYaml {
    project: ProjectMetaYaml,
    libraries: Vec<String>,
    board: BoardYaml,
    scenarios: Vec<ScenarioYaml>,
}

#[derive(Debug, Serialize)]
struct ProjectMetaYaml {
    name: String,
    version: String,
    import_source: String,
}

#[derive(Debug, Serialize)]
struct BoardYaml {
    components: BTreeMap<String, ComponentYaml>,
    nets: BTreeMap<String, NetYaml>,
}

#[derive(Debug, Serialize)]
struct ComponentYaml {
    model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    part_number: Option<String>,
    pins: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    source: Option<ComponentSourceYaml>,
}

#[derive(Debug, Serialize)]
struct ComponentSourceYaml {
    format: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    lib: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    part: Option<String>,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    fields: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
struct NetYaml {
    kind: String,
}

#[derive(Debug, Serialize)]
struct ScenarioYaml {}

pub fn import_kicad_netlist(options: &KicadImportOptions) -> Result<()> {
    let parsed = parse_kicad_netlist(&options.input)?;
    let output_dir = options.output.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(output_dir).with_context(|| {
        format!(
            "Failed to create import output directory {}",
            output_dir.display()
        )
    })?;
    let project = build_project_yaml(options, &parsed)?;
    let mut yaml = serde_yaml_ng::to_string(&project)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI from a KiCad generic XML netlist. Add scenarios before sign-off.\n",
    );
    fs::write(&options.output, yaml)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    Ok(())
}

fn parse_kicad_netlist(path: &Path) -> Result<ParsedKicadNetlist> {
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read KiCad netlist {}", path.display()))?;
    let mut reader = Reader::from_str(&text);
    reader.config_mut().trim_text(true);
    let mut stack: Vec<String> = Vec::new();
    let mut components = BTreeMap::new();
    let mut nets = Vec::new();
    let mut current_component: Option<ParsedComponent> = None;
    let mut current_net: Option<ParsedNet> = None;
    let mut text_target: Option<TextTarget> = None;

    loop {
        match reader.read_event() {
            Ok(Event::Start(event)) => {
                let tag = local_name(event.name().as_ref());
                let parent = stack.last().map(String::as_str);
                match (tag.as_str(), parent) {
                    ("comp", Some("components")) => {
                        let refdes = required_attr(&reader, &event, "ref")?;
                        if components.contains_key(&refdes) {
                            bail!("Duplicate KiCad component reference {refdes}.");
                        }
                        current_component = Some(ParsedComponent {
                            refdes,
                            value: None,
                            lib: None,
                            part: None,
                            fields: BTreeMap::new(),
                        });
                    }
                    ("net", Some("nets")) => {
                        current_net = Some(ParsedNet {
                            code: attr_value(&reader, &event, "code")?.unwrap_or_default(),
                            name: attr_value(&reader, &event, "name")?.unwrap_or_default(),
                            nodes: Vec::new(),
                        });
                    }
                    ("value", Some("comp")) if current_component.is_some() => {
                        text_target = Some(TextTarget::Value);
                    }
                    ("field", Some("fields")) if current_component.is_some() => {
                        text_target =
                            Some(TextTarget::Field(required_attr(&reader, &event, "name")?));
                    }
                    ("libsource", Some("comp")) if current_component.is_some() => {
                        apply_libsource(&reader, &event, current_component.as_mut().unwrap())?;
                    }
                    ("node", Some("net")) if current_net.is_some() => {
                        push_node(&reader, &event, current_net.as_mut().unwrap())?;
                    }
                    _ => {}
                }
                stack.push(tag);
            }
            Ok(Event::Empty(event)) => {
                let tag = local_name(event.name().as_ref());
                let parent = stack.last().map(String::as_str);
                match (tag.as_str(), parent) {
                    ("libsource", Some("comp")) if current_component.is_some() => {
                        apply_libsource(&reader, &event, current_component.as_mut().unwrap())?;
                    }
                    ("node", Some("net")) if current_net.is_some() => {
                        push_node(&reader, &event, current_net.as_mut().unwrap())?;
                    }
                    ("field", Some("fields")) if current_component.is_some() => {
                        let name = required_attr(&reader, &event, "name")?;
                        current_component
                            .as_mut()
                            .unwrap()
                            .fields
                            .insert(name, String::new());
                    }
                    _ => {}
                }
            }
            Ok(Event::Text(event)) => {
                if let (Some(component), Some(target)) =
                    (current_component.as_mut(), text_target.as_ref())
                {
                    let value = event
                        .xml_content()
                        .context("Failed to decode KiCad XML text")?
                        .trim()
                        .to_string();
                    match target {
                        TextTarget::Value => component.value = non_empty(value),
                        TextTarget::Field(name) => {
                            component.fields.insert(name.clone(), value);
                        }
                    }
                }
            }
            Ok(Event::End(event)) => {
                let tag = local_name(event.name().as_ref());
                match tag.as_str() {
                    "value" | "field" => text_target = None,
                    "comp" => {
                        let Some(component) = current_component.take() else {
                            bail!("KiCad XML closed a component without opening one.");
                        };
                        components.insert(component.refdes.clone(), component);
                    }
                    "net" => {
                        let Some(net) = current_net.take() else {
                            bail!("KiCad XML closed a net without opening one.");
                        };
                        nets.push(net);
                    }
                    _ => {}
                }
                let popped = stack.pop();
                if popped.as_deref() != Some(tag.as_str()) {
                    bail!("Malformed KiCad XML nesting near closing tag {tag}.");
                }
            }
            Ok(Event::Eof) => break,
            Err(error) => bail!("Failed to parse KiCad XML netlist: {error}"),
            _ => {}
        }
    }

    if components.is_empty() {
        bail!("KiCad netlist {} contains no components.", path.display());
    }
    if current_component.is_some() || current_net.is_some() || !stack.is_empty() {
        bail!(
            "KiCad netlist {} ended with unclosed XML tags.",
            path.display()
        );
    }
    Ok(ParsedKicadNetlist { components, nets })
}

fn build_project_yaml(
    options: &KicadImportOptions,
    parsed: &ParsedKicadNetlist,
) -> Result<ProjectYaml> {
    let net_names = unique_net_names(&parsed.nets);
    let mut components = parsed
        .components
        .iter()
        .map(|(refdes, component)| {
            (
                refdes.clone(),
                ComponentYaml {
                    model: model_for_component(component, &options.default_model),
                    part_number: component.value.clone(),
                    pins: BTreeMap::new(),
                    source: Some(ComponentSourceYaml {
                        format: "kicad_xml_netlist".to_string(),
                        value: component.value.clone(),
                        lib: component.lib.clone(),
                        part: component.part.clone(),
                        fields: component.fields.clone(),
                    }),
                },
            )
        })
        .collect::<BTreeMap<_, _>>();
    let mut assigned_pins = BTreeSet::new();
    for (net_index, net) in parsed.nets.iter().enumerate() {
        let net_name = net_names[net_index].clone();
        for node in &net.nodes {
            let Some(component) = components.get_mut(&node.refdes) else {
                bail!(
                    "KiCad net {} references unknown component {}.",
                    net.name,
                    node.refdes
                );
            };
            let key = format!("{}.{}", node.refdes, node.pin);
            if !assigned_pins.insert(key.clone()) {
                bail!("KiCad component pin {key} appears on more than one net.");
            }
            component.pins.insert(node.pin.clone(), net_name.clone());
        }
    }
    let nets = parsed
        .nets
        .iter()
        .enumerate()
        .map(|(index, net)| {
            (
                net_names[index].clone(),
                NetYaml {
                    kind: classify_net(&net.name).to_string(),
                },
            )
        })
        .collect();
    Ok(ProjectYaml {
        project: ProjectMetaYaml {
            name: options.name.clone(),
            version: "0.1.0".to_string(),
            import_source: "kicad_xml_netlist".to_string(),
        },
        libraries: vec![generic_schematic_library_path()],
        board: BoardYaml { components, nets },
        scenarios: Vec::new(),
    })
}

fn apply_libsource(
    reader: &Reader<&[u8]>,
    event: &BytesStart<'_>,
    component: &mut ParsedComponent,
) -> Result<()> {
    component.lib = attr_value(reader, event, "lib")?;
    component.part = attr_value(reader, event, "part")?;
    Ok(())
}

fn push_node(reader: &Reader<&[u8]>, event: &BytesStart<'_>, net: &mut ParsedNet) -> Result<()> {
    net.nodes.push(ParsedNode {
        refdes: required_attr(reader, event, "ref")?,
        pin: required_attr(reader, event, "pin")?,
    });
    Ok(())
}

fn model_for_component(component: &ParsedComponent, default_model: &str) -> String {
    component
        .fields
        .iter()
        .find(|(name, _)| {
            name.eq_ignore_ascii_case("CircuitCI_Model")
                || name.eq_ignore_ascii_case("CircuitCIModel")
        })
        .map(|(_, value)| value.trim())
        .filter(|value| !value.is_empty())
        .unwrap_or(default_model)
        .to_string()
}

fn attr_value(
    reader: &Reader<&[u8]>,
    event: &BytesStart<'_>,
    name: &str,
) -> Result<Option<String>> {
    for attribute in event.attributes().with_checks(true) {
        let attribute = attribute.context("Malformed KiCad XML attribute")?;
        if local_name(attribute.key.as_ref()) == name {
            let value = attribute
                .decode_and_unescape_value(reader.decoder())
                .context("Failed to decode KiCad XML attribute")?
                .to_string();
            return Ok(Some(value));
        }
    }
    Ok(None)
}

fn required_attr(reader: &Reader<&[u8]>, event: &BytesStart<'_>, name: &str) -> Result<String> {
    match attr_value(reader, event, name)? {
        Some(value) if !value.trim().is_empty() => Ok(value),
        _ => bail!(
            "KiCad XML <{}> is missing required attribute {name}.",
            local_name(event.name().as_ref())
        ),
    }
}

fn unique_net_names(nets: &[ParsedNet]) -> Vec<String> {
    let mut seen = BTreeSet::new();
    nets.iter()
        .map(|net| {
            let base = net_name_for(net);
            if seen.insert(base.clone()) {
                return base;
            }
            let mut suffix = 2;
            loop {
                let candidate = format!("{base}_{suffix}");
                if seen.insert(candidate.clone()) {
                    return candidate;
                }
                suffix += 1;
            }
        })
        .collect()
}

fn net_name_for(net: &ParsedNet) -> String {
    if is_ground_net(&net.name) {
        return "gnd".to_string();
    }
    let raw = if net.name.trim().is_empty() {
        format!("code_{}", net.code)
    } else {
        net.name.clone()
    };
    format!("net_{}", sanitize_identifier(&raw))
}

fn classify_net(name: &str) -> &'static str {
    if is_ground_net(name) {
        "ground"
    } else {
        "digital_or_analog"
    }
}

fn is_ground_net(name: &str) -> bool {
    let normalized = normalize_net_name(name);
    normalized == "0" || normalized == "gnd" || normalized == "ground" || normalized.contains("gnd")
}

fn normalize_net_name(name: &str) -> String {
    name.trim()
        .trim_start_matches('/')
        .replace([' ', '_'], "")
        .to_ascii_lowercase()
}

fn sanitize_identifier(value: &str) -> String {
    let mut output = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
        } else {
            output.push('_');
        }
    }
    let trimmed = output.trim_matches('_');
    if trimmed.is_empty() {
        "unnamed".to_string()
    } else {
        trimmed.to_string()
    }
}

fn local_name(name: &[u8]) -> String {
    let text = String::from_utf8_lossy(name);
    text.rsplit(':').next().unwrap_or(&text).to_string()
}

fn non_empty(value: String) -> Option<String> {
    (!value.is_empty()).then_some(value)
}

fn generic_schematic_library_path() -> String {
    fs::canonicalize("libs/generic/schematic")
        .unwrap_or_else(|_| PathBuf::from("libs/generic/schematic"))
        .to_string_lossy()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::{classify_net, parse_kicad_netlist};

    #[test]
    fn classifies_common_power_and_ground_nets() {
        assert_eq!(classify_net("GND"), "ground");
        assert_eq!(classify_net("/+3V3"), "digital_or_analog");
        assert_eq!(classify_net("UART_TX"), "digital_or_analog");
    }

    #[test]
    fn parses_basic_kicad_xml_netlist() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("board.net");
        std::fs::write(
            &path,
            r#"
<export>
  <components>
    <comp ref="R1"><value>10k</value><libsource lib="Device" part="R"/></comp>
    <comp ref="C1"><value>100n</value></comp>
  </components>
  <nets>
    <net code="1" name="+3V3"><node ref="R1" pin="1"/></net>
    <net code="2" name="RC"><node ref="R1" pin="2"/><node ref="C1" pin="1"/></net>
    <net code="3" name="GND"><node ref="C1" pin="2"/></net>
  </nets>
</export>
"#,
        )
        .unwrap();
        let parsed = parse_kicad_netlist(&path).unwrap();
        assert_eq!(parsed.components.len(), 2);
        assert_eq!(parsed.nets.len(), 3);
        assert_eq!(parsed.nets[1].nodes.len(), 2);
    }
}
