use super::kicad::{
    KicadImportOptions, ParsedComponent, ParsedComponentInstance, ParsedKicadNetlist, ParsedNet,
    ParsedNode, import_parsed_kicad,
};
mod sexp;
mod symbols;
use anyhow::{Context, Result, bail};
use sexp::{
    Sexp, as_list, child_list, list_children, maybe_list, numeric_at, parse_sexp_document,
    string_at, tag,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use symbols::{PowerLabel, SymbolInstance, parse_lib_symbol_pins, parse_symbol_instances};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct Point {
    x: i64,
    y: i64,
}

#[derive(Debug, Clone)]
struct Segment {
    a: Point,
    b: Point,
}

type SheetPinKey = (String, String);
type SheetPinAliases = BTreeMap<SheetPinKey, String>;

#[derive(Debug)]
struct ParsedSchematic {
    source_path: PathBuf,
    netlist: ParsedKicadNetlist,
    sheets: Vec<SheetInstance>,
    sheet_pin_aliases: SheetPinAliases,
    hierarchical_labels: BTreeSet<String>,
}

#[derive(Debug)]
struct SheetInstance {
    name: String,
    file: PathBuf,
    pins: BTreeMap<String, Point>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SchematicMode {
    Root,
    Child,
}

#[derive(Debug)]
struct UnionFind {
    parent: Vec<usize>,
}

pub fn import_kicad_schematic(options: &KicadImportOptions) -> Result<()> {
    let parsed = parse_kicad_schematic(&options.input)?;
    import_parsed_kicad(
        options,
        &parsed,
        "kicad_schematic",
        "# Generated by CircuitCI from a native KiCad schematic. Add scenarios before sign-off.\n",
    )
}

pub(super) fn parse_kicad_schematic(path: &Path) -> Result<ParsedKicadNetlist> {
    let parsed = parse_schematic_file(path, SchematicMode::Root)?;
    let source_path = parsed.source_path.clone();
    flatten_schematic(parsed, &mut vec![source_path])
}

fn flatten_schematic(
    parsed: ParsedSchematic,
    stack: &mut Vec<PathBuf>,
) -> Result<ParsedKicadNetlist> {
    if parsed.sheets.is_empty() {
        return Ok(parsed.netlist);
    }

    let mut children = Vec::new();
    for sheet in &parsed.sheets {
        let child = parse_schematic_file(&sheet.file, SchematicMode::Child)?;
        if stack.contains(&child.source_path) {
            bail!(
                "KiCad schematic hierarchy contains a cycle through {}.",
                child.source_path.display()
            );
        }
        let sheet_pin_names = sheet_pin_names(sheet);
        if sheet_pin_names != child.hierarchical_labels {
            bail!(
                "KiCad sheet {} pins {:?} do not exactly match child hierarchical labels {:?}.",
                sheet.name,
                sheet_pin_names,
                child.hierarchical_labels
            );
        }
        let child_source_path = child.source_path.clone();
        stack.push(child_source_path);
        let child_netlist = flatten_schematic(child, stack)?;
        stack.pop();
        children.push((sheet, child_netlist));
    }

    let namespaced_sheets = sheets_requiring_component_namespace(&parsed.netlist, &children);
    let mut netlist = parsed.netlist;
    for (sheet, child_netlist) in children {
        let child_netlist = if namespaced_sheets.contains(&sheet.name) {
            namespace_child_components(child_netlist, sheet)?
        } else {
            child_netlist
        };
        netlist =
            merge_hierarchical_netlists(netlist, child_netlist, sheet, &parsed.sheet_pin_aliases)?;
    }
    Ok(netlist)
}

fn parse_schematic_file(path: &Path, mode: SchematicMode) -> Result<ParsedSchematic> {
    let source_path = fs::canonicalize(path)
        .with_context(|| format!("Failed to resolve KiCad schematic {}", path.display()))?;
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read KiCad schematic {}", path.display()))?;
    let root = parse_sexp_document(&text)?;
    let root_list = as_list(&root).context("KiCad schematic must be an S-expression list.")?;
    if tag(root_list) != Some("kicad_sch") {
        bail!(
            "KiCad schematic {} root token is not kicad_sch.",
            path.display()
        );
    }
    reject_unsupported_constructs(root_list, mode)?;
    let sheets = parse_sheets(root_list, path)?;
    let lib_pins = parse_lib_symbol_pins(root_list)?;
    let (symbols, power_labels) = parse_symbol_instances(root_list, &lib_pins)?;
    if symbols.is_empty() && sheets.is_empty() {
        bail!(
            "KiCad schematic {} contains no importable symbols.",
            path.display()
        );
    }
    validate_symbol_package_refs(&symbols)?;
    let (segments, junctions) = parse_wires_and_junctions(root_list)?;
    let (mut labels, hierarchical_labels) = parse_labels(root_list, power_labels, mode)?;
    validate_bus_graphics(root_list, &segments, &mut labels)?;
    let no_connects = parse_no_connects(root_list)?;
    let (effective_labels, sheet_pin_aliases) = if sheets.is_empty() {
        (labels.clone(), BTreeMap::new())
    } else {
        hierarchy_net_aliases(&sheets, &symbols, &segments, &junctions, &labels)?
    };
    let nets = if symbols.is_empty() {
        Vec::new()
    } else {
        build_nets(
            &symbols,
            &segments,
            &junctions,
            &effective_labels,
            &no_connects,
        )?
    };

    let components = build_components_from_symbols(symbols)?;
    Ok(ParsedSchematic {
        source_path,
        netlist: ParsedKicadNetlist { components, nets },
        sheets,
        sheet_pin_aliases,
        hierarchical_labels,
    })
}

fn build_components_from_symbols(
    symbols: Vec<SymbolInstance>,
) -> Result<BTreeMap<String, ParsedComponent>> {
    let mut components = BTreeMap::new();
    for symbol in symbols {
        if let Some(component) = components.get_mut(&symbol.refdes) {
            merge_symbol_unit(component, symbol)?;
        } else {
            components.insert(symbol.refdes.clone(), component_from_symbol(symbol));
        }
    }
    Ok(components)
}

fn validate_symbol_package_refs(symbols: &[SymbolInstance]) -> Result<()> {
    let mut first_by_ref: BTreeMap<&str, &SymbolInstance> = BTreeMap::new();
    let mut units_by_ref: BTreeMap<&str, BTreeSet<u32>> = BTreeMap::new();
    for symbol in symbols {
        if let Some(first) = first_by_ref.get(symbol.refdes.as_str()) {
            if first.value != symbol.value
                || first.lib != symbol.lib
                || first.part != symbol.part
                || first.fields != symbol.fields
                || first.in_bom != symbol.in_bom
            {
                bail!(
                    "KiCad schematic component {} has duplicate units with conflicting package metadata.",
                    symbol.refdes
                );
            }
        } else {
            first_by_ref.insert(symbol.refdes.as_str(), symbol);
        }
        let units = units_by_ref.entry(symbol.refdes.as_str()).or_default();
        if !units.insert(symbol.unit) {
            bail!(
                "KiCad schematic component {} has duplicate unit {}.",
                symbol.refdes,
                symbol.unit
            );
        }
    }
    Ok(())
}

fn component_from_symbol(symbol: SymbolInstance) -> ParsedComponent {
    ParsedComponent {
        refdes: symbol.refdes,
        value: symbol.value,
        lib: symbol.lib,
        part: symbol.part,
        fields: symbol.fields,
        in_bom: Some(symbol.in_bom),
        unit: Some(symbol.unit),
        units: Vec::new(),
        instances: symbol
            .instances
            .into_iter()
            .map(|instance| ParsedComponentInstance {
                project: instance.project,
                path: instance.path,
                reference: instance.reference,
                unit: instance.unit,
            })
            .collect(),
    }
}

fn merge_symbol_unit(component: &mut ParsedComponent, symbol: SymbolInstance) -> Result<()> {
    if component.value != symbol.value
        || component.lib != symbol.lib
        || component.part != symbol.part
        || component.fields != symbol.fields
        || component.in_bom != Some(symbol.in_bom)
    {
        bail!(
            "KiCad schematic component {} has duplicate units with conflicting package metadata.",
            component.refdes
        );
    }

    if component.units.is_empty() {
        let existing_unit = component
            .unit
            .take()
            .expect("native schematic components keep source.unit until merged");
        component.units.push(existing_unit);
    }
    if component.units.contains(&symbol.unit) {
        bail!(
            "KiCad schematic component {} has duplicate unit {}.",
            component.refdes,
            symbol.unit
        );
    }
    component.units.push(symbol.unit);
    component.units.sort_unstable();
    component
        .instances
        .extend(
            symbol
                .instances
                .into_iter()
                .map(|instance| ParsedComponentInstance {
                    project: instance.project,
                    path: instance.path,
                    reference: instance.reference,
                    unit: instance.unit,
                }),
        );
    Ok(())
}

fn sheets_requiring_component_namespace(
    root: &ParsedKicadNetlist,
    children: &[(&SheetInstance, ParsedKicadNetlist)],
) -> BTreeSet<String> {
    let mut owners_by_ref: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for refdes in root.components.keys() {
        owners_by_ref
            .entry(refdes.clone())
            .or_default()
            .insert(String::new());
    }
    for (sheet, child) in children {
        for refdes in child.components.keys() {
            owners_by_ref
                .entry(refdes.clone())
                .or_default()
                .insert(sheet.name.clone());
        }
    }

    let mut namespaced_sheets = BTreeSet::new();
    for owners in owners_by_ref.values() {
        if owners.len() <= 1 {
            continue;
        }
        for owner in owners {
            if !owner.is_empty() {
                namespaced_sheets.insert(owner.clone());
            }
        }
    }
    namespaced_sheets
}

fn namespace_child_components(
    mut child: ParsedKicadNetlist,
    sheet: &SheetInstance,
) -> Result<ParsedKicadNetlist> {
    let prefix = sanitize_sheet_net_prefix(&sheet.name);
    let mut renames = BTreeMap::new();
    let mut components = BTreeMap::new();
    for (old_refdes, mut component) in child.components {
        let new_refdes = format!("{prefix}__{old_refdes}");
        if components.contains_key(&new_refdes) {
            bail!(
                "KiCad sheet {} component references collide after namespacing as {new_refdes}.",
                sheet.name
            );
        }
        component.refdes = new_refdes.clone();
        renames.insert(old_refdes, new_refdes.clone());
        components.insert(new_refdes, component);
    }

    for net in &mut child.nets {
        for node in &mut net.nodes {
            if let Some(new_refdes) = renames.get(&node.refdes) {
                node.refdes = new_refdes.clone();
            }
        }
    }
    child.components = components;
    Ok(child)
}

fn merge_hierarchical_netlists(
    mut root: ParsedKicadNetlist,
    child: ParsedKicadNetlist,
    sheet: &SheetInstance,
    aliases: &SheetPinAliases,
) -> Result<ParsedKicadNetlist> {
    for (refdes, component) in child.components {
        if root.components.contains_key(&refdes) {
            bail!("KiCad hierarchy has duplicate component reference {refdes}.");
        }
        root.components.insert(refdes, component);
    }

    let mut nodes_by_name: BTreeMap<String, Vec<ParsedNode>> = BTreeMap::new();
    for net in root.nets {
        nodes_by_name.entry(net.name).or_default().extend(net.nodes);
    }
    for net in child.nets {
        let name = if sheet.pins.contains_key(&net.name) || is_ground_net_name(&net.name) {
            aliases
                .get(&(sheet.name.clone(), net.name.clone()))
                .cloned()
                .unwrap_or(net.name)
        } else {
            format!("{}_{}", sanitize_sheet_net_prefix(&sheet.name), net.name)
        };
        nodes_by_name.entry(name).or_default().extend(net.nodes);
    }

    let nets = nodes_by_name
        .into_iter()
        .enumerate()
        .map(|(index, (name, nodes))| ParsedNet {
            code: (index + 1).to_string(),
            name,
            nodes,
        })
        .collect();
    Ok(ParsedKicadNetlist {
        components: root.components,
        nets,
    })
}

fn reject_unsupported_constructs(root: &[Sexp], mode: SchematicMode) -> Result<()> {
    for item in root.iter().skip(1) {
        let Some(list) = maybe_list(item) else {
            continue;
        };
        match tag(list) {
            Some("hierarchical_label") if mode == SchematicMode::Root => {
                bail!("Native KiCad schematic import does not support hierarchical labels yet.")
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_sheets(root: &[Sexp], schematic_path: &Path) -> Result<Vec<SheetInstance>> {
    let mut sheets = Vec::new();
    let mut sheet_names = BTreeSet::new();
    let mut sheet_prefixes = BTreeMap::new();
    for sheet in list_children(root, "sheet") {
        let properties = parse_properties(sheet);
        let sheet_name = properties
            .get("Sheetname")
            .filter(|value| !value.trim().is_empty())
            .with_context(|| "KiCad sheet is missing Sheetname property.")?
            .to_string();
        if !sheet_names.insert(sheet_name.clone()) {
            bail!("KiCad schematic has duplicate sheet name {sheet_name}.");
        }
        let sheet_prefix = sanitize_sheet_net_prefix(&sheet_name);
        if let Some(existing_sheet) =
            sheet_prefixes.insert(sheet_prefix.clone(), sheet_name.clone())
        {
            bail!(
                "KiCad sheets {existing_sheet} and {sheet_name} sanitize to the same local-net prefix {sheet_prefix}; use distinct sheet names before importing hierarchy."
            );
        }
        let file = properties
            .get("Sheetfile")
            .filter(|value| !value.trim().is_empty())
            .with_context(|| format!("KiCad sheet {sheet_name} is missing Sheetfile property."))?;
        let file = resolve_sheet_file(schematic_path, file);
        if !file.is_file() {
            bail!(
                "KiCad sheet {sheet_name} file {} does not exist.",
                file.display()
            );
        }
        let mut pins = BTreeMap::new();
        for pin in list_children(sheet, "pin") {
            let pin_name = string_at(pin, 1)
                .filter(|value| !value.trim().is_empty())
                .with_context(|| "KiCad sheet pin is missing a name.")?
                .to_string();
            if pins.contains_key(&pin_name) {
                bail!("KiCad sheet {sheet_name} has duplicate pin {pin_name}.");
            }
            let point = child_list(pin, "at")
                .and_then(parse_at_point)
                .with_context(|| {
                    format!("KiCad sheet pin {pin_name} is missing valid coordinates.")
                })?;
            pins.insert(pin_name, point);
        }
        if pins.is_empty() {
            bail!("KiCad sheet {sheet_name} must declare at least one hierarchical pin.");
        }
        sheets.push(SheetInstance {
            name: sheet_name,
            file,
            pins,
        });
    }
    Ok(sheets)
}

fn parse_properties(list: &[Sexp]) -> BTreeMap<String, String> {
    let mut properties = BTreeMap::new();
    for property in list_children(list, "property") {
        if let (Some(name), Some(value)) = (string_at(property, 1), string_at(property, 2)) {
            properties.insert(name.to_string(), value.to_string());
        }
    }
    properties
}

fn resolve_sheet_file(schematic_path: &Path, sheet_file: &str) -> PathBuf {
    let path = Path::new(sheet_file);
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        schematic_path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(path)
    }
}

fn sheet_pin_names(sheet: &SheetInstance) -> BTreeSet<String> {
    sheet.pins.keys().cloned().collect()
}

fn parse_wires_and_junctions(root: &[Sexp]) -> Result<(Vec<Segment>, BTreeSet<Point>)> {
    let mut segments = Vec::new();
    for wire in list_children(root, "wire") {
        let points = child_list(wire, "pts")
            .map(parse_points)
            .transpose()?
            .with_context(|| "KiCad wire is missing pts.")?;
        if points.len() < 2 {
            bail!("KiCad wire must contain at least two points.");
        }
        for pair in points.windows(2) {
            let segment = Segment {
                a: pair[0],
                b: pair[1],
            };
            if !segment.is_axis_aligned() {
                bail!("Native KiCad schematic import supports only horizontal or vertical wires.");
            }
            segments.push(segment);
        }
    }
    let junctions = parse_junctions(root)?;
    validate_junctions(&segments, &junctions)?;
    reject_unjunctioned_crossings(&segments, &junctions)?;
    Ok((segments, junctions))
}

fn validate_bus_graphics(
    root: &[Sexp],
    wire_segments: &[Segment],
    labels: &mut BTreeMap<Point, String>,
) -> Result<()> {
    let bus_aliases = parse_bus_aliases(root)?;
    let alias_members = bus_aliases
        .values()
        .flat_map(|members| members.iter().cloned())
        .collect::<BTreeSet<_>>();
    let mut bus_segments = Vec::new();

    for bus in list_children(root, "bus") {
        let points = child_list(bus, "pts")
            .map(parse_points)
            .transpose()?
            .with_context(|| "KiCad bus is missing pts.")?;
        if points.len() < 2 {
            bail!("KiCad bus must contain at least two points.");
        }
        for pair in points.windows(2) {
            let segment = Segment {
                a: pair[0],
                b: pair[1],
            };
            if !segment.is_axis_aligned() {
                bail!("Native KiCad schematic import supports only horizontal or vertical buses.");
            }
            bus_segments.push(segment);
        }
    }

    let bus_labels = resolve_bus_labels(&bus_aliases, &alias_members, &bus_segments, labels)?;

    for bus_entry in list_children(root, "bus_entry") {
        let start = child_list(bus_entry, "at")
            .and_then(parse_at_point)
            .with_context(|| "KiCad bus_entry is missing valid coordinates.")?;
        let size = child_list(bus_entry, "size")
            .and_then(parse_size_point)
            .with_context(|| "KiCad bus_entry is missing valid size.")?;
        let endpoints = [
            start,
            Point {
                x: start.x + size.x,
                y: start.y + size.y,
            },
        ];
        let touching_wires = wire_segments
            .iter()
            .filter(|segment| endpoints.iter().any(|point| segment.is_endpoint(*point)))
            .collect::<Vec<_>>();
        if touching_wires.is_empty() {
            bail!("KiCad bus_entry is not attached to any scalar wire endpoint.");
        }
        for wire in touching_wires {
            let wire_labels = labels
                .iter()
                .filter_map(|(point, label)| wire.contains(*point).then_some(label))
                .collect::<Vec<_>>();
            if wire_labels.is_empty() {
                let candidates =
                    bus_entry_member_candidates(&endpoints, &bus_segments, &bus_labels);
                if candidates.len() == 1 {
                    let inferred = candidates
                        .iter()
                        .next()
                        .expect("checked one candidate")
                        .clone();
                    let insert_at = endpoints
                        .iter()
                        .find(|point| wire.is_endpoint(**point))
                        .copied()
                        .expect("touching wire checked");
                    insert_label(labels, insert_at, inferred)?;
                    continue;
                }
                if candidates.is_empty() {
                    bail!(
                        "KiCad bus_entry wire endpoint requires an explicit scalar label or one resolvable bus label."
                    );
                }
                bail!(
                    "KiCad bus_entry wire endpoint is ambiguous across bus members {candidates:?}."
                );
            }
            if !alias_members.is_empty() {
                for label in wire_labels {
                    if !alias_members.contains(label) {
                        bail!(
                            "KiCad bus_entry scalar label {label} is not declared by any bus_alias member."
                        );
                    }
                }
            }
        }
    }
    Ok(())
}

fn resolve_bus_labels(
    bus_aliases: &BTreeMap<String, BTreeSet<String>>,
    alias_members: &BTreeSet<String>,
    bus_segments: &[Segment],
    labels: &mut BTreeMap<Point, String>,
) -> Result<Vec<(Point, BTreeSet<String>)>> {
    let mut bus_labels = Vec::new();
    let mut consumed_points = Vec::new();
    for (point, label) in labels.iter() {
        if !bus_segments.iter().any(|segment| segment.contains(*point)) {
            continue;
        }
        let resolved = if let Some(members) = bus_aliases.get(label) {
            members.clone()
        } else if alias_members.contains(label) {
            BTreeSet::from([label.clone()])
        } else {
            bail!("KiCad bus label {label} is not a bus_alias name or member.");
        };
        bus_labels.push((*point, resolved));
        consumed_points.push(*point);
    }
    for point in consumed_points {
        labels.remove(&point);
    }
    Ok(bus_labels)
}

fn bus_entry_member_candidates(
    endpoints: &[Point; 2],
    bus_segments: &[Segment],
    bus_labels: &[(Point, BTreeSet<String>)],
) -> BTreeSet<String> {
    let attached_bus_segments = bus_segments
        .iter()
        .filter(|segment| endpoints.iter().any(|point| segment.contains(*point)))
        .collect::<Vec<_>>();
    let mut candidates = BTreeSet::new();
    for (label_point, members) in bus_labels {
        if attached_bus_segments
            .iter()
            .any(|segment| segment.contains(*label_point))
        {
            candidates.extend(members.iter().cloned());
        }
    }
    candidates
}

fn parse_bus_aliases(root: &[Sexp]) -> Result<BTreeMap<String, BTreeSet<String>>> {
    let mut aliases = BTreeMap::new();
    let mut global_members = BTreeMap::new();
    for alias in list_children(root, "bus_alias") {
        let name = string_at(alias, 1)
            .filter(|value| !value.trim().is_empty())
            .with_context(|| "KiCad bus_alias is missing a name.")?
            .to_string();
        if aliases.contains_key(&name) {
            bail!("KiCad schematic has duplicate bus_alias {name}.");
        }
        let members_list = child_list(alias, "members")
            .with_context(|| format!("KiCad bus_alias {name} is missing members."))?;
        let mut members = BTreeSet::new();
        for member in members_list.iter().skip(1) {
            let Sexp::Str(value) = member else {
                bail!("KiCad bus_alias {name} has malformed member.");
            };
            let member = value.trim();
            if member.is_empty() {
                bail!("KiCad bus_alias {name} has an empty member.");
            }
            for expanded in expand_bus_alias_member(&name, member)? {
                if !members.insert(expanded.clone()) {
                    bail!("KiCad bus_alias {name} has duplicate member {expanded}.");
                }
                if let Some(existing_alias) = global_members.insert(expanded.clone(), name.clone())
                {
                    bail!(
                        "KiCad bus_alias member {expanded} appears in both {existing_alias} and {name}."
                    );
                }
            }
        }
        if members.is_empty() {
            bail!("KiCad bus_alias {name} must declare at least one member.");
        }
        aliases.insert(name, members);
    }
    Ok(aliases)
}

fn expand_bus_alias_member(alias_name: &str, member: &str) -> Result<Vec<String>> {
    if member.contains('{') || member.contains('}') {
        bail!("KiCad bus_alias {alias_name} member {member} uses unsupported grouped syntax.");
    }

    let Some(open) = member.find('[') else {
        if member.contains(']') || member.contains("..") {
            bail!("KiCad bus_alias {alias_name} member {member} has malformed range syntax.");
        }
        return Ok(vec![member.to_string()]);
    };

    let Some(close_offset) = member[open + 1..].find(']') else {
        bail!("KiCad bus_alias {alias_name} member {member} has malformed range syntax.");
    };
    let close = open + 1 + close_offset;
    if member[open + 1..close].contains('[') || member[close + 1..].contains(['[', ']']) {
        bail!("KiCad bus_alias {alias_name} member {member} has malformed range syntax.");
    }

    let range = &member[open + 1..close];
    let (start_raw, end_raw) = range.split_once("..").with_context(|| {
        format!("KiCad bus_alias {alias_name} member {member} is missing '..'.")
    })?;
    if start_raw.is_empty()
        || end_raw.is_empty()
        || !start_raw.chars().all(|ch| ch.is_ascii_digit())
        || !end_raw.chars().all(|ch| ch.is_ascii_digit())
    {
        bail!("KiCad bus_alias {alias_name} member {member} range bounds must be decimal.");
    }

    let start = start_raw.parse::<usize>().with_context(|| {
        format!("KiCad bus_alias {alias_name} member {member} range start is invalid.")
    })?;
    let end = end_raw.parse::<usize>().with_context(|| {
        format!("KiCad bus_alias {alias_name} member {member} range end is invalid.")
    })?;
    if start > end {
        bail!("KiCad bus_alias {alias_name} member {member} descending ranges are unsupported.");
    }
    let count = end - start + 1;
    if count > 1024 {
        bail!("KiCad bus_alias {alias_name} member {member} expands to more than 1024 labels.");
    }

    let prefix = &member[..open];
    let suffix = &member[close + 1..];
    let width = if start_raw.len() == end_raw.len() && start_raw.len() > 1 {
        start_raw.len()
    } else {
        0
    };
    Ok((start..=end)
        .map(|index| {
            if width > 0 {
                format!("{prefix}{index:0width$}{suffix}")
            } else {
                format!("{prefix}{index}{suffix}")
            }
        })
        .collect())
}

fn parse_junctions(root: &[Sexp]) -> Result<BTreeSet<Point>> {
    let mut junctions = BTreeSet::new();
    for junction in list_children(root, "junction") {
        let point = child_list(junction, "at")
            .and_then(parse_at_point)
            .with_context(|| "KiCad junction is missing valid coordinates.")?;
        if !junctions.insert(point) {
            bail!("KiCad schematic has duplicate junction at one coordinate.");
        }
    }
    Ok(junctions)
}

fn validate_junctions(segments: &[Segment], junctions: &BTreeSet<Point>) -> Result<()> {
    for junction in junctions {
        let touches = segments
            .iter()
            .filter(|segment| segment.contains(*junction))
            .count();
        if touches == 0 {
            bail!("KiCad junction is not attached to any wire.");
        }
        if touches == 1 {
            bail!("KiCad junction touches only one wire segment.");
        }
    }
    Ok(())
}

fn parse_labels(
    root: &[Sexp],
    power_labels: Vec<PowerLabel>,
    mode: SchematicMode,
) -> Result<(BTreeMap<Point, String>, BTreeSet<String>)> {
    let mut labels = BTreeMap::new();
    let mut hierarchical_labels = BTreeSet::new();
    for (point, name) in power_labels {
        insert_label(&mut labels, point, name)?;
    }
    for label_tag in ["label", "global_label", "hierarchical_label"] {
        if label_tag == "hierarchical_label" && mode != SchematicMode::Child {
            continue;
        }
        for label in list_children(root, label_tag) {
            let name = string_at(label, 1)
                .filter(|value| !value.trim().is_empty())
                .with_context(|| format!("KiCad {label_tag} is missing a label name."))?;
            let at = child_list(label, "at")
                .and_then(parse_at_point)
                .with_context(|| {
                    format!("KiCad {label_tag} {name} is missing valid coordinates.")
                })?;
            if label_tag == "hierarchical_label" && !hierarchical_labels.insert(name.to_string()) {
                bail!("KiCad child schematic has duplicate hierarchical label {name}.");
            }
            insert_label(&mut labels, at, name.to_string())?;
        }
    }
    Ok((labels, hierarchical_labels))
}

fn insert_label(labels: &mut BTreeMap<Point, String>, point: Point, name: String) -> Result<()> {
    if let Some(existing) = labels.get(&point) {
        if existing == &name {
            bail!("KiCad schematic has duplicate label {name} at one coordinate.");
        }
        bail!(
            "KiCad schematic has conflicting labels {existing:?} and {name:?} at one coordinate."
        );
    }
    labels.insert(point, name);
    Ok(())
}

fn parse_no_connects(root: &[Sexp]) -> Result<BTreeSet<Point>> {
    let mut no_connects = BTreeSet::new();
    for no_connect in list_children(root, "no_connect") {
        let at = child_list(no_connect, "at")
            .and_then(parse_at_point)
            .with_context(|| "KiCad no_connect marker is missing valid coordinates.")?;
        no_connects.insert(at);
    }
    Ok(no_connects)
}

fn hierarchy_net_aliases(
    sheets: &[SheetInstance],
    symbols: &[SymbolInstance],
    segments: &[Segment],
    junctions: &BTreeSet<Point>,
    labels: &BTreeMap<Point, String>,
) -> Result<(BTreeMap<Point, String>, SheetPinAliases)> {
    let mut effective_labels = labels.clone();
    let sheet_pins = sheets
        .iter()
        .flat_map(|sheet| {
            sheet
                .pins
                .iter()
                .map(move |(name, point)| (sheet.name.as_str(), name.as_str(), *point))
        })
        .collect::<Vec<_>>();
    if sheet_pins.is_empty() {
        return Ok((effective_labels, BTreeMap::new()));
    }

    let mut points = BTreeSet::new();
    for segment in segments {
        points.insert(segment.a);
        points.insert(segment.b);
    }
    points.extend(junctions.iter().copied());
    points.extend(labels.keys().copied());
    for symbol in symbols {
        points.extend(symbol.pins.values().copied());
    }
    for (_, _, point) in &sheet_pins {
        if !is_connectivity_attached(*point, segments, labels)
            && !symbols
                .iter()
                .any(|symbol| symbol.pins.values().any(|pin| pin == point))
        {
            bail!(
                "KiCad sheet pin at root coordinate is not attached to a wire, symbol pin, or label."
            );
        }
        points.insert(*point);
    }

    let mut index = BTreeMap::new();
    for point in &points {
        let next = index.len();
        index.insert(*point, next);
    }
    let mut uf = UnionFind::new(index.len());
    for segment in segments {
        let segment_points = points
            .iter()
            .filter(|point| segment.contains(**point))
            .copied()
            .collect::<Vec<_>>();
        for pair in segment_points.windows(2) {
            uf.union(index[&pair[0]], index[&pair[1]]);
        }
    }

    let mut labels_by_root: BTreeMap<usize, BTreeSet<String>> = BTreeMap::new();
    for (point, label) in labels {
        let root = uf.find(index[point]);
        labels_by_root
            .entry(root)
            .or_default()
            .insert(label.clone());
    }

    let mut pins_by_root: BTreeMap<usize, Vec<(&str, &str, Point)>> = BTreeMap::new();
    for (sheet, pin, point) in sheet_pins {
        let root = uf.find(index[&point]);
        pins_by_root
            .entry(root)
            .or_default()
            .push((sheet, pin, point));
    }

    let mut aliases = BTreeMap::new();
    let mut canonical_roots = BTreeMap::new();
    for (root, pins) in pins_by_root {
        let user_labels = labels_by_root.get(&root).cloned().unwrap_or_default();
        if user_labels.len() > 1 {
            bail!("KiCad schematic net has conflicting labels {user_labels:?}.");
        }
        let pin_names = pins
            .iter()
            .map(|(_, pin, _)| (*pin).to_string())
            .collect::<BTreeSet<_>>();
        let canonical = if let Some(label) = user_labels.iter().next() {
            label.clone()
        } else if pin_names.len() == 1 {
            pin_names.iter().next().expect("checked one pin").clone()
        } else if pin_names.iter().all(|name| is_ground_net_name(name)) {
            "GND".to_string()
        } else {
            bail!(
                "KiCad root net connects multiple sheet pins {pin_names:?} without an explicit root label."
            );
        };
        if user_labels.is_empty() {
            let point = pins
                .first()
                .map(|(_, _, point)| *point)
                .expect("checked non-empty pins");
            insert_label(&mut effective_labels, point, canonical.clone())?;
        }
        if !is_ground_net_name(&canonical)
            && canonical_roots.insert(canonical.clone(), root).is_some()
        {
            bail!(
                "KiCad disconnected root nets both resolve to sheet alias {canonical}; add distinct explicit root labels."
            );
        }
        for (sheet, pin, _) in pins {
            aliases.insert((sheet.to_string(), pin.to_string()), canonical.clone());
        }
    }
    Ok((effective_labels, aliases))
}

fn build_nets(
    symbols: &[SymbolInstance],
    segments: &[Segment],
    junctions: &BTreeSet<Point>,
    labels: &BTreeMap<Point, String>,
    no_connects: &BTreeSet<Point>,
) -> Result<Vec<ParsedNet>> {
    validate_no_connects(symbols, segments, labels, no_connects)?;
    validate_labels_attached(symbols, segments, labels)?;
    let mut points = BTreeSet::new();
    for segment in segments {
        points.insert(segment.a);
        points.insert(segment.b);
    }
    points.extend(junctions.iter().copied());
    points.extend(labels.keys().copied());
    let mut connected_pins = Vec::new();
    let mut connected_pin_counts: BTreeMap<&str, usize> = BTreeMap::new();
    for symbol in symbols {
        let _ = (&symbol.at, &symbol.lib_id, symbol.is_power_symbol);
        for (pin, point) in &symbol.pins {
            if no_connects.contains(point) {
                continue;
            }
            if !is_connectivity_attached(*point, segments, labels) {
                bail!(
                    "KiCad schematic pin {}.{} is unconnected; add a no_connect marker or wire/label it.",
                    symbol.refdes,
                    pin
                );
            }
            connected_pins.push((&symbol.refdes, pin, *point));
            *connected_pin_counts
                .entry(symbol.refdes.as_str())
                .or_default() += 1;
            points.insert(*point);
        }
        if connected_pin_counts
            .get(symbol.refdes.as_str())
            .copied()
            .unwrap_or(0)
            == 0
        {
            bail!(
                "KiCad schematic component {} has no connected pins; at least one pin must be wired or labeled.",
                symbol.refdes
            );
        }
    }

    let mut index = BTreeMap::new();
    for point in &points {
        let next = index.len();
        index.insert(*point, next);
    }
    let mut uf = UnionFind::new(index.len());
    for segment in segments {
        let segment_points = points
            .iter()
            .filter(|point| segment.contains(**point))
            .copied()
            .collect::<Vec<_>>();
        for pair in segment_points.windows(2) {
            uf.union(index[&pair[0]], index[&pair[1]]);
        }
    }

    let mut labels_by_root: BTreeMap<usize, BTreeSet<String>> = BTreeMap::new();
    for (point, label) in labels {
        let root = uf.find(index[point]);
        labels_by_root
            .entry(root)
            .or_default()
            .insert(label.clone());
    }
    for labels in labels_by_root.values() {
        if labels.len() > 1 {
            bail!("KiCad schematic net has conflicting labels {labels:?}.");
        }
    }

    let mut nodes_by_key: BTreeMap<String, Vec<ParsedNode>> = BTreeMap::new();
    let mut label_by_key = BTreeMap::new();
    for (refdes, pin, point) in connected_pins {
        let root = uf.find(index[&point]);
        let label = labels_by_root
            .get(&root)
            .and_then(|labels| labels.iter().next().cloned());
        let key = label.clone().unwrap_or_else(|| format!("__root_{root}"));
        if let Some(label) = label {
            label_by_key.insert(key.clone(), label);
        }
        nodes_by_key.entry(key).or_default().push(ParsedNode {
            refdes: refdes.clone(),
            pin: pin.clone(),
        });
    }

    let mut nets = Vec::new();
    for (index, (key, nodes)) in nodes_by_key.into_iter().enumerate() {
        if nodes.is_empty() {
            continue;
        }
        let name = label_by_key
            .get(&key)
            .cloned()
            .unwrap_or_else(|| format!("net_{}", index + 1));
        nets.push(ParsedNet {
            code: (index + 1).to_string(),
            name,
            nodes,
        });
    }
    if nets.is_empty() {
        bail!("KiCad schematic has no connected component pins.");
    }
    Ok(nets)
}

fn validate_labels_attached(
    symbols: &[SymbolInstance],
    segments: &[Segment],
    labels: &BTreeMap<Point, String>,
) -> Result<()> {
    for (point, label) in labels {
        if !segments.iter().any(|segment| segment.contains(*point))
            && !symbols
                .iter()
                .any(|symbol| symbol.pins.values().any(|pin| pin == point))
        {
            bail!("KiCad schematic label {label} is not attached to a wire or pin.");
        }
    }
    Ok(())
}

fn validate_no_connects(
    symbols: &[SymbolInstance],
    segments: &[Segment],
    labels: &BTreeMap<Point, String>,
    no_connects: &BTreeSet<Point>,
) -> Result<()> {
    for point in no_connects {
        let attached_pins = symbols
            .iter()
            .flat_map(|symbol| {
                symbol.pins.iter().filter_map(|(pin, pin_point)| {
                    (pin_point == point).then_some((&symbol.refdes, pin))
                })
            })
            .collect::<Vec<_>>();
        if attached_pins.is_empty() {
            bail!("KiCad no_connect marker is not attached to any symbol pin.");
        }
        if attached_pins.len() > 1 {
            bail!("KiCad no_connect marker matches multiple symbol pins.");
        }
        let (refdes, pin) = attached_pins[0];
        if is_connectivity_attached(*point, segments, labels) {
            bail!(
                "KiCad no_connect marker is attached to connected pin {}.{}.",
                refdes,
                pin
            );
        }
    }
    Ok(())
}

fn is_connectivity_attached(
    point: Point,
    segments: &[Segment],
    labels: &BTreeMap<Point, String>,
) -> bool {
    labels.contains_key(&point) || segments.iter().any(|segment| segment.contains(point))
}

fn reject_unjunctioned_crossings(segments: &[Segment], junctions: &BTreeSet<Point>) -> Result<()> {
    for (left_index, left) in segments.iter().enumerate() {
        for right in segments.iter().skip(left_index + 1) {
            let Some(point) = left.intersection(right) else {
                continue;
            };
            let endpoint_touch = left.is_endpoint(point) || right.is_endpoint(point);
            if !endpoint_touch && !junctions.contains(&point) {
                bail!("KiCad schematic has crossing wires without an explicit junction.");
            }
        }
    }
    Ok(())
}

impl Segment {
    fn is_axis_aligned(&self) -> bool {
        self.a.x == self.b.x || self.a.y == self.b.y
    }

    fn contains(&self, point: Point) -> bool {
        if self.a.x == self.b.x {
            point.x == self.a.x && between(point.y, self.a.y, self.b.y)
        } else if self.a.y == self.b.y {
            point.y == self.a.y && between(point.x, self.a.x, self.b.x)
        } else {
            false
        }
    }

    fn is_endpoint(&self, point: Point) -> bool {
        self.a == point || self.b == point
    }

    fn intersection(&self, other: &Segment) -> Option<Point> {
        if self.a.x == self.b.x && other.a.y == other.b.y {
            let point = Point {
                x: self.a.x,
                y: other.a.y,
            };
            (self.contains(point) && other.contains(point)).then_some(point)
        } else if self.a.y == self.b.y && other.a.x == other.b.x {
            let point = Point {
                x: other.a.x,
                y: self.a.y,
            };
            (self.contains(point) && other.contains(point)).then_some(point)
        } else {
            None
        }
    }
}

impl UnionFind {
    fn new(size: usize) -> Self {
        Self {
            parent: (0..size).collect(),
        }
    }

    fn find(&mut self, item: usize) -> usize {
        if self.parent[item] != item {
            self.parent[item] = self.find(self.parent[item]);
        }
        self.parent[item]
    }

    fn union(&mut self, a: usize, b: usize) {
        let root_a = self.find(a);
        let root_b = self.find(b);
        if root_a != root_b {
            self.parent[root_b] = root_a;
        }
    }
}

fn parse_points(list: &[Sexp]) -> Result<Vec<Point>> {
    list_children(list, "xy")
        .map(|xy| {
            let x = numeric_at(xy, 1).with_context(|| "KiCad xy point is missing x.")?;
            let y = numeric_at(xy, 2).with_context(|| "KiCad xy point is missing y.")?;
            Ok(Point {
                x: quantize_coord(x),
                y: quantize_coord(y),
            })
        })
        .collect()
}

fn parse_at_point(list: &[Sexp]) -> Option<Point> {
    Some(Point {
        x: quantize_coord(numeric_at(list, 1)?),
        y: quantize_coord(numeric_at(list, 2)?),
    })
}

fn parse_size_point(list: &[Sexp]) -> Option<Point> {
    parse_at_point(list)
}

fn is_ground_net_name(name: &str) -> bool {
    let normalized = name
        .trim()
        .trim_start_matches('/')
        .replace([' ', '_'], "")
        .to_ascii_lowercase();
    normalized == "0" || normalized == "gnd" || normalized == "ground" || normalized.contains("gnd")
}

fn sanitize_sheet_net_prefix(value: &str) -> String {
    let mut output = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
        } else {
            output.push('_');
        }
    }
    let trimmed = output.trim_matches('_');
    if trimmed.is_empty() {
        "sheet".to_string()
    } else {
        trimmed.to_string()
    }
}

fn quantize_coord(value: f64) -> i64 {
    (value * 1_000_000.0).round() as i64
}

fn between(value: i64, a: i64, b: i64) -> bool {
    value >= a.min(b) && value <= a.max(b)
}

#[cfg(test)]
mod tests {
    use super::parse_kicad_schematic;

    #[test]
    fn parses_single_sheet_schematic_connectivity() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("basic.kicad_sch");
        std::fs::write(
            &path,
            r#"
(kicad_sch
  (lib_symbols
    (symbol "Device:R"
      (pin passive line (at -2.54 0 0) (length 2.54) (number "1"))
      (pin passive line (at 2.54 0 180) (length 2.54) (number "2"))))
  (symbol (lib_id "Device:R") (at 10 10 0)
    (property "Reference" "R1") (property "Value" "10k")
    (pin "1") (pin "2"))
  (wire (pts (xy 7.46 10) (xy 7.46 12)))
  (label "NET_A" (at 7.46 12 0))
  (no_connect (at 12.54 10)))
"#,
        )
        .unwrap();
        let parsed = parse_kicad_schematic(&path).unwrap();
        assert_eq!(parsed.components.len(), 1);
        assert_eq!(parsed.nets.len(), 1);
        assert!(parsed.nets.iter().any(|net| net.name == "NET_A"));
    }
}
