mod rows;

use anyhow::{Context, Result, bail};
use rows::{
    AppliedField, ManufacturingField, ParsedMetadata, RowManifest, normalize_rows,
    normalized_yaml_value, parse_metadata_csv,
};
use serde::Serialize;
use serde_yaml_ng::{Mapping, Value};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct ManufacturingMetadataImportOptions {
    pub project: PathBuf,
    pub metadata: PathBuf,
    pub output: PathBuf,
    pub manifest: PathBuf,
    pub source: Option<String>,
    pub allow_unknown_fields: bool,
}

#[derive(Debug, Clone, Default)]
pub struct ManufacturingMetadataImportSummary {
    pub rows: usize,
    pub applied_fields: usize,
    pub skipped_rows: usize,
}

#[derive(Debug, Serialize)]
struct ImportManifest {
    schema_version: String,
    sources: SourceManifest,
    import: ImportSummaryManifest,
    rows: Vec<RowManifest>,
}

#[derive(Debug, Serialize)]
struct SourceManifest {
    project: SourceFileManifest,
    metadata: SourceCsvManifest,
}

#[derive(Debug, Serialize)]
struct SourceFileManifest {
    path: String,
    size_bytes: u64,
    sha256: String,
}

#[derive(Debug, Serialize)]
struct SourceCsvManifest {
    path: String,
    size_bytes: u64,
    sha256: String,
    columns: Vec<String>,
    data_rows: usize,
}

#[derive(Debug, Serialize)]
struct ImportSummaryManifest {
    applied_fields: usize,
    skipped_rows: usize,
    allow_unknown_fields: bool,
    source_label: String,
}

pub fn import_manufacturing_metadata(
    options: &ManufacturingMetadataImportOptions,
) -> Result<ManufacturingMetadataImportSummary> {
    let parsed = parse_metadata_csv(&options.metadata)?;
    let text = fs::read_to_string(&options.project).with_context(|| {
        format!(
            "Failed to read Board IR project {}",
            options.project.display()
        )
    })?;
    let mut project_yaml: Value = serde_yaml_ng::from_str(&text).with_context(|| {
        format!(
            "Failed to parse Board IR project YAML {}",
            options.project.display()
        )
    })?;

    let (applied, row_manifests, skipped_rows) = normalize_rows(&parsed, options)?;
    if applied.is_empty() {
        bail!(
            "Manufacturing metadata import found no supported fields in {}.",
            options.metadata.display()
        );
    }
    apply_metadata(&mut project_yaml, &applied, source_label(options, &applied))?;
    absolutize_relative_libraries(
        &mut project_yaml,
        options
            .project
            .parent()
            .unwrap_or_else(|| std::path::Path::new(".")),
    )?;

    if let Some(parent) = options.output.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create manufacturing metadata import output directory {}",
                parent.display()
            )
        })?;
    }
    let mut yaml = serde_yaml_ng::to_string(&project_yaml)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI from reviewed board/order manufacturing metadata CSV evidence.\n",
    );
    fs::write(&options.output, yaml).with_context(|| {
        format!(
            "Failed to write manufacturing metadata import project {}",
            options.output.display()
        )
    })?;

    let manifest = ImportManifest {
        schema_version: "0.29.0".to_string(),
        sources: SourceManifest {
            project: source_file_manifest(&options.project)?,
            metadata: source_csv_manifest(&options.metadata, &parsed)?,
        },
        import: ImportSummaryManifest {
            applied_fields: applied.len(),
            skipped_rows,
            allow_unknown_fields: options.allow_unknown_fields,
            source_label: source_label(options, &applied).to_string(),
        },
        rows: row_manifests,
    };
    if let Some(parent) = options.manifest.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "Failed to create manufacturing metadata manifest output directory {}",
                parent.display()
            )
        })?;
    }
    fs::write(
        &options.manifest,
        serde_json::to_string_pretty(&manifest)?.as_bytes(),
    )
    .with_context(|| {
        format!(
            "Failed to write manufacturing metadata manifest {}",
            options.manifest.display()
        )
    })?;

    Ok(ManufacturingMetadataImportSummary {
        rows: parsed.data_rows,
        applied_fields: applied.len(),
        skipped_rows,
    })
}

fn apply_metadata(
    project_yaml: &mut Value,
    fields: &[AppliedField],
    source_label: &str,
) -> Result<()> {
    let root = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    let board = ensure_mapping_field_mut(root, "board")?;
    let mut wrote_manufacturing = false;
    for field in fields {
        if field.field == ManufacturingField::ControlledImpedanceCouponSample
            || field.field == ManufacturingField::ControlledImpedanceSolverSample
            || field.field == ManufacturingField::ControlledImpedanceSolverMaterialCorner
        {
            continue;
        }
        if field.field == ManufacturingField::ControlledImpedanceNet {
            let target = field
                .controlled_impedance_net
                .as_ref()
                .context("controlled_impedance_net field must have target value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let targets = ensure_sequence_field_mut(controlled_impedance, "nets")?;
            upsert_controlled_impedance_net_value(targets, &target.net, value)?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedancePair {
            let target = field
                .controlled_impedance_pair
                .as_ref()
                .context("controlled_impedance_pair field must have target value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let targets = ensure_sequence_field_mut(controlled_impedance, "differential_pairs")?;
            upsert_controlled_impedance_pair_value(
                targets,
                &target.first_net,
                &target.second_net,
                value,
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedanceCoupon {
            let coupon = field
                .controlled_impedance_coupon
                .as_ref()
                .context("controlled_impedance_coupon field must have coupon value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let coupons = ensure_sequence_field_mut(controlled_impedance, "coupons")?;
            upsert_named_sequence_value(
                coupons,
                &coupon.name,
                value,
                "controlled_impedance.coupons",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedanceSolverResult {
            let result = field
                .controlled_impedance_solver_result
                .as_ref()
                .context("controlled_impedance_solver_result field must have result value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let results = ensure_sequence_field_mut(controlled_impedance, "solver_results")?;
            upsert_named_sequence_value(
                results,
                &result.name,
                value,
                "controlled_impedance.solver_results",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedanceSolverMaterialLibrary {
            let library = field
                .controlled_impedance_solver_material_library
                .as_ref()
                .context(
                    "controlled_impedance_solver_material_library field must have library value",
                )?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let libraries =
                ensure_sequence_field_mut(controlled_impedance, "solver_material_libraries")?;
            upsert_named_sequence_value(
                libraries,
                &library.name,
                value,
                "controlled_impedance.solver_material_libraries",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedanceSolverMaterialAcceptance {
            let acceptance = field
                .controlled_impedance_solver_material_acceptance
                .as_ref()
                .context(
                    "controlled_impedance_solver_material_acceptance field must have acceptance value",
                )?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let acceptances =
                ensure_sequence_field_mut(controlled_impedance, "solver_material_acceptances")?;
            upsert_named_sequence_value(
                acceptances,
                &acceptance.name,
                value,
                "controlled_impedance.solver_material_acceptances",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ControlledImpedanceSolverQualification {
            let qualification = field
                .controlled_impedance_solver_qualification
                .as_ref()
                .context(
                    "controlled_impedance_solver_qualification field must have qualification value",
                )?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let controlled_impedance =
                ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
            let qualifications =
                ensure_sequence_field_mut(controlled_impedance, "solver_qualifications")?;
            upsert_named_sequence_value(
                qualifications,
                &qualification.name,
                value,
                "controlled_impedance.solver_qualifications",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ThermalCopper {
            let rule = field
                .thermal_copper
                .as_ref()
                .context("thermal_copper field must have thermal copper value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let rules = ensure_sequence_field_mut(manufacturing, "thermal_copper")?;
            upsert_named_sequence_value(rules, &rule.name, value, "thermal_copper")?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ThermalMeasurement {
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let measurements = ensure_sequence_field_mut(manufacturing, "thermal_measurements")?;
            measurements.push(normalized_yaml_value(field)?);
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ThermalPackage {
            let package = field
                .thermal_package
                .as_ref()
                .context("thermal_package field must have thermal package value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let packages = ensure_sequence_field_mut(manufacturing, "thermal_packages")?;
            upsert_component_sequence_value(
                packages,
                &package.component,
                value,
                "thermal_packages",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ThermalEnvironment {
            let environment = field
                .thermal_environment
                .as_ref()
                .context("thermal_environment field must have thermal environment value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let environments = ensure_sequence_field_mut(manufacturing, "thermal_environments")?;
            upsert_named_sequence_value(
                environments,
                &environment.name,
                value,
                "thermal_environments",
            )?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::ThermalLimit {
            let limit = field
                .thermal_limit
                .as_ref()
                .context("thermal_limit field must have thermal limit value")?;
            let value = normalized_yaml_value(field)?;
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            let limits = ensure_sequence_field_mut(manufacturing, "thermal_limits")?;
            upsert_named_sequence_value(limits, &limit.name, value, "thermal_limits")?;
            wrote_manufacturing = true;
        } else if field.field == ManufacturingField::StackupLayer {
            let layer = field
                .stackup_layer
                .as_ref()
                .context("stackup_layer field must have stackup layer value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let stackup = ensure_mapping_field_mut(layout, "stackup")?;
            let layers = ensure_sequence_field_mut(stackup, "layers")?;
            upsert_named_sequence_value(layers, &layer.name, value, "layout.stackup.layers")?;
        } else if field.field == ManufacturingField::RfAntennaKeepout {
            let keepout = field
                .rf_antenna_keepout
                .as_ref()
                .context("rf_antenna_keepout field must have keepout value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let keepouts = ensure_sequence_field_mut(rf_antenna, "keepouts")?;
            upsert_named_sequence_value(
                keepouts,
                &keepout.name,
                value,
                "layout.constraints.rf_antenna.keepouts",
            )?;
        } else if field.field == ManufacturingField::RfAntennaFeedPath {
            let feed_path = field
                .rf_antenna_feed_path
                .as_ref()
                .context("rf_antenna_feed_path field must have feed path value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let feed_paths = ensure_sequence_field_mut(rf_antenna, "feed_paths")?;
            upsert_named_sequence_value(
                feed_paths,
                &feed_path.name,
                value,
                "layout.constraints.rf_antenna.feed_paths",
            )?;
        } else if field.field == ManufacturingField::RfAntennaMatchingNetwork {
            let network = field
                .rf_antenna_matching_network
                .as_ref()
                .context("rf_antenna_matching_network field must have matching network value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let matching_networks = ensure_sequence_field_mut(rf_antenna, "matching_networks")?;
            upsert_named_sequence_value(
                matching_networks,
                &network.name,
                value,
                "layout.constraints.rf_antenna.matching_networks",
            )?;
        } else if field.field == ManufacturingField::RfAntennaMeasurement {
            let measurement = field
                .rf_antenna_measurement
                .as_ref()
                .context("rf_antenna_measurement field must have measurement value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let measurements = ensure_sequence_field_mut(rf_antenna, "measurements")?;
            upsert_named_sequence_value(
                measurements,
                &measurement.name,
                value,
                "layout.constraints.rf_antenna.measurements",
            )?;
        } else if field.field == ManufacturingField::RfAntennaPerformanceLimit {
            let limit = field
                .rf_antenna_performance_limit
                .as_ref()
                .context("rf_antenna_performance_limit field must have limit value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let performance_limits = ensure_sequence_field_mut(rf_antenna, "performance_limits")?;
            upsert_named_sequence_value(
                performance_limits,
                &limit.name,
                value,
                "layout.constraints.rf_antenna.performance_limits",
            )?;
        } else if field.field == ManufacturingField::RfAntennaMeasurementCondition {
            let condition = field
                .rf_antenna_measurement_condition
                .as_ref()
                .context("rf_antenna_measurement_condition field must have condition value")?;
            let value = normalized_yaml_value(field)?;
            let layout = ensure_mapping_field_mut(board, "layout")?;
            let constraints = ensure_mapping_field_mut(layout, "constraints")?;
            let rf_antenna = ensure_mapping_field_mut(constraints, "rf_antenna")?;
            let conditions = ensure_sequence_field_mut(rf_antenna, "measurement_conditions")?;
            upsert_named_sequence_value(
                conditions,
                &condition.name,
                value,
                "layout.constraints.rf_antenna.measurement_conditions",
            )?;
        } else {
            let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
            manufacturing.insert(
                Value::String(field.field.board_key().to_string()),
                normalized_yaml_value(field)?,
            );
            wrote_manufacturing = true;
        }
    }
    for field in fields
        .iter()
        .filter(|field| field.field == ManufacturingField::ControlledImpedanceCouponSample)
    {
        let sample = field
            .controlled_impedance_coupon_sample
            .as_ref()
            .context("controlled_impedance_coupon_sample field must have sample value")?;
        let value = normalized_yaml_value(field)?;
        let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
        let controlled_impedance = ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
        let coupons = ensure_sequence_field_mut(controlled_impedance, "coupons")?;
        upsert_controlled_impedance_coupon_sample_value(
            coupons,
            &sample.coupon_name,
            &sample.name,
            value,
        )?;
        wrote_manufacturing = true;
    }
    for field in fields
        .iter()
        .filter(|field| field.field == ManufacturingField::ControlledImpedanceSolverSample)
    {
        let sample = field
            .controlled_impedance_solver_sample
            .as_ref()
            .context("controlled_impedance_solver_sample field must have sample value")?;
        let value = normalized_yaml_value(field)?;
        let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
        let controlled_impedance = ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
        let results = ensure_sequence_field_mut(controlled_impedance, "solver_results")?;
        upsert_controlled_impedance_solver_sample_value(
            results,
            &sample.solver_result_name,
            &sample.name,
            value,
        )?;
        wrote_manufacturing = true;
    }
    for field in fields
        .iter()
        .filter(|field| field.field == ManufacturingField::ControlledImpedanceSolverMaterialCorner)
    {
        let corner = field
            .controlled_impedance_solver_material_corner
            .as_ref()
            .context("controlled_impedance_solver_material_corner field must have corner value")?;
        let value = normalized_yaml_value(field)?;
        let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
        let controlled_impedance = ensure_mapping_field_mut(manufacturing, "controlled_impedance")?;
        let results = ensure_sequence_field_mut(controlled_impedance, "solver_results")?;
        upsert_controlled_impedance_solver_material_corner_value(
            results,
            &corner.solver_result_name,
            &corner.name,
            value,
        )?;
        wrote_manufacturing = true;
    }
    if wrote_manufacturing {
        let manufacturing = ensure_mapping_field_mut(board, "manufacturing")?;
        manufacturing.insert(
            Value::String("source".to_string()),
            Value::String(source_label.to_string()),
        );
    }
    Ok(())
}

fn source_label<'a>(
    options: &'a ManufacturingMetadataImportOptions,
    fields: &'a [AppliedField],
) -> &'a str {
    options
        .source
        .as_deref()
        .or_else(|| {
            fields
                .iter()
                .find(|field| field.field == ManufacturingField::Source)
                .and_then(|field| field.string_value.as_deref())
        })
        .unwrap_or("manufacturing_metadata_csv")
}

fn upsert_controlled_impedance_net_value(
    sequence: &mut Vec<Value>,
    net: &str,
    value: Value,
) -> Result<()> {
    let mut matched_index = None;
    for (index, item) in sequence.iter().enumerate() {
        if yaml_mapping_string(item, "net") == Some(net) {
            if matched_index.is_some() {
                bail!(
                    "Board IR field controlled_impedance.nets has duplicate existing net {net}; refusing to update ambiguous target."
                );
            }
            matched_index = Some(index);
        }
    }
    if let Some(index) = matched_index {
        sequence[index] = value;
    } else {
        sequence.push(value);
    }
    Ok(())
}

fn upsert_controlled_impedance_pair_value(
    sequence: &mut Vec<Value>,
    first_net: &str,
    second_net: &str,
    value: Value,
) -> Result<()> {
    let target_key = ordered_pair_key(first_net, second_net);
    let mut matched_index = None;
    for (index, item) in sequence.iter().enumerate() {
        let Some(existing_first) = yaml_mapping_string(item, "first_net") else {
            continue;
        };
        let Some(existing_second) = yaml_mapping_string(item, "second_net") else {
            continue;
        };
        if ordered_pair_key(existing_first, existing_second) == target_key {
            if matched_index.is_some() {
                bail!(
                    "Board IR field controlled_impedance.differential_pairs has duplicate existing pair {target_key}; refusing to update ambiguous target."
                );
            }
            matched_index = Some(index);
        }
    }
    if let Some(index) = matched_index {
        sequence[index] = value;
    } else {
        sequence.push(value);
    }
    Ok(())
}

fn upsert_named_sequence_value(
    sequence: &mut Vec<Value>,
    name: &str,
    value: Value,
    field_name: &str,
) -> Result<()> {
    let mut matched_index = None;
    for (index, item) in sequence.iter().enumerate() {
        if yaml_mapping_name(item) == Some(name) {
            if matched_index.is_some() {
                bail!(
                    "Board IR field {field_name} has duplicate existing name {name}; refusing to update ambiguous target."
                );
            }
            matched_index = Some(index);
        }
    }
    if let Some(index) = matched_index {
        sequence[index] = value;
    } else {
        sequence.push(value);
    }
    Ok(())
}

fn upsert_controlled_impedance_coupon_sample_value(
    coupons: &mut [Value],
    coupon_name: &str,
    sample_name: &str,
    value: Value,
) -> Result<()> {
    let mut matched_coupon_index = None;
    for (index, coupon) in coupons.iter().enumerate() {
        if yaml_mapping_name(coupon) == Some(coupon_name) {
            if matched_coupon_index.is_some() {
                bail!(
                    "Board IR field controlled_impedance.coupons has duplicate existing name {coupon_name}; refusing to update ambiguous coupon sample."
                );
            }
            matched_coupon_index = Some(index);
        }
    }
    let Some(index) = matched_coupon_index else {
        bail!(
            "Board IR field controlled_impedance.coupons has no coupon named {coupon_name}; refusing to attach coupon sample {sample_name}."
        );
    };
    let mapping = coupons[index].as_mapping_mut().with_context(|| {
        format!("Board IR field controlled_impedance.coupons item {coupon_name} must be an object.")
    })?;
    let samples = ensure_sequence_field_mut(mapping, "samples")?;
    upsert_named_sequence_value(
        samples,
        sample_name,
        value,
        "controlled_impedance.coupons[].samples",
    )
}

fn upsert_controlled_impedance_solver_sample_value(
    results: &mut [Value],
    result_name: &str,
    sample_name: &str,
    value: Value,
) -> Result<()> {
    let mut matched_result_index = None;
    for (index, result) in results.iter().enumerate() {
        if yaml_mapping_name(result) == Some(result_name) {
            if matched_result_index.is_some() {
                bail!(
                    "Board IR field controlled_impedance.solver_results has duplicate existing name {result_name}; refusing to update ambiguous solver sample."
                );
            }
            matched_result_index = Some(index);
        }
    }
    let Some(index) = matched_result_index else {
        bail!(
            "Board IR field controlled_impedance.solver_results has no result named {result_name}; refusing to attach solver sample {sample_name}."
        );
    };
    let mapping = results[index].as_mapping_mut().with_context(|| {
        format!(
            "Board IR field controlled_impedance.solver_results item {result_name} must be an object."
        )
    })?;
    let samples = ensure_sequence_field_mut(mapping, "samples")?;
    upsert_named_sequence_value(
        samples,
        sample_name,
        value,
        "controlled_impedance.solver_results[].samples",
    )
}

fn upsert_controlled_impedance_solver_material_corner_value(
    results: &mut [Value],
    result_name: &str,
    corner_name: &str,
    value: Value,
) -> Result<()> {
    let mut matched_result_index = None;
    for (index, result) in results.iter().enumerate() {
        if yaml_mapping_name(result) == Some(result_name) {
            if matched_result_index.is_some() {
                bail!(
                    "Board IR field controlled_impedance.solver_results has duplicate existing name {result_name}; refusing to update ambiguous solver material corner."
                );
            }
            matched_result_index = Some(index);
        }
    }
    let Some(index) = matched_result_index else {
        bail!(
            "Board IR field controlled_impedance.solver_results has no result named {result_name}; refusing to attach solver material corner {corner_name}."
        );
    };
    let mapping = results[index].as_mapping_mut().with_context(|| {
        format!(
            "Board IR field controlled_impedance.solver_results item {result_name} must be an object."
        )
    })?;
    let material_corners = ensure_sequence_field_mut(mapping, "material_corners")?;
    upsert_named_sequence_value(
        material_corners,
        corner_name,
        value,
        "controlled_impedance.solver_results[].material_corners",
    )
}

fn upsert_component_sequence_value(
    sequence: &mut Vec<Value>,
    component: &str,
    value: Value,
    field_name: &str,
) -> Result<()> {
    let mut matched_index = None;
    for (index, item) in sequence.iter().enumerate() {
        if yaml_mapping_string(item, "component") == Some(component) {
            if matched_index.is_some() {
                bail!(
                    "Board IR field {field_name} has duplicate existing component {component}; refusing to update ambiguous target."
                );
            }
            matched_index = Some(index);
        }
    }
    if let Some(index) = matched_index {
        sequence[index] = value;
    } else {
        sequence.push(value);
    }
    Ok(())
}

fn yaml_mapping_name(value: &Value) -> Option<&str> {
    yaml_mapping_string(value, "name")
}

fn yaml_mapping_string<'a>(value: &'a Value, key: &str) -> Option<&'a str> {
    value
        .as_mapping()?
        .get(Value::String(key.to_string()))?
        .as_str()
}

fn ordered_pair_key(first: &str, second: &str) -> String {
    if first <= second {
        format!("{first}/{second}")
    } else {
        format!("{second}/{first}")
    }
}

fn source_file_manifest(path: &Path) -> Result<SourceFileManifest> {
    Ok(SourceFileManifest {
        path: path.display().to_string(),
        size_bytes: fs::metadata(path)
            .with_context(|| format!("Failed to stat {}", path.display()))?
            .len(),
        sha256: file_sha256_hex(path)?,
    })
}

fn source_csv_manifest(path: &Path, parsed: &ParsedMetadata) -> Result<SourceCsvManifest> {
    Ok(SourceCsvManifest {
        path: path.display().to_string(),
        size_bytes: fs::metadata(path)
            .with_context(|| format!("Failed to stat {}", path.display()))?
            .len(),
        sha256: file_sha256_hex(path)?,
        columns: parsed.headers.clone(),
        data_rows: parsed.data_rows,
    })
}

fn file_sha256_hex(path: &Path) -> Result<String> {
    let bytes = fs::read(path).with_context(|| format!("Failed to hash {}", path.display()))?;
    Ok(sha256_hex(&bytes))
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn ensure_mapping_field_mut<'a>(mapping: &'a mut Mapping, key: &str) -> Result<&'a mut Mapping> {
    let key_value = Value::String(key.to_string());
    if !mapping.contains_key(&key_value) {
        mapping.insert(key_value.clone(), Value::Mapping(Mapping::new()));
    }
    mapping
        .get_mut(&key_value)
        .expect("field was inserted when absent")
        .as_mapping_mut()
        .with_context(|| format!("Board IR field {key} must be an object."))
}

fn ensure_sequence_field_mut<'a>(
    mapping: &'a mut Mapping,
    key: &str,
) -> Result<&'a mut Vec<Value>> {
    let key_value = Value::String(key.to_string());
    if !mapping.contains_key(&key_value) {
        mapping.insert(key_value.clone(), Value::Sequence(Vec::new()));
    }
    mapping
        .get_mut(&key_value)
        .expect("field was inserted when absent")
        .as_sequence_mut()
        .with_context(|| format!("Board IR field {key} must be a list."))
}

fn absolutize_relative_libraries(project_yaml: &mut Value, project_dir: &Path) -> Result<()> {
    let mapping = project_yaml
        .as_mapping_mut()
        .context("Board IR project must be a YAML object.")?;
    let Some(libraries) = mapping.get_mut(Value::String("libraries".to_string())) else {
        return Ok(());
    };
    let libraries = libraries
        .as_sequence_mut()
        .context("Board IR field libraries must be a list.")?;
    for library in libraries {
        let Some(path_text) = library.as_str() else {
            bail!("Board IR libraries entries must be strings.");
        };
        let path = Path::new(path_text);
        if path.is_absolute() {
            continue;
        }
        let resolved = normalize_path(&project_dir.join(path));
        let absolute = fs::canonicalize(&resolved).unwrap_or(resolved);
        *library = Value::String(absolute.to_string_lossy().to_string());
    }
    Ok(())
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    normalized
}
