use anyhow::{Context, Result, bail};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct SpiceImportOptions {
    pub input: PathBuf,
    pub output: PathBuf,
    pub name: String,
    pub backend: String,
    pub stop_time_us: f64,
    pub max_step_us: f64,
}

#[derive(Debug)]
struct ParsedDeck {
    elements: Vec<ParsedElement>,
    includes: Vec<IncludeFile>,
    nodes: BTreeSet<String>,
    tran: Option<TranSpec>,
}

#[derive(Debug)]
struct ParsedElement {
    name: String,
    model: String,
    pins: Vec<(String, String)>,
    spice: Option<SpicePrimitiveSpec>,
}

#[derive(Debug)]
struct IncludeFile {
    path: String,
    resolved: Option<PathBuf>,
}

#[derive(Debug)]
struct TranSpec {
    stop_time_us: f64,
    max_step_us: f64,
}

#[derive(Debug)]
enum SpicePrimitiveSpec {
    Resistor { value_ohm: f64 },
    Capacitor { value_f: f64 },
    DcVoltageSource { dc_v: f64 },
    PulseVoltageSource { pulse: PulseSpec },
}

#[derive(Debug, Serialize)]
struct ProjectYaml {
    project: ProjectMetaYaml,
    libraries: Vec<String>,
    board: BoardYaml,
    scenarios: Vec<ScenarioYaml>,
}

#[derive(Debug, Serialize)]
struct ProjectMetaYaml {
    name: String,
    version: String,
}

#[derive(Debug, Serialize)]
struct BoardYaml {
    components: BTreeMap<String, ComponentYaml>,
    nets: BTreeMap<String, NetYaml>,
}

#[derive(Debug, Serialize)]
struct ComponentYaml {
    model: String,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    pins: BTreeMap<String, String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    spice: Option<ComponentSpiceYaml>,
}

#[derive(Debug, Serialize)]
struct ComponentSpiceYaml {
    primitive: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    value_ohm: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    value_f: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    dc_v: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pulse: Option<PulseSpec>,
}

#[derive(Debug, Serialize)]
struct PulseSpec {
    initial_v: f64,
    pulsed_v: f64,
    delay_us: f64,
    rise_us: f64,
    fall_us: f64,
    width_us: f64,
    period_us: f64,
}

#[derive(Debug, Serialize)]
struct NetYaml {
    kind: String,
}

#[derive(Debug, Serialize)]
struct ScenarioYaml {
    name: String,
    #[serde(rename = "type")]
    scenario_type: String,
    checks: Vec<String>,
    analog: AnalogYaml,
}

#[derive(Debug, Serialize)]
struct AnalogYaml {
    backend: String,
    netlist_source: String,
    netlist: String,
    model_files: Vec<ModelFileYaml>,
    node_bindings: Vec<NodeBindingYaml>,
    pin_bindings: Vec<PinBindingYaml>,
    analysis: AnalysisYaml,
    stimuli: Vec<StimulusYaml>,
    probes: Vec<ProbeYaml>,
    assertions: Vec<AssertionYaml>,
}

#[derive(Debug, Serialize)]
struct ModelFileYaml {
    path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    sha256: Option<String>,
}

#[derive(Debug, Serialize)]
struct NodeBindingYaml {
    node: String,
    net: String,
}

#[derive(Debug, Serialize)]
struct PinBindingYaml {
    node: String,
    endpoint: EndpointYaml,
}

#[derive(Debug, Serialize)]
struct EndpointYaml {
    component: String,
    pin: String,
}

#[derive(Debug, Serialize)]
struct AnalysisYaml {
    #[serde(rename = "type")]
    analysis_type: String,
    stop_time_us: f64,
    max_step_us: f64,
}

#[derive(Debug, Serialize)]
struct StimulusYaml {
    name: String,
    description: String,
}

#[derive(Debug, Serialize)]
struct ProbeYaml {
    name: String,
    expression: String,
}

#[derive(Debug, Serialize)]
struct AssertionYaml {}

pub fn import_spice(options: &SpiceImportOptions) -> Result<()> {
    let deck = parse_spice_deck(&options.input)?;
    let output_dir = options.output.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(output_dir).with_context(|| {
        format!(
            "Failed to create import output directory {}",
            output_dir.display()
        )
    })?;
    let project = build_project_yaml(options, &deck, output_dir)?;
    let mut yaml = serde_yaml_ng::to_string(&project)?;
    yaml.insert_str(
        0,
        "# Generated by CircuitCI from a SPICE deck. Review probes/assertions before sign-off.\n",
    );
    fs::write(&options.output, yaml)
        .with_context(|| format!("Failed to write {}", options.output.display()))?;
    Ok(())
}

fn parse_spice_deck(path: &Path) -> Result<ParsedDeck> {
    let text = fs::read_to_string(path)
        .with_context(|| format!("Failed to read SPICE deck {}", path.display()))?;
    let logical_lines = logical_lines(&text)?;
    let source_dir = path.parent().unwrap_or_else(|| Path::new("."));
    let mut elements = Vec::new();
    let mut includes = Vec::new();
    let mut nodes = BTreeSet::new();
    let mut tran = None;
    for line in logical_lines {
        let tokens = tokenize(&line);
        if tokens.is_empty() {
            continue;
        }
        let first = tokens[0].as_str();
        if first.starts_with('.') {
            let directive = first.to_ascii_lowercase();
            match directive.as_str() {
                ".include" | ".lib" => includes.push(parse_include(&tokens, source_dir)?),
                ".tran" => tran = parse_tran(&tokens).or(tran),
                ".control" | ".endc" => {
                    bail!("SPICE control blocks are not supported by import-spice: {line}")
                }
                _ => {}
            }
            continue;
        }
        let element = parse_element(&tokens, &line)?;
        for (_, node) in &element.pins {
            nodes.insert(node.clone());
        }
        elements.push(element);
    }
    if elements.is_empty() {
        bail!(
            "SPICE deck {} contains no importable elements.",
            path.display()
        );
    }
    Ok(ParsedDeck {
        elements,
        includes,
        nodes,
        tran,
    })
}

fn logical_lines(text: &str) -> Result<Vec<String>> {
    let mut lines: Vec<String> = Vec::new();
    for (index, raw) in text.lines().enumerate() {
        let trimmed = strip_inline_comment(raw).trim();
        if trimmed.is_empty() || trimmed.starts_with('*') || trimmed.starts_with(';') {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix('+') {
            let Some(previous) = lines.last_mut() else {
                bail!(
                    "Continuation line {} has no preceding SPICE card.",
                    index + 1
                );
            };
            previous.push(' ');
            previous.push_str(rest.trim());
        } else {
            lines.push(trimmed.to_string());
        }
    }
    Ok(lines)
}

fn strip_inline_comment(line: &str) -> &str {
    line.split_once('$').map_or(line, |(before, _)| before)
}

fn tokenize(line: &str) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut quote: Option<char> = None;
    for character in line.chars() {
        if let Some(mark) = quote {
            if character == mark {
                quote = None;
            } else {
                current.push(character);
            }
            continue;
        }
        if matches!(character, '"' | '\'') {
            quote = Some(character);
            continue;
        }
        if character.is_whitespace() {
            if !current.is_empty() {
                tokens.push(std::mem::take(&mut current));
            }
        } else {
            current.push(character);
        }
    }
    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

fn parse_include(tokens: &[String], source_dir: &Path) -> Result<IncludeFile> {
    if tokens.len() < 2 {
        bail!("{} directive requires a path.", tokens[0]);
    }
    let path = tokens[1].clone();
    let candidate = Path::new(&path);
    let resolved = if candidate.is_absolute() {
        candidate.is_file().then(|| candidate.to_path_buf())
    } else {
        let joined = source_dir.join(candidate);
        joined.is_file().then_some(joined)
    };
    Ok(IncludeFile { path, resolved })
}

fn parse_tran(tokens: &[String]) -> Option<TranSpec> {
    if tokens.len() < 3 {
        return None;
    }
    let max_step_us = parse_spice_number(&tokens[1]).map(|value| value * 1_000_000.0)?;
    let stop_time_us = parse_spice_number(&tokens[2]).map(|value| value * 1_000_000.0)?;
    Some(TranSpec {
        stop_time_us,
        max_step_us,
    })
}

fn parse_element(tokens: &[String], line: &str) -> Result<ParsedElement> {
    let name = tokens[0].clone();
    validate_refdes(&name)?;
    let prefix = name
        .chars()
        .next()
        .expect("tokenized element name is not empty")
        .to_ascii_uppercase();
    match prefix {
        'R' => parse_two_terminal(tokens, "generic.analog.resistor", |value| {
            SpicePrimitiveSpec::Resistor { value_ohm: value }
        }),
        'C' => parse_two_terminal(tokens, "generic.analog.capacitor", |value| {
            SpicePrimitiveSpec::Capacitor { value_f: value }
        }),
        'V' => parse_voltage_source(tokens),
        'D' => parse_fixed_pins(
            tokens,
            3,
            &["A", "K"],
            "generic.analog.imported_spice_device",
        ),
        'Q' => {
            if tokens.len() >= 5 {
                let pin_names = if tokens.len() >= 6 {
                    vec!["C", "B", "E", "S"]
                } else {
                    vec!["C", "B", "E"]
                };
                parse_fixed_pins(
                    tokens,
                    pin_names.len() + 2,
                    &pin_names,
                    "generic.analog.imported_spice_device",
                )
            } else {
                bail!("Malformed BJT element line: {line}")
            }
        }
        'M' => parse_fixed_pins(
            tokens,
            6,
            &["D", "G", "S", "B"],
            "generic.analog.imported_spice_device",
        ),
        'X' => parse_subckt(tokens, line),
        _ if tokens.len() >= 4 => parse_fixed_pins(
            tokens,
            4,
            &["A", "B"],
            "generic.analog.imported_spice_device",
        ),
        _ => bail!("Unsupported or malformed SPICE element line: {line}"),
    }
}

fn parse_two_terminal<F>(tokens: &[String], model: &str, primitive: F) -> Result<ParsedElement>
where
    F: FnOnce(f64) -> SpicePrimitiveSpec,
{
    if tokens.len() < 4 {
        bail!(
            "Malformed two-terminal SPICE element line: {}",
            tokens.join(" ")
        );
    }
    let value = parse_spice_number(&tokens[3])
        .with_context(|| format!("Could not parse SPICE value {}", tokens[3]))?;
    Ok(ParsedElement {
        name: tokens[0].clone(),
        model: model.to_string(),
        pins: vec![
            ("A".to_string(), tokens[1].clone()),
            ("B".to_string(), tokens[2].clone()),
        ],
        spice: Some(primitive(value)),
    })
}

fn parse_voltage_source(tokens: &[String]) -> Result<ParsedElement> {
    if tokens.len() < 4 {
        bail!(
            "Malformed voltage-source SPICE element line: {}",
            tokens.join(" ")
        );
    }
    let spec = tokens[3..].join(" ");
    let spice = if spec.trim_start().to_ascii_uppercase().starts_with("PULSE") {
        SpicePrimitiveSpec::PulseVoltageSource {
            pulse: parse_pulse(&spec)?,
        }
    } else {
        let value_token = if tokens[3].eq_ignore_ascii_case("DC") && tokens.len() >= 5 {
            &tokens[4]
        } else {
            &tokens[3]
        };
        SpicePrimitiveSpec::DcVoltageSource {
            dc_v: parse_spice_number(value_token)
                .with_context(|| format!("Could not parse voltage source value {value_token}"))?,
        }
    };
    Ok(ParsedElement {
        name: tokens[0].clone(),
        model: "generic.analog.imported_spice_device".to_string(),
        pins: vec![
            ("P".to_string(), tokens[1].clone()),
            ("N".to_string(), tokens[2].clone()),
        ],
        spice: Some(spice),
    })
}

fn parse_fixed_pins(
    tokens: &[String],
    min_tokens: usize,
    pin_names: &[&str],
    model: &str,
) -> Result<ParsedElement> {
    if tokens.len() < min_tokens {
        bail!("Malformed SPICE element line: {}", tokens.join(" "));
    }
    Ok(ParsedElement {
        name: tokens[0].clone(),
        model: model.to_string(),
        pins: pin_names
            .iter()
            .enumerate()
            .map(|(index, pin)| ((*pin).to_string(), tokens[index + 1].clone()))
            .collect(),
        spice: None,
    })
}

fn parse_subckt(tokens: &[String], line: &str) -> Result<ParsedElement> {
    if tokens.len() < 4 {
        bail!("Malformed subcircuit instance line: {line}");
    }
    let node_count = tokens.len() - 2;
    Ok(ParsedElement {
        name: tokens[0].clone(),
        model: "generic.analog.imported_spice_device".to_string(),
        pins: (0..node_count)
            .map(|index| (format!("P{}", index + 1), tokens[index + 1].clone()))
            .collect(),
        spice: None,
    })
}

fn parse_pulse(spec: &str) -> Result<PulseSpec> {
    let start = spec.find('(').context("PULSE source is missing '('")?;
    let end = spec.rfind(')').context("PULSE source is missing ')'")?;
    let values: Vec<_> = spec[start + 1..end]
        .split(|character: char| character == ',' || character.is_whitespace())
        .filter(|field| !field.is_empty())
        .map(parse_spice_number)
        .collect::<Option<Vec<_>>>()
        .context("PULSE source contains an unparseable numeric value")?;
    if values.len() < 7 {
        bail!("PULSE source requires at least seven values.");
    }
    Ok(PulseSpec {
        initial_v: values[0],
        pulsed_v: values[1],
        delay_us: values[2] * 1_000_000.0,
        rise_us: values[3] * 1_000_000.0,
        fall_us: values[4] * 1_000_000.0,
        width_us: values[5] * 1_000_000.0,
        period_us: values[6] * 1_000_000.0,
    })
}

fn validate_refdes(name: &str) -> Result<()> {
    if name.is_empty()
        || !name.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '_' | '-' | '.')
        })
    {
        bail!("SPICE element name {name:?} cannot be represented as a Board IR component id.");
    }
    Ok(())
}

fn parse_spice_number(token: &str) -> Option<f64> {
    let upper = token.trim().to_ascii_uppercase();
    for (suffix, scale) in [
        ("MEG", 1e6),
        ("T", 1e12),
        ("G", 1e9),
        ("K", 1e3),
        ("M", 1e-3),
        ("U", 1e-6),
        ("N", 1e-9),
        ("P", 1e-12),
        ("F", 1e-15),
    ] {
        if let Some(number) = upper.strip_suffix(suffix) {
            return number.parse::<f64>().ok().map(|value| value * scale);
        }
    }
    upper.parse::<f64>().ok()
}

fn build_project_yaml(
    options: &SpiceImportOptions,
    deck: &ParsedDeck,
    output_dir: &Path,
) -> Result<ProjectYaml> {
    let mut components = BTreeMap::new();
    let mut pin_bindings = Vec::new();
    for element in &deck.elements {
        let mut pins = BTreeMap::new();
        for (pin, node) in &element.pins {
            let net = net_name_for_node(node);
            pins.insert(pin.clone(), net.clone());
            pin_bindings.push(PinBindingYaml {
                node: node.clone(),
                endpoint: EndpointYaml {
                    component: element.name.clone(),
                    pin: pin.clone(),
                },
            });
        }
        components.insert(
            element.name.clone(),
            ComponentYaml {
                model: element.model.clone(),
                pins,
                spice: element.spice.as_ref().map(ComponentSpiceYaml::from),
            },
        );
    }
    let mut nets = BTreeMap::new();
    for node in &deck.nodes {
        let kind = if is_ground_node(node) {
            "ground"
        } else {
            "digital_or_analog"
        };
        nets.insert(
            net_name_for_node(node),
            NetYaml {
                kind: kind.to_string(),
            },
        );
    }
    let node_bindings = deck
        .nodes
        .iter()
        .map(|node| NodeBindingYaml {
            node: node.clone(),
            net: net_name_for_node(node),
        })
        .collect();
    let probes = deck
        .nodes
        .iter()
        .filter(|node| !is_ground_node(node))
        .map(|node| ProbeYaml {
            name: format!("v_{}", sanitize_identifier(node)),
            expression: format!("V({node})"),
        })
        .collect();
    let tran = deck.tran.as_ref();
    Ok(ProjectYaml {
        project: ProjectMetaYaml {
            name: options.name.clone(),
            version: "0.1.0".to_string(),
        },
        libraries: vec![generic_analog_library_path()],
        board: BoardYaml { components, nets },
        scenarios: vec![ScenarioYaml {
            name: "imported_spice_transient".to_string(),
            scenario_type: "analog_transient".to_string(),
            checks: vec!["SPICE_TRANSIENT_ANALYSIS".to_string()],
            analog: AnalogYaml {
                backend: options.backend.clone(),
                netlist_source: "file".to_string(),
                netlist: path_for_yaml(&options.input, output_dir),
                model_files: model_files_for_yaml(&deck.includes, output_dir)?,
                node_bindings,
                pin_bindings,
                analysis: AnalysisYaml {
                    analysis_type: "tran".to_string(),
                    stop_time_us: tran.map_or(options.stop_time_us, |value| value.stop_time_us),
                    max_step_us: tran.map_or(options.max_step_us, |value| value.max_step_us),
                },
                stimuli: vec![StimulusYaml {
                    name: "imported_deck_sources".to_string(),
                    description:
                        "Stimuli are defined by independent sources in the imported SPICE deck."
                            .to_string(),
                }],
                probes,
                assertions: Vec::new(),
            },
        }],
    })
}

impl From<&SpicePrimitiveSpec> for ComponentSpiceYaml {
    fn from(value: &SpicePrimitiveSpec) -> Self {
        match value {
            SpicePrimitiveSpec::Resistor { value_ohm } => Self {
                primitive: "resistor".to_string(),
                value_ohm: Some(*value_ohm),
                value_f: None,
                dc_v: None,
                pulse: None,
            },
            SpicePrimitiveSpec::Capacitor { value_f } => Self {
                primitive: "capacitor".to_string(),
                value_ohm: None,
                value_f: Some(*value_f),
                dc_v: None,
                pulse: None,
            },
            SpicePrimitiveSpec::DcVoltageSource { dc_v } => Self {
                primitive: "dc_voltage_source".to_string(),
                value_ohm: None,
                value_f: None,
                dc_v: Some(*dc_v),
                pulse: None,
            },
            SpicePrimitiveSpec::PulseVoltageSource { pulse } => Self {
                primitive: "pulse_voltage_source".to_string(),
                value_ohm: None,
                value_f: None,
                dc_v: None,
                pulse: Some(PulseSpec {
                    initial_v: pulse.initial_v,
                    pulsed_v: pulse.pulsed_v,
                    delay_us: pulse.delay_us,
                    rise_us: pulse.rise_us,
                    fall_us: pulse.fall_us,
                    width_us: pulse.width_us,
                    period_us: pulse.period_us,
                }),
            },
        }
    }
}

fn model_files_for_yaml(includes: &[IncludeFile], output_dir: &Path) -> Result<Vec<ModelFileYaml>> {
    let mut seen = BTreeSet::new();
    let mut files = Vec::new();
    for include in includes {
        let path = include.resolved.as_ref().map_or_else(
            || include.path.clone(),
            |path| path_for_yaml(path, output_dir),
        );
        if !seen.insert(path.clone()) {
            continue;
        }
        let sha256 = include.resolved.as_ref().map(file_sha256_hex).transpose()?;
        files.push(ModelFileYaml { path, sha256 });
    }
    Ok(files)
}

fn file_sha256_hex(path: &PathBuf) -> Result<String> {
    let bytes = fs::read(path).with_context(|| format!("Failed to read {}", path.display()))?;
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    Ok(format!("{:x}", hasher.finalize()))
}

fn path_for_yaml(path: &Path, output_dir: &Path) -> String {
    if path.is_absolute() {
        return path.to_string_lossy().to_string();
    }
    let candidate = output_dir.join(path);
    if candidate.exists() {
        path.to_string_lossy().to_string()
    } else {
        fs::canonicalize(path)
            .unwrap_or_else(|_| path.to_path_buf())
            .to_string_lossy()
            .to_string()
    }
}

fn generic_analog_library_path() -> String {
    fs::canonicalize("libs/generic/analog")
        .unwrap_or_else(|_| PathBuf::from("libs/generic/analog"))
        .to_string_lossy()
        .to_string()
}

fn net_name_for_node(node: &str) -> String {
    if is_ground_node(node) {
        "gnd".to_string()
    } else {
        format!("net_{}", sanitize_identifier(node))
    }
}

fn is_ground_node(node: &str) -> bool {
    matches!(node.to_ascii_lowercase().as_str(), "0" | "gnd" | "ground")
}

fn sanitize_identifier(value: &str) -> String {
    let mut output = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            output.push(character.to_ascii_lowercase());
        } else {
            output.push('_');
        }
    }
    output.trim_matches('_').to_string()
}

#[cfg(test)]
mod tests {
    use super::{logical_lines, parse_spice_deck, parse_spice_number};

    #[test]
    fn spice_suffix_numbers_parse() {
        assert_eq!(parse_spice_number("10k"), Some(10_000.0));
        assert!((parse_spice_number("100n").unwrap() - 100e-9).abs() < 1e-18);
        assert!((parse_spice_number("1u").unwrap() - 1e-6).abs() < 1e-18);
        assert_eq!(parse_spice_number("2meg"), Some(2e6));
        assert_eq!(parse_spice_number("3.3"), Some(3.3));
    }

    #[test]
    fn continuation_lines_are_joined() {
        let lines = logical_lines("R1 a b\n+ 10k\n").unwrap();
        assert_eq!(lines, vec!["R1 a b 10k"]);
    }

    #[test]
    fn malformed_continuation_fails_closed() {
        assert!(logical_lines("+ orphan\n").is_err());
    }

    #[test]
    fn parser_discovers_basic_elements() {
        let dir = tempfile::tempdir().unwrap();
        let deck = dir.path().join("rc.cir");
        std::fs::write(
            &deck,
            "* test
V1 in 0 DC 3.3
R1 in out 10k
C1 out 0 100n
.tran 1u 10u
.end
",
        )
        .unwrap();
        let parsed = parse_spice_deck(&deck).unwrap();
        assert_eq!(parsed.elements.len(), 3);
        assert!(parsed.nodes.contains("in"));
        assert!(parsed.nodes.contains("out"));
        assert!(parsed.nodes.contains("0"));
        assert_eq!(parsed.tran.unwrap().stop_time_us, 10.0);
    }
}
