use crate::board_ir::Scenario;
use crate::library::BoundBoard;
use std::fs;
use std::path::Path;

use super::analog_runner::{
    ModelSectionOverride, ParameterOverride, rewrite_include_line, sweep_temperature_c,
};
use super::analog_util::{absolute_path, normalize_path};

pub(super) fn build_xyce_transient_wrapper(
    bound: &BoundBoard<'_>,
    scenario: &Scenario,
    netlist: &Path,
    raw_output: &Path,
    parameter_overrides: &[ParameterOverride],
    model_section_overrides: &[ModelSectionOverride],
    operating_probe_expressions: &[String],
) -> Result<String, String> {
    let analog = scenario
        .analog
        .as_ref()
        .expect("analog was validated before Xyce wrapper generation");
    let source = fs::read_to_string(netlist).map_err(|error| {
        format!(
            "Failed to read SPICE netlist {}: {error}",
            netlist.display()
        )
    })?;
    let mut text = String::new();
    text.push_str("* Generated by CircuitCI for Xyce. Do not edit by hand.\n");
    text.push_str("* Source netlist: ");
    text.push_str(&netlist.to_string_lossy());
    text.push('\n');
    let include_base = netlist.parent().unwrap_or(&bound.project.source_dir);
    let mut in_control_block = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        let directive = trimmed.to_ascii_lowercase();
        let first_token = directive.split_whitespace().next().unwrap_or("");
        if first_token == ".control" {
            in_control_block = true;
            continue;
        }
        if in_control_block {
            if first_token == ".endc" {
                in_control_block = false;
            }
            continue;
        }
        if matches!(first_token, ".end" | ".tran" | ".print") {
            continue;
        }
        text.push_str(&rewrite_include_line(line, include_base));
        text.push('\n');
    }
    if !parameter_overrides.is_empty() {
        text.push_str("* CircuitCI sweep parameter overrides.\n");
        for override_ in parameter_overrides {
            text.push_str(".param ");
            text.push_str(&override_.name);
            text.push('=');
            text.push_str(&format!("{:.12e}", override_.value));
            text.push('\n');
        }
        if let Some(temperature_c) = sweep_temperature_c(parameter_overrides) {
            text.push_str(".temp ");
            text.push_str(&format!("{:.12e}", temperature_c));
            text.push('\n');
        }
    }
    if !model_section_overrides.is_empty() {
        text.push_str("* CircuitCI sweep model section overrides.\n");
        for override_ in model_section_overrides {
            let path = Path::new(&override_.path);
            let absolute = if path.is_absolute() {
                normalize_path(path)
            } else {
                absolute_path(&bound.project.source_dir.join(path))
                    .unwrap_or_else(|_| normalize_path(&bound.project.source_dir.join(path)))
            };
            text.push_str(".lib \"");
            text.push_str(&absolute.to_string_lossy());
            text.push_str("\" ");
            text.push_str(&override_.section);
            text.push('\n');
        }
    }
    let step_s = analog.analysis.max_step_us / 1_000_000.0;
    let stop_s = analog.analysis.stop_time_us / 1_000_000.0;
    text.push_str(&format!(".TRAN {:.12e} {:.12e}\n", step_s, stop_s));
    text.push_str(".PRINT TRAN DELIMITER=COMMA FILE=\"");
    text.push_str(&raw_output.to_string_lossy());
    text.push('"');
    for probe in &analog.probes {
        text.push(' ');
        text.push_str(&probe.expression);
    }
    for expression in operating_probe_expressions {
        text.push(' ');
        text.push_str(expression);
    }
    text.push_str("\n.END\n");
    Ok(text)
}

pub(super) fn build_xyce_ac_wrapper(
    bound: &BoundBoard<'_>,
    scenario: &Scenario,
    netlist: &Path,
    raw_output: &Path,
    parameter_overrides: &[ParameterOverride],
    model_section_overrides: &[ModelSectionOverride],
) -> Result<String, String> {
    let analog = scenario
        .analog
        .as_ref()
        .expect("analog was validated before Xyce AC wrapper generation");
    let source = fs::read_to_string(netlist).map_err(|error| {
        format!(
            "Failed to read SPICE netlist {}: {error}",
            netlist.display()
        )
    })?;
    let start_hz = analog.analysis.start_frequency_hz.ok_or_else(|| {
        "analog.analysis.start_frequency_hz is required for AC analysis.".to_string()
    })?;
    let stop_hz = analog.analysis.stop_frequency_hz.ok_or_else(|| {
        "analog.analysis.stop_frequency_hz is required for AC analysis.".to_string()
    })?;
    let points_per_decade = analog.analysis.points_per_decade.unwrap_or(20);
    let mut text = String::new();
    text.push_str("* Generated by CircuitCI for Xyce AC. Do not edit by hand.\n");
    text.push_str("* Source netlist: ");
    text.push_str(&netlist.to_string_lossy());
    text.push('\n');
    let include_base = netlist.parent().unwrap_or(&bound.project.source_dir);
    let mut in_control_block = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        let directive = trimmed.to_ascii_lowercase();
        let first_token = directive.split_whitespace().next().unwrap_or("");
        if first_token == ".control" {
            in_control_block = true;
            continue;
        }
        if in_control_block {
            if first_token == ".endc" {
                in_control_block = false;
            }
            continue;
        }
        if matches!(first_token, ".end" | ".tran" | ".ac" | ".print") {
            continue;
        }
        text.push_str(&rewrite_include_line(line, include_base));
        text.push('\n');
    }
    if !parameter_overrides.is_empty() {
        text.push_str("* CircuitCI sweep parameter overrides.\n");
        for override_ in parameter_overrides {
            text.push_str(".param ");
            text.push_str(&override_.name);
            text.push('=');
            text.push_str(&format!("{:.12e}", override_.value));
            text.push('\n');
        }
        if let Some(temperature_c) = sweep_temperature_c(parameter_overrides) {
            text.push_str(".temp ");
            text.push_str(&format!("{:.12e}", temperature_c));
            text.push('\n');
        }
    }
    if !model_section_overrides.is_empty() {
        text.push_str("* CircuitCI sweep model section overrides.\n");
        for override_ in model_section_overrides {
            let path = Path::new(&override_.path);
            let absolute = if path.is_absolute() {
                normalize_path(path)
            } else {
                absolute_path(&bound.project.source_dir.join(path))
                    .unwrap_or_else(|_| normalize_path(&bound.project.source_dir.join(path)))
            };
            text.push_str(".lib \"");
            text.push_str(&absolute.to_string_lossy());
            text.push_str("\" ");
            text.push_str(&override_.section);
            text.push('\n');
        }
    }
    text.push_str(&format!(
        ".AC DEC {} {:.12e} {:.12e}\n",
        points_per_decade, start_hz, stop_hz
    ));
    text.push_str(".PRINT AC DELIMITER=COMMA FILE=\"");
    text.push_str(&raw_output.to_string_lossy());
    text.push('"');
    for probe in &analog.probes {
        text.push(' ');
        text.push_str(&probe.expression);
    }
    text.push_str("\n.END\n");
    Ok(text)
}

pub(super) fn build_xyce_dc_wrapper(
    bound: &BoundBoard<'_>,
    scenario: &Scenario,
    netlist: &Path,
    raw_output: &Path,
    parameter_overrides: &[ParameterOverride],
    model_section_overrides: &[ModelSectionOverride],
) -> Result<String, String> {
    let analog = scenario
        .analog
        .as_ref()
        .expect("analog was validated before Xyce DC wrapper generation");
    let source = fs::read_to_string(netlist).map_err(|error| {
        format!(
            "Failed to read SPICE netlist {}: {error}",
            netlist.display()
        )
    })?;
    let mut text = String::new();
    text.push_str("* Generated by CircuitCI for Xyce operating point. Do not edit by hand.\n");
    text.push_str("* Source netlist: ");
    text.push_str(&netlist.to_string_lossy());
    text.push('\n');
    let include_base = netlist.parent().unwrap_or(&bound.project.source_dir);
    let mut in_control_block = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        let directive = trimmed.to_ascii_lowercase();
        let first_token = directive.split_whitespace().next().unwrap_or("");
        if first_token == ".control" {
            in_control_block = true;
            continue;
        }
        if in_control_block {
            if first_token == ".endc" {
                in_control_block = false;
            }
            continue;
        }
        if matches!(first_token, ".end" | ".tran" | ".ac" | ".op" | ".print") {
            continue;
        }
        text.push_str(&rewrite_include_line(line, include_base));
        text.push('\n');
    }
    if !parameter_overrides.is_empty() {
        text.push_str("* CircuitCI sweep parameter overrides.\n");
        for override_ in parameter_overrides {
            text.push_str(".param ");
            text.push_str(&override_.name);
            text.push('=');
            text.push_str(&format!("{:.12e}", override_.value));
            text.push('\n');
        }
        if let Some(temperature_c) = sweep_temperature_c(parameter_overrides) {
            text.push_str(".temp ");
            text.push_str(&format!("{:.12e}", temperature_c));
            text.push('\n');
        }
    }
    if !model_section_overrides.is_empty() {
        text.push_str("* CircuitCI sweep model section overrides.\n");
        for override_ in model_section_overrides {
            let path = Path::new(&override_.path);
            let absolute = if path.is_absolute() {
                normalize_path(path)
            } else {
                absolute_path(&bound.project.source_dir.join(path))
                    .unwrap_or_else(|_| normalize_path(&bound.project.source_dir.join(path)))
            };
            text.push_str(".lib \"");
            text.push_str(&absolute.to_string_lossy());
            text.push_str("\" ");
            text.push_str(&override_.section);
            text.push('\n');
        }
    }
    text.push_str(".OP\n");
    text.push_str(".PRINT DC DELIMITER=COMMA FILE=\"");
    text.push_str(&raw_output.to_string_lossy());
    text.push('"');
    for probe in &analog.probes {
        text.push(' ');
        text.push_str(&probe.expression);
    }
    text.push_str("\n.END\n");
    Ok(text)
}

pub(super) fn build_xyce_noise_wrapper(
    bound: &BoundBoard<'_>,
    scenario: &Scenario,
    netlist: &Path,
    spectrum_raw_output: &Path,
    total_raw_output: &Path,
    parameter_overrides: &[ParameterOverride],
    model_section_overrides: &[ModelSectionOverride],
) -> Result<String, String> {
    let analog = scenario
        .analog
        .as_ref()
        .expect("analog was validated before Xyce noise wrapper generation");
    let source = fs::read_to_string(netlist).map_err(|error| {
        format!(
            "Failed to read SPICE netlist {}: {error}",
            netlist.display()
        )
    })?;
    let output_node = analog
        .analysis
        .noise_output_node
        .as_deref()
        .ok_or_else(|| "noise_output_node is required for noise analysis".to_string())?;
    let input_source = analog
        .analysis
        .noise_input_source
        .as_deref()
        .ok_or_else(|| "noise_input_source is required for noise analysis".to_string())?;
    let mut text = String::new();
    text.push_str("* Generated by CircuitCI for Xyce noise. Do not edit by hand.\n");
    text.push_str("* Source netlist: ");
    text.push_str(&netlist.to_string_lossy());
    text.push('\n');
    let include_base = netlist.parent().unwrap_or(&bound.project.source_dir);
    let mut in_control_block = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        let directive = trimmed.to_ascii_lowercase();
        let first_token = directive.split_whitespace().next().unwrap_or("");
        if first_token == ".control" {
            in_control_block = true;
            continue;
        }
        if in_control_block {
            if first_token == ".endc" {
                in_control_block = false;
            }
            continue;
        }
        if matches!(
            first_token,
            ".end" | ".tran" | ".ac" | ".op" | ".noise" | ".print"
        ) {
            continue;
        }
        let rewritten = rewrite_include_line(line, include_base);
        text.push_str(&ensure_noise_input_source_has_ac(&rewritten, input_source));
        text.push('\n');
    }
    if !parameter_overrides.is_empty() {
        text.push_str("* CircuitCI sweep parameter overrides.\n");
        for override_ in parameter_overrides {
            text.push_str(".param ");
            text.push_str(&override_.name);
            text.push('=');
            text.push_str(&format!("{:.12e}", override_.value));
            text.push('\n');
        }
        if let Some(temperature_c) = sweep_temperature_c(parameter_overrides) {
            text.push_str(".temp ");
            text.push_str(&format!("{:.12e}", temperature_c));
            text.push('\n');
        }
    }
    if !model_section_overrides.is_empty() {
        text.push_str("* CircuitCI sweep model section overrides.\n");
        for override_ in model_section_overrides {
            let path = Path::new(&override_.path);
            let absolute = if path.is_absolute() {
                normalize_path(path)
            } else {
                absolute_path(&bound.project.source_dir.join(path))
                    .unwrap_or_else(|_| normalize_path(&bound.project.source_dir.join(path)))
            };
            text.push_str(".lib \"");
            text.push_str(&absolute.to_string_lossy());
            text.push_str("\" ");
            text.push_str(&override_.section);
            text.push('\n');
        }
    }
    let output_expr = if let Some(reference_node) = analog.analysis.noise_reference_node.as_deref()
    {
        format!("V({output_node},{reference_node})")
    } else {
        format!("V({output_node})")
    };
    let start_hz = analog
        .analysis
        .start_frequency_hz
        .ok_or_else(|| "start_frequency_hz is required for noise analysis".to_string())?;
    let stop_hz = analog
        .analysis
        .stop_frequency_hz
        .ok_or_else(|| "stop_frequency_hz is required for noise analysis".to_string())?;
    let points = analog.analysis.points_per_decade.unwrap_or(20);
    text.push_str(&format!(
        ".NOISE {output_expr} {input_source} DEC {points} {start_hz:.12e} {stop_hz:.12e}\n"
    ));
    text.push_str(".PRINT NOISE DELIMITER=COMMA FILE=\"");
    text.push_str(&spectrum_raw_output.to_string_lossy());
    text.push_str("\" ONOISE INOISE\n");
    text.push_str(".PRINT NOISE DELIMITER=COMMA FILE=\"");
    text.push_str(&total_raw_output.to_string_lossy());
    text.push_str("\" ONOISE_TOTAL INOISE_TOTAL\n.END\n");
    Ok(text)
}

pub(super) fn build_xyce_sparameter_wrapper(
    bound: &BoundBoard<'_>,
    scenario: &Scenario,
    netlist: &Path,
    raw_output: &Path,
    parameter_overrides: &[ParameterOverride],
    model_section_overrides: &[ModelSectionOverride],
) -> Result<String, String> {
    let analog = scenario
        .analog
        .as_ref()
        .expect("analog was validated before Xyce S-parameter wrapper generation");
    let source = fs::read_to_string(netlist).map_err(|error| {
        format!(
            "Failed to read SPICE netlist {}: {error}",
            netlist.display()
        )
    })?;
    let start_hz = analog.analysis.start_frequency_hz.ok_or_else(|| {
        "analog.analysis.start_frequency_hz is required for S-parameter analysis.".to_string()
    })?;
    let stop_hz = analog.analysis.stop_frequency_hz.ok_or_else(|| {
        "analog.analysis.stop_frequency_hz is required for S-parameter analysis.".to_string()
    })?;
    let points_per_decade = analog.analysis.points_per_decade.unwrap_or(20);
    let mut text = String::new();
    text.push_str("* Generated by CircuitCI for Xyce S-parameter. Do not edit by hand.\n");
    text.push_str("* Source netlist: ");
    text.push_str(&netlist.to_string_lossy());
    text.push('\n');
    let include_base = netlist.parent().unwrap_or(&bound.project.source_dir);
    let mut in_control_block = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        let directive = trimmed.to_ascii_lowercase();
        let first_token = directive.split_whitespace().next().unwrap_or("");
        if first_token == ".control" {
            in_control_block = true;
            continue;
        }
        if in_control_block {
            if first_token == ".endc" {
                in_control_block = false;
            }
            continue;
        }
        if matches!(
            first_token,
            ".end" | ".tran" | ".ac" | ".op" | ".noise" | ".lin" | ".print"
        ) {
            continue;
        }
        text.push_str(&rewrite_include_line(line, include_base));
        text.push('\n');
    }
    if !parameter_overrides.is_empty() {
        text.push_str("* CircuitCI sweep parameter overrides.\n");
        for override_ in parameter_overrides {
            text.push_str(".param ");
            text.push_str(&override_.name);
            text.push('=');
            text.push_str(&format!("{:.12e}", override_.value));
            text.push('\n');
        }
        if let Some(temperature_c) = sweep_temperature_c(parameter_overrides) {
            text.push_str(".temp ");
            text.push_str(&format!("{:.12e}", temperature_c));
            text.push('\n');
        }
    }
    if !model_section_overrides.is_empty() {
        text.push_str("* CircuitCI sweep model section overrides.\n");
        for override_ in model_section_overrides {
            let path = Path::new(&override_.path);
            let absolute = if path.is_absolute() {
                normalize_path(path)
            } else {
                absolute_path(&bound.project.source_dir.join(path))
                    .unwrap_or_else(|_| normalize_path(&bound.project.source_dir.join(path)))
            };
            text.push_str(".lib \"");
            text.push_str(&absolute.to_string_lossy());
            text.push_str("\" ");
            text.push_str(&override_.section);
            text.push('\n');
        }
    }
    for (index, port) in analog.analysis.s_parameter_ports.iter().enumerate() {
        text.push_str(&format!(
            "P{} {} {} port={} z0={:.12e}\n",
            index + 1,
            port.positive_node,
            port.negative_node,
            index + 1,
            port.reference_impedance_ohm
        ));
    }
    text.push_str(&format!(
        ".AC DEC {} {:.12e} {:.12e}\n",
        points_per_decade, start_hz, stop_hz
    ));
    text.push_str(".LIN FORMAT=TOUCHSTONE DATAFORMAT=RI SPARCALC=1 FILE=\"");
    text.push_str(&raw_output.to_string_lossy());
    text.push_str("\"\n.END\n");
    Ok(text)
}

fn ensure_noise_input_source_has_ac(line: &str, input_source: &str) -> String {
    let trimmed = line.trim_start();
    let Some(first_token) = trimmed.split_whitespace().next() else {
        return line.to_string();
    };
    if !first_token.eq_ignore_ascii_case(input_source) {
        return line.to_string();
    }
    if trimmed
        .to_ascii_lowercase()
        .split_whitespace()
        .any(|token| token == "ac")
    {
        return line.to_string();
    }
    format!("{line} AC 1")
}
